### ISSUE TITLE
RuntimeError at import

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1005]
Hi,
Obspy import enter an infinite loop with this simple import
```python
 from obspy.seedlink.slpacket import SLPacket
```
I am using fcbabdd4a0640f688758afa55c65da019a80447c
and mac os 10.10.2

```log
Python 2.7.9 (default, Dec 12 2014, 09:50:09)
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from obspy.seedlink.slpacket import SLPacket
/usr/local/lib/python2.7/site-packages/obspy/__init__.py:164: ObsPyDeprecationWarning: Module 'obspy.seedlink' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.clients.seedlink'instead.
  ObsPyDeprecationWarning)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-5f6d2d2d345a> in <module>()
----> 1 from obspy.seedlink.slpacket import SLPacket

/usr/local/lib/python2.7/site-packages/obspy/__init__.pyc in load_module(self, name)
    168         # imports.
    169         else:
--> 170             module = importlib.import_module(name)
    171
    172         sys.modules[name] = module

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

/usr/local/lib/python2.7/site-packages/obspy/__init__.pyc in load_module(self, name)
    168         # imports.
    169         else:
--> 170             module = importlib.import_module(name)
    171
    172         sys.modules[name] = module

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

/usr/local/lib/python2.7/site-packages/obspy/__init__.pyc in load_module(self, name)
    168         # imports.
    169         else:
--> 170             module = importlib.import_module(name)
    171
    172         sys.modules[name] = module

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

/usr/local/lib/python2.7/site-packages/obspy/__init__.pyc in load_module(self, name)
    168         # imports.
    169         else:
--> 170             module = importlib.import_module(name)
    171
    172         sys.modules[name] = module

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

....

RuntimeError: maximum recursion depth exceeded while calling a Python object

```

**Comment by mbyt** [comment]
I can reproduce this running:
```
python -c "from obspy.seedlink.slpacket import SLPacket"
...
File "obspy/__init__.py", line 170, in load_module
    module = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "obspy/__init__.py", line 170, in load_module
    module = importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
RuntimeError: maximum recursion depth exceeded
```

So basically, the deprecaction stuff supporting the old module structure fails, When directly importing from the new module structure it works:
```
python -c "from obspy.client.seedlink.slpacket import SLPacket"
```

**Comment by krischer** [comment]
I can no longer reproduce it with the latest master. Can somebody confirm that this issue if fixed?

**Comment by megies** [comment]
On current master:
```
$ python -c "from obspy.seedlink.slpacket import SLPacket"
obspy/__init__.py:141: ObsPyDeprecationWarning: Module 'obspy.seedlink' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.clients.seedlink' instead.
  ObsPyDeprecationWarning)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named slpacket
$ python -c "import obspy; print obspy.__version__"
0.10.1.dev0+232.g08fd14ece7.obspy.master
```

**Comment by krischer** [comment]
Did you run `pip install` again? On my machine it works with Python 2.7 and Python 3.4 with exactly the same ObsPy version.

**Comment by megies** [comment]
Double checked, still getting this error.

**Comment by barsch** [comment]
works for me

```
D:\Python\virtualenv\obspy\64\Python27\Scripts>activate
(Python27) D:\Python\virtualenv\obspy\64\Python27\Scripts>python -c "from obspy.seedlink.slpacket import SLPacket"
d:\workspace\obspy\obspy\__init__.py:150: ObsPyDeprecationWarning: Module 'obspy.seedlink' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.clients.seedlink' instead.
  ObsPyDeprecationWarning)
d:\workspace\obspy\obspy\__init__.py:150: ObsPyDeprecationWarning: Module 'obspy.seedlink.slpacket' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.clients.seedlink.slpacket' instead.
  ObsPyDeprecationWarning)

(Python27) D:\Python\virtualenv\obspy\64\Python27\Scripts>python -c "import obspy; print obspy.__version__"
0.10.1.dev0+246.gaa9c8c439f.obspy.master
```

**Comment by krischer** [comment]
Alright. I think this can then be closed.
