### ISSUE TITLE
Problem with readEvents on mac

### ISSUE THREAD

**Issue by koenigpeter** [obspy/obspy#1017]
I have a problem with the readEvents routine (here imported as "read"). My script just wants to read from quakeml files and it works actually fine on linux in my institute. The exact same files however produce this error on my mac (os x 10.10, python and obspy installed via anaconda).
I tried changing the encoding of the script via vim, but that didn't help. 
Anyone an idea whats going on here?
```
Traceback (most recent call last):
  File "../seishub_extractcatalog1.py", line 66, in <module>
    cat = read(fn)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/decorator.py", line 307, in new_func
    return func(*args, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/event.py", line 140, in readEvents
    catalog = _read(pathnames[0], format, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/decorator.py", line 215, in wrapped_func
    result = func(filename, *args, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/event.py", line 154, in _read
    **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/base.py", line 394, in _readFromPlugin
    is_format = isFormat(filename)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/decorator.py", line 307, in new_func
    return func(*args, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/zmap/core.py", line 363, in isZmap
    first_line = first_line.decode('utf-8')
  File "/Users/Peter/anaconda/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by QuLogic** [comment]
Looks like new ZMAP support incorrectly assumes Unicode, and fails if it's not true (i.e., not a ZMAP file.)

Maybe you can try passing `format='quakeml'` to bypass autodetection since you already know the format.

**Comment by koenigpeter** [comment]
Sorry, that I only answer now, I couldn't test your solution now.
The passing of a format specifier produces a different error:
```
Traceback (most recent call last):
  File "../seishub_extractcatalog1.py", line 66, in <module>
    cat = read(fn, format='quakeml')
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/decorator.py", line 307, in new_func
    return func(*args, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/event.py", line 140, in readEvents
    catalog = _read(pathnames[0], format, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/decorator.py", line 215, in wrapped_func
    result = func(filename, *args, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/event.py", line 154, in _read
    **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/base.py", line 419, in _readFromPlugin
    list_obj = readFormat(filename, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/quakeml.py", line 1778, in readQuakeML
    return Unpickler().load(filename)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/quakeml.py", line 148, in load
    self.xml_doc = _xml_doc_from_anything(file)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/quakeml.py", line 80, in _xml_doc_from_anything
    source)
ValueError: Could not parse 'baynet030049.xml' to an etree element.
```

**Comment by QuLogic** [comment]
Based on the previous error complaining about `0xff`, I think your file may be corrupt. Have you tried opening it in a browser? Can you post it somewhere to view?

**Comment by koenigpeter** [comment]
ok, thanks, I tried that and you're completely right. I have no idea how the files got corrupted since I just copied them via USB stick from my institutes computer where they all were fine (and the code also worked on them on linux). But yeah, all of them are complete rubbish. 
When I use just one quakeml file now (which is not corrupted, I checked), the readEvents gives the following error:

```
Traceback (most recent call last):
  File "../seishub_extractcatalog1.py", line 66, in <module>
    cat = read(fn, format='quakeml')
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/decorator.py", line 307, in new_func
    return func(*args, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/event.py", line 140, in readEvents
    catalog = _read(pathnames[0], format, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/decorator.py", line 215, in wrapped_func
    result = func(filename, *args, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/event.py", line 154, in _read
    **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/util/base.py", line 419, in _readFromPlugin
    list_obj = readFormat(filename, **kwargs)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/quakeml.py", line 1778, in readQuakeML
    return Unpickler().load(filename)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/quakeml.py", line 148, in load
    self.xml_doc = _xml_doc_from_anything(file)
  File "/Users/Peter/anaconda/lib/python2.7/site-packages/obspy-0.10.1-py2.7-macosx-10.5-x86_64.egg/obspy/core/quakeml.py", line 80, in _xml_doc_from_anything
    source)
ValueError: Could not parse '.DS_Store' to an etree element.
```

**Comment by megies** [comment]
Do you happen to have something like `for filename in os.listdir("*")` in your code? It looks like you're running into hidden files..

**Comment by koenigpeter** [comment]
ah thank you! that's it. I'm using almost the exact code for that and there was in fact a hidden file in the directory.
I'm sorry for this. Thanks so much!
