### ISSUE TITLE
manpages to do not build correctly in a sand-boxed environment

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#1054]
In a sand-boxed environment (observed with MacPorts) the command: `python setup.py build build_man` will produce unexpected results.

This for example is `build/man/obspy-runtests.1`:
```
.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.46.6.
.TH PYTHON: "1" "May 2015" "Python: Could not load shared library "libmseed_Darwin_64bit_py27.so"." "User Commands"
.SH NAME
Python: \- manual page for Python: Could not load shared library "libmseed_Darwin_64bit_py27.so".
.SH DESCRIPTION
\fI\,/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python\/\fP.app/Contents/MacOS/Python: Could not load shared library "libmseed_Darwin_64bit_py27.so".
.IP
dlopen(obspy/core/util/../../lib/libmseed_Darwin_64bit_py27.so, 6): image not found
.IP
dlopen(obspy/core/util/../../lib/libmseed_Darwin_64bit_py27.so, 6): image not found
```

The following details should be addressed:

1. If the ObsPy scripts fails (here: image not found), `setup.py` should raise an exception, so that processing stops and the failure remains undetected and we install invalid manpages
1. Try to modify `Help2ManBuild` in a way, that scripts work correctly after a `build`.

**Comment by krischer** [comment]
It actually works fine for me in a clean environment. I cannot reproduce the issue.

**Comment by petrrr** [comment]
What you intend with "clean environment", maybe this should give a hints at what is missing.

**Comment by megies** [comment]
can you see/check/list at build time what libs are actually in `obspy/core/util/../../lib/`?

**Comment by krischer** [comment]
For me it builds in `build/lib.macosx-10.5-x86_64-3.4/obspy/lib/` and I guess it uses these then? The environment is clean in the sense that ObsPy is not installed and `obspy/obspy/lib` is empty.

**Comment by petrrr** [comment]
@megies: It's empty after the build.
```
petr% ls -la obspy/core/util/../../lib/
total 8
drwxr-xr-x   4 macports  admin   136 16 May 21:11 .
drwxr-xr-x  43 macports  admin  1462 19 May 15:04 ..
-rw-r--r--   1 macports  admin    36 16 May 21:11 .gitignore
-rw-r--r--   1 macports  admin   372 16 May 21:11 __init__.py
```
@krischer: Yes, the libraries are in the place your are indicating, however they are not loaded correctly, when the script is called.
```
petr% ls -la build/lib.macosx-10.8-x86_64-2.7/obspy/lib/
total 404
drwxr-xr-x   9 macports  admin     306 19 May 15:04 .
drwxr-xr-x  39 macports  admin    1326 19 May 15:04 ..
-rw-r--r--   1 macports  admin     372 16 May 21:11 __init__.py
-rwxr-xr-x   1 macports  admin  161252 19 May 15:04 libevresp_Darwin_64bit_py27.so
-rwxr-xr-x   1 macports  admin   15000 19 May 15:04 libgse2_Darwin_64bit_py27.so
-rwxr-xr-x   1 macports  admin  163764 19 May 15:04 libmseed_Darwin_64bit_py27.so
-rwxr-xr-x   1 macports  admin    8976 19 May 15:04 libsegy_Darwin_64bit_py27.so
-rwxr-xr-x   1 macports  admin   35916 19 May 15:04 libsignal_Darwin_64bit_py27.so
-rwxr-xr-x   1 macports  admin   13600 19 May 15:04 libtau_Darwin_64bit_py27.so
```

**Comment by petrrr** [comment]
But:
```
petr% python2.7 runtests.py
Traceback (most recent call last):
  File "runtests.py", line 14, in <module>
    from obspy.core.scripts.runtests import main
  File "/opt/local/var/macports/build/_Users_petr_sandbox_SVN-repos_macports_dports_python_py-obspy-devel/py27-obspy-devel/work/obspy-0.10.3rc1/obspy/__init__.py", line 47, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/opt/local/var/macports/build/_Users_petr_sandbox_SVN-repos_macports_dports_python_py-obspy-devel/py27-obspy-devel/work/obspy-0.10.3rc1/obspy/core/util/base.py", line 476, in make_format_plugin_table
    "obspy.plugin.%s.%s" % (group, name), method)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 546, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2339, in load
    return self.resolve()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/local/var/macports/build/_Users_petr_sandbox_SVN-repos_macports_dports_python_py-obspy-devel/py27-obspy-devel/work/obspy-0.10.3rc1/obspy/mseed/core.py", line 19, in <module>
    from obspy.mseed import util
  File "/opt/local/var/macports/build/_Users_petr_sandbox_SVN-repos_macports_dports_python_py-obspy-devel/py27-obspy-devel/work/obspy-0.10.3rc1/obspy/mseed/util.py", line 23, in <module>
    from obspy.mseed.headers import (ENCODINGS, ENDIAN,
  File "/opt/local/var/macports/build/_Users_petr_sandbox_SVN-repos_macports_dports_python_py-obspy-devel/py27-obspy-devel/work/obspy-0.10.3rc1/obspy/mseed/headers.py", line 22, in <module>
    clibmseed = _load_CDLL("mseed")
  File "/opt/local/var/macports/build/_Users_petr_sandbox_SVN-repos_macports_dports_python_py-obspy-devel/py27-obspy-devel/work/obspy-0.10.3rc1/obspy/core/util/libnames.py", line 97, in _load_CDLL
    raise ImportError(msg)
ImportError: Could not load shared library "libmseed_Darwin_64bit_py27.so".

 dlopen(/opt/local/var/macports/build/_Users_petr_sandbox_SVN-repos_macports_dports_python_py-obspy-devel/py27-obspy-devel/work/obspy-0.10.3rc1/obspy/core/util/../../lib/libmseed_Darwin_64bit_py27.so, 6): image not found
```

**Comment by megies** [comment]
Ah, OK, finally rings a bell and turns out I need to work around the exact same thing in some Debian package builds. Basically I copy the libs from the build dir back to the source tree, where build2man seems to look for it.
See here: https://github.com/obspy/obspy/blob/master/debian/pybuild/_copy_lib_extensions_to_source_tree.sh

I'm manually executing that script during build before the build2man: https://github.com/obspy/obspy/blob/master/debian/pybuild/rules#L45-L46

Sorry I didn't see earlier what's going on..

**Comment by petrrr** [comment]
Yes, this is exactly the same issue. I thought it might be worth, trying to fix this in the setup.py, so that this is universally valid. 

Also: I ideally would just do something elegant like `${python.bin} setup.py build build_man` in the build step. When I implement you trick, this would work and I need to get more complex.

**Comment by megies** [comment]
Really no chance to fix this in `setup.py`, I think, as it's severly tied to how packaging is handled depending on operating system, OS-dependent build system etcpp.

Only chance is to fix this in the packaging build scripts itself, like I do in `debian/rules`.

**Comment by megies** [comment]
We *could* build man pages statically and keep them in `misc/source` somewhere (even if only for macports). But that would introduce the possibility that we forget to update and they get outdated at some point. And even then you would need to adapt the packaging to copy those man pages around.. no?

**Comment by QuLogic** [comment]
Have you tried this?
```
python setup.py build
PYTHONPATH=$(pwd)/build/lib.macosx-10.5-x86_64-3.4 python setup.py build_man
```

**Comment by petrrr** [comment]
Okay, I did this linking into the source tree stuff. But I honestly find this pretty hacky (and potentially error prone).
 
The point here is that actually you cannot run all these `obspy-*`scripts right after the build step. And I doubt this would works on any OS, and if it works it very probably uses an already installed version not necessary the one you would like to run against. I do not see an OS/packaging system dependency here.

Also if the run of the script fails (e.g. because the shared libraries are not found), it passes undetected, because `strerr` just finishes as output in the manpage files. You just install invalid manpages.

What also puzzles me is why actually the install step reruns the build step.

**Comment by megies** [comment]
See also #1272.
