### ISSUE TITLE
Taup - get_travel_times error with depth close to 0.

### ISSUE THREAD

**Issue by ThomasLecocq** [obspy/obspy#1057]
```python
from obspy.geodetics.base import kilometer2degrees
from obspy.taup import TauPyModel
model = TauPyModel(model="iasp91")
arrivals = model.get_travel_times(source_depth_in_km=0.0015,
                                  distance_in_degree=kilometer2degrees(200.),
                                  )
print arrivals
```

fails miserably:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from obspy.geodetics.base import kilometer2degrees
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\__init__.py", line 41, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\core\__init__.py", line 120, in <module>
    from obspy.core.util import DynamicAttributeImportRerouteModule
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\core\util\__init__.py", line 39, in <module>
    from obspy.core.util.obspy_types import (ComplexWithUncertainties, Enum,
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\core\util\obspy_types.py", line 16, in <module>
    with standard_library.hooks():
  File "C:\Anaconda\lib\site-packages\future\standard_library\__init__.py", line 323, in __enter__
    install_hooks()
  File "C:\Anaconda\lib\site-packages\future\standard_library\__init__.py", line 528, in install_hooks
    install_aliases()
  File "C:\Anaconda\lib\site-packages\future\standard_library\__init__.py", line 482, in install_aliases
    import test
  File "C:\Users\tlecocq\Desktop\test.py", line 5, in <module>
    distance_in_degree=kilometer2degrees(200.),
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\taup\tau.py", line 330, in get_travel_times
    tt.run()
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\taup\taup_time.py", line 37, in run
    self.depth_correct(self.depth)
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\taup\taup_time.py", line 49, in depth_correct
    self.recalc_phases()
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\taup\taup_time.py", line 72, in recalc_phases
    self.depth_corrected_model)
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\taup\seismic_phase.py", line 110, in __init__
    self.sum_branches(tMod)
  File "c:\users\tlecocq\desktop\tmp\obspy\obspy\taup\seismic_phase.py", line 618, in sum_branches
    self.ray_param = tMod.ray_param.copy()
AttributeError: 'TauModel' object has no attribute 'ray_param'
```

but it looks it's only for specific phases, setting ```phase_list=["Pn", "Pg"]``` works.

**Comment by krischer** [comment]
This is a bit nasty. I think the error comes from the depth correction of the model but I am not yet sure. In any case, here is a more focused snippet. `s` is a strictly upwards travelling S-wave.

```python
from obspy.taup import TauPyModel

model = TauPyModel(model="iasp91")

arrivals = model.get_travel_times(
    source_depth_in_km=0.6, distance_in_degree=1.0,
    phase_list=["s"])

print(arrivals)
```
