### ISSUE TITLE
ImportError: Could not load shared library "libmseed_Linux_64bit_py27.so".

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1076]
##### I installed the latest Anaconda (Python 2.7.10) and obspy (0.10.2) on Linux. It's OK to import other modules but when I import obspy, I got an ImportError: Could not load shared library "libmseed_Linux_64bit_py27.so", because /lib64/libc.so.6: version `GLIBC_2.7' not found.

    >>> import obspy
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/__init__.py", line 47, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/core/util/base.py", line 476, in make_format_plugin_table
    "obspy.plugin.%s.%s" % (group, name), method)
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 2345, in load
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/mseed/core.py", line 19, in <module>
    from obspy.mseed import util
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/mseed/util.py", line 23, in <module>
    from obspy.mseed.headers import (ENCODINGS, ENDIAN,
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/mseed/headers.py", line 22, in <module>
    clibmseed = _load_CDLL("mseed")
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/core/util/libnames.py", line 97, in _load_CDLL
    raise ImportError(msg)
ImportError: Could not load shared library "libmseed_Linux_64bit_py27.so".

 /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/core/util/../../lib/libmseed_Linux_64bit_py27.so)
	
```
##### I checked libc.so.6 by 

          >> strings /lib64/libc.so.6 | grep GLIBC
```
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_PRIVATE
```
##### It looks glibc is too old. I compiled glibc2.7 from the source and 

         >> export LD_PRELOAD=/path/to/libc-2.7.so

##### I find the libmseed.so from an old version of obspy (/obspy.mseed-0.4.7-py2.7-linux-x86_64.egg) and replace libmseed_Linux_64bit_py27.so with this old one. But it doesn't work.

         >>> import obspy
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/__init__.py", line 47, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/core/util/base.py", line 476, in make_format_plugin_table
    "obspy.plugin.%s.%s" % (group, name), method)
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 2345, in load
  File "/home/me/anaconda/lib/python2.7/site-packages/setuptools-17.0-py2.7.egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/mseed/core.py", line 19, in <module>
    from obspy.mseed import util
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/mseed/util.py", line 23, in <module>
    from obspy.mseed.headers import (ENCODINGS, ENDIAN,
  File "/home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/mseed/headers.py", line 519, in <module>
    C.c_short]
  File "/home/me/anaconda/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/home/me/anaconda/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/me/anaconda/lib/python2.7/site-packages/obspy-0.10.2-py2.7-linux-x86_64.egg/obspy/core/util/../../lib/libmseed_Linux_64bit_py27.so: undefined symbol: ms_readtraces_timewin
```

Is there any solution? Can people provide a libmseed_Linux_64bit_py27.so with a lower version of glibc?

**Comment by QuLogic** [comment]
> on Linux

There are about a million distributions, so which one and what version?

> It looks glibc is too old. I compiled glibc2.7 from the source and

That is extreme overkill.

**Comment by lileipku00** [comment]
My libc.so.6 is valid from GLIBC_2.2.5 to GLIBC_2.5

**Comment by QuLogic** [comment]
Please answer the question I asked.

**Comment by lileipku00** [comment]
You mean the version of Linux?

       >>cat /proc/version
Linux version 2.6.18-274.el5 (mockbuild@x86-002.build.bos.redhat.com) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-51)) #1 SMP Fri Jul 8 17:36:59 EDT 2011

          >>uname -a
Linux server 2.6.18-274.el5 #1 SMP Fri Jul 8 17:36:59 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux

And another one,

           >>cat /proc/version
Linux version 2.6.18-398.el5 (mockbuild@builder17.centos.org) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-55)) #1 SMP Tue Sep 16 20:50:52 EDT 2014

          >>uname -a
Linux server 2.6.18-398.el5 #1 SMP Tue Sep 16 20:50:52 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lileipku00** [comment]
>>lsb_release -a
```
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 5.7 (Tikanga)
Release:        5.7
Codename:       Tikanga
```
and

            >>lsb_release -a
```
LSB Version:    :core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 5.11 (Final)
Release:        5.11
Codename:       Final
```


There is libc-2.14.so on the servers. But I got nothing except Segment Fault if I export it in  LD_LIBRARY_PATH.

**Comment by lileipku00** [comment]
And I'm not sure libmseed**.so will be the only one raising error...

**Comment by QuLogic** [comment]
You are using either RHEL 5 or CentOS 5. That was released 8 years ago and is only receiving security fixes. Thus, I cannot really confirm whether these instructions will work. You can follow the [instructions for building from source](https://github.com/obspy/obspy/wiki/Installation-via-PyPi-from-source), but _first_ activate the anaconda installation so that it is installed there (and uses its newer Python) instead of system-wide.

**Comment by QuLogic** [comment]
Please stop by the [Gitter chat room](https://gitter.im/obspy/obspy) if you need to discuss this more      comprehensively.

**Comment by lileipku00** [comment]
Nice Gitter. Thx @QuLogic .

**Comment by lileipku00** [comment]
It works. I installed from source.

Thanks a lot @QuLogic
