### ISSUE TITLE
Raspbian Jessie packages

### ISSUE THREAD

**Issue by bonaime** [obspy/obspy#1134]
Is there any plan for obspy on Raspbian Jessie ? And also with linux-armv7l  (Raspberry Pi 2) ? 

Raspberry Pi 2 is really more powerfull than Raspberry Pi 
Raspbian Jessie which was released recently (2015-09-24)  has a more recent matplotlib package (1.4.2-3.1) than Raspbian Wheezy (1.1.1~rc2-1)

Thank you

**Comment by megies** [comment]
There's no change package-wise from Raspberry Pi 1 to 2 (at least when using Raspbian wheezy, but I guess it's the same for jessie). "Debian architecture" is still `armhf`. Just use the same aptitude package install routine on Raspi2.

.. I wasn't aware yet there was official Jessie support now for Raspberry.. I might set it up at some point I guess on my old Raspi1. If you want it now, you can try to build the packages, too, if you like.

No big deal (in principle, it's a new build system for Jessie, so there might be some unanticipated glitches?):

 - install build dependencies via aptitude (https://github.com/obspy/obspy/blob/master/debian/pybuild/control#L7-L11)
 - git clone and checkout the `releases` (or `master` should be fine too, I think) branch from obspy/obspy
 - go to `misc/debian` and run `$ ./deb__build_debs.sh -f megies -t deb_0.10.2` to build the current stable release

**Comment by megies** [comment]
I've built packages, but wasn't able to test them yet (no root access on the box I used). You can try them out if you like:
https://www.geophysik.uni-muenchen.de/~megies/.obspy_raspi2_debs/

**Comment by bonaime** [comment]
Strating with a new fresh version, 
I had to install dependencies:
```code
sudo apt-get install python-lxml python-scipy python-sqlalchemy python-suds python-tornado 
sudo pip install future
```
then there is an installation problem with python-future
```code
dpkg -i python-obspy_0.10.2-3~jessie_armhf.deb
(Reading database ... 117809 files and directories currently installed.)
Preparing to unpack python-obspy_0.10.2-3~jessie_armhf.deb ...
Unpacking python-obspy (0.10.2-3~jessie) over (0.10.2-3~jessie) ...
dpkg: dependency problems prevent configuration of python-obspy:
 python-obspy depends on python-future (>= 0.12.4); however:
  Package python-future is not installed.

dpkg: error processing package python-obspy (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.0.2-5) ...
Errors were encountered while processing:
 python-obspy
```

But future is installed
```code
root@raspberrypi:/home/pi/obspy# pip show future

Name: future
Version: 0.15.2
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```

**Comment by megies** [comment]
I would **really** recommend to avoid manual installs into the global system, which is package controlled, whenever possible..
I've packaged `python-future` and `python3-future` for Debian/Ubuntu, you can install it via aptitude/apt-get once you added the obspy deb repository to your sources.list and updated the package lists..

I would recommend you do a `pip remove future` and install it via the packaging system.

**Comment by bonaime** [comment]
I removed future with pip and the added in /etc/apt/sources.list
```code
deb http://deb.obspy.org jessie main
````
and the I added the  gnupg key
````code
root@raspberrypi:/home/pi# wget --quiet -O - https://raw.github.com/obspy/obspy/master/misc/debian/public.key | sudo apt-key add -
OK
````
But the apt-get update fails:
```code
W: Failed to fetch http://deb.obspy.org/dists/jessie/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
````

**Comment by megies** [comment]
Sorry, I hadn't added `armhf` to the config file for `jessie` yet. Did so now, should work now. Can you please try again?

**Comment by bonaime** [comment]
Maybe you should also add lines for armhf in 
http://deb.obspy.org/dists/jessie/InRelease

On the Wheezy version the InRelease file contains
Architectures: amd64 i386 armhf
and six lines related to armhf

**Comment by megies** [comment]
OK, sorry again, had to run an export command to get the changes to spread through the complete hierarchy.. should work now..  ;-)

**Comment by bonaime** [comment]
nto working. Here is the error of apt-get update
```error
Hit http://deb.obspy.org jessie InRelease
Ign http://archive.raspberrypi.org jessie/ui Translation-en
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie/main Sources
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Hit http://deb.obspy.org jessie/main armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://deb.obspy.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://deb.obspy.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Hit http://archive.raspberrypi.org jessie/main Sources
Hit http://archive.raspberrypi.org jessie/ui Sources
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Ign http://deb.obspy.org jessie/main Translation-en_GB
Ign http://deb.obspy.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Reading package lists... Done
`````
I have updated the public.key
````root@raspberrypi:/tmp# wget --quiet -O - https://raw.github.com/obspy/obspy/master/misc/debian/public.key | sudo apt-key add -
OK
```

**Comment by megies** [comment]
Uhm.. sorry, but where's the error message? I don't see any obvious errors in the last comment..

**Comment by bonaime** [comment]
sorry, wrong paste ! I updated my last comment..

**Comment by megies** [comment]
Ok, sorry.. again.. should work now? 
It wasn't enough to just add `armhf` architecture to `jessie` release but I needed to add the respective deb files to its database..

**Comment by bonaime** [comment]
I just installed obspy !
I will give you more information in 2 weeks as I will be in the field...

**Comment by megies** [comment]
Finally. :-) 

Would be great if you could run `/usr/bin/obspy-runtests -r` on that machine (it'll take quite a while though)..

**Comment by bonaime** [comment]
http://tests.obspy.org/29246/

**Comment by megies** [comment]
Only image tests failing..

**Comment by bonaime** [comment]
http://tests.obspy.org/29278/
after installing mpl_toolkits.basemap, pyflakes and pyimgur

**Comment by krischer** [comment]
Can you please run it once again with

```bash
$ OBSPY_KEEP_IMAGES= obspy-runtests
```

Then the test images should be uploaded to the test reporting page.

**Comment by megies** [comment]
Unfortunately that doesn't work if you run tests as user, due to file permissions in `/usr`. It should work if you run it as root, if you don't mind. But then there's additional files sticking around in `/usr`, which won't get deleted during package uninstall. Well, mostly cosmetics, I guess..
Another option is to set `export OBSPY_IMGUR_CLIENTID` beforehand (see 3d094be090a). We don't get the nice diffs in the test pages then but at least the images can be viewed online.

**Comment by bonaime** [comment]
http://tests.obspy.org/29408/
as root

**Comment by megies** [comment]
Hmm, sorry, guess the setting the IMGUR ID thing has to be done as well, to have the images show up in the test.. can you doh it again, please?

**Comment by bonaime** [comment]
export OBSPY_IMGUR_CLIENTID
OBSPY_KEEP_IMAGES= obspy-runtests
http://tests.obspy.org/29429/
But I don't think that the images has been sent...

**Comment by megies** [comment]
Sorry, thought it was clear, and wanted to avoid posting the ID here. Anyway, you need to `export OBSPY_IMGUR_CLIENTID=53b182544dc5d89`.

**Comment by bonaime** [comment]
http://tests.obspy.org/29443/
with images !

**Comment by bonaime** [comment]
it seems it is a font problem...

**Comment by krischer** [comment]
Ah yea...I've actually seen that a lot.

```bash
$ sudo apt-get install ttf-bitstream-vera
``` 

should fix it. To me this looks like a matplotlib packaging problem - they should make sure to ship with the default font. Or maybe we could make it a dependency of the obspy debian packages?

**Comment by megies** [comment]
> http://tests.obspy.org/29443/
> with images !

Thanks! :+1: 

> To me this looks like a matplotlib packaging problem - they should make sure to ship with the default font. Or maybe we could make it a dependency of the obspy debian packages?

I'll add it as a `Recommends:`, that doesn't hurt.
I've also did that with `python-tornado`, due to a problem with tornado not made optional correctly at some point by matplotlib (see matplotlib/matplotlib#3039, which is fixed now).

But I'll report this to Debian packaging of matplotlib, it should definitely be in their `Recommends:`.

---
Update:

Actually, I just checked and I don't have `ttf-bitstream-vera` package installed... and `imaging` tests run fine for me. I checked and Bitstream Vera comes directly from my matplotlib install in Anaconda:
```python
from matplotlib import font_manager
font_manager.findfont('Bitstream Vera Sans')
```
```
'...anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/Vera.ttf'
```
See https://github.com/matplotlib/matplotlib/tree/master/lib/matplotlib/mpl-data/fonts/ttf.

---
Update:

Seems these ttf fonts get stripped in packaging, I don't have them installed via `python-matplotlib-data`, although these ttf files have lived in `matplotlib/lib/matplotlib/mpl-data/fonts/ttf` for ages. In that case they should add the correct `Depends:` though..
```
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/LICENSE_STIX
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXGeneral.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXGeneralBol.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXGeneralBolIta.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXGeneralItalic.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXNonUni.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXNonUniBol.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXNonUniBolIta.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXNonUniIta.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizFiveSymReg.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizFourSymBol.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizFourSymReg.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymBol.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymReg.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizThreeSymBol.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizThreeSymReg.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizTwoSymBol.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/STIXSizTwoSymReg.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/cmex10.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/cmr10.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/cmss10.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf
python-matplotlib-data: /usr/share/matplotlib/mpl-data/fonts/ttf/cmtt10.ttf
```

**Comment by bonaime** [comment]
after installing  ttf-bitstream-vera
http://tests.obspy.org/29445/

**Comment by megies** [comment]
My guess is that the font cache might not get updated.. maybe try to remove/reinstall matplotlib with the vera package already there?

**Comment by megies** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802776

**Comment by bonaime** [comment]
http://tests.obspy.org/29461/
after  remove/reinstall matplotlib and then reinstall obspy and obspy-tests

**Comment by QuLogic** [comment]
The font cache is in `~/.cache/matplotlib`.

**Comment by megies** [comment]
Yep, just tried it here, can confirm. You need to `rm ~/.cache/matplotlib` so that matplotlib builds font cache from scratch when next imported..

**Comment by bonaime** [comment]
after removing ~/.cache/matplotlib
http://tests.obspy.org/29517/
I can see only one error in the report while in the console I have other warnings and errors:
```log
...
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
.............................................................................................Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/obspy/mseed/core.py", line 346, in log_error_or_warning
    raise InternalMSEEDReadingError(msg[7:].strip())
obspy.mseed.core.InternalMSEEDReadingError: Invalid blockette offset (12365) less than or equal to current offset (12365)
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

======================================================================
ERROR: test_flake8 (obspy.core.tests.test_code_formatting.CodeFormattingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/obspy/core/tests/test_code_formatting.py", line 27, in test_flake8
    report, message = check_flake8()
  File "/usr/lib/python2.7/dist-packages/obspy/core/util/testing.py", line 533, in check_flake8
    raise Exception('flake8 is required to check code formatting')
Exception: flake8 is required to check code formatting

----------------------------------------------------------------------
Ran 1195 tests in 2919.271s
```

I will put here the complete console log in few minutes

**Comment by megies** [comment]
:+1: All good! No need to check code formatting with flake8, we only use it for development purposes. The other message are OK, that's kind of expected output during test runs.

**Comment by bonaime** [comment]
```log
OBSPY_KEEP_IMAGES= obspy-runtests
...........................................................................................................................................................................................................................................................................................................ss...................................................................................................................................................................................................................................................................................Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
Warning: underflow encountered in multiply
.............s.....Warning: underflow encountered in multiply
.Warning: underflow encountered in multiply
.Warning: underflow encountered in multiply
..............Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
.............................................................................................Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/lib/python2.7/dist-packages/obspy/mseed/core.py", line 346, in log_error_or_warning
    raise InternalMSEEDReadingError(msg[7:].strip())
obspy.mseed.core.InternalMSEEDReadingError: Invalid blockette offset (12365) less than or equal to current offset (12365)
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 1195 tests in 2947.773s
```

**Comment by bonaime** [comment]
How it is possible to get my OBSPY_IMGUR_CLIENTID ?

**Comment by bonaime** [comment]
https://github.com/obspy/obspy/commit/3ac89074069676db71858a0a596d466d3475879d#commitcomment-12070739

**Comment by krischer** [comment]
Well you could get your own one at the imgur website or you just leave it empty and it will use the default ObsPy one.

**Comment by bonaime** [comment]
With OBSPY_VERSION 1.0.0, I have some error after running
```
OBSPY_KEEP_IMAGES= obspy-runtests -r
```
```Imgur ERROR message: read error on connection```

The test ends with
```
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
Warning: invalid value encountered in sign
FFF....FFF..............................................................................................................................................
................................................................................s.......................................................................
........................................................................................................................................................
.........................................................................................................................F....F.........................
..............F.F................F.............F.............................................................FFFFFFFKilled
````
and nothing is send to http://tests.obspy.org/

The "Killed" at the end is very strange !

I installed 1.0.0 with apt-get

**Comment by megies** [comment]
Seems related to connecting to imgur? Can you try a couple of times, whether you always get the same error (maybe not doing all tests..)?

**Comment by bonaime** [comment]
I installed ttf-bitstream-vera, re install matplotlib and then Obspy and I have the following errors for test_event.py:

```
.............../usr/lib/python2.7/dist-packages/obspy/core/util/testing.py:362: UserWarning: Could not set locale to English/United States. Some date-rel
ated tests may fail
  warnings.warn(msg)
/usr/lib/python2.7/dist-packages/obspy/core/util/testing.py:371: UserWarning: Unable to find the Bitstream Vera Sans font. Plotting tests will likely fai
l.
  warnings.warn('Unable to find the Bitstream Vera Sans font. '
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1279: UserWarning: findfont: Font family [u'Bitstream Vera Sans'] not found. Falling back to
Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1289: UserWarning: findfont: Could not match :family=Bitstream Vera Sans:style=normal:variant
=normal:weight=heavy:stretch=normal:size=12.0. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
FFFsss.../usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1289: UserWarning: findfont: Could not match :family=Bitstream Vera Sans:style=norma
l:variant=normal:weight=normal:stretch=normal:size=large. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
  UserWarning)
F..............
======================================================================
FAIL: test_catalog_plot_global (__main__.CatalogBasemapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_event.py", line 485, in test_catalog_plot_global
    cat.plot(method='basemap', outfile=ic.name)
  File "/usr/lib/python2.7/dist-packages/obspy/core/util/testing.py", line 447, in __exit__
    raise ImageComparisonException(msg)
ImageComparisonException: Image comparison failed.
        RMS:       16.5793003347
        Tolerance: 3.0
        Expected:  http://i.imgur.com/amrUTJG.png
        Actual:    http://i.imgur.com/v3gEqDi.png
        Diff:      http://i.imgur.com/8Jb4ufs.png

======================================================================
FAIL: test_catalog_plot_local (__main__.CatalogBasemapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_event.py", line 515, in test_catalog_plot_local
    color='date', colormap='gist_heat')
  File "/usr/lib/python2.7/dist-packages/obspy/core/util/testing.py", line 447, in __exit__
    raise ImageComparisonException(msg)
ImageComparisonException: Image comparison failed.
        RMS:       22.1329209741
        Tolerance: 4.5
        Expected:  http://i.imgur.com/t2zrm5B.png
        Actual:    http://i.imgur.com/2cRHWXc.png
        Diff:      http://i.imgur.com/GwLvR3K.png

======================================================================
FAIL: test_catalog_plot_ortho (__main__.CatalogBasemapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_event.py", line 497, in test_catalog_plot_ortho
    color='date')
  File "/usr/lib/python2.7/dist-packages/obspy/core/util/testing.py", line 447, in __exit__
    raise ImageComparisonException(msg)
ImageComparisonException: Image comparison failed.
        RMS:       15.5892378809
        Tolerance: 3.0
        Expected:  http://i.imgur.com/TbJjEWO.png
        Actual:    http://i.imgur.com/8ide2Tl.png
        Diff:      http://i.imgur.com/S7ZICxe.png

======================================================================
FAIL: test_plot_farfield_without_quiver_with_maps (__main__.EventTestCase)
Traceback (most recent call last):
  File "test_event.py", line 147, in test_plot_farfield_without_quiver_with_maps
    ['p_sphere', 's_sphere']], outfile=ic.name)
  File "/usr/lib/python2.7/dist-packages/obspy/core/util/testing.py", line 447, in __exit__
    raise ImageComparisonException(msg)
ImageComparisonException: Image comparison failed.
        RMS:       49.2872234966
        Tolerance: 3.0
        Expected:  http://i.imgur.com/Rwu7raw.png
        Actual:    http://i.imgur.com/femFlrk.png
        Diff:      http://i.imgur.com/dcgLAYK.png

----------------------------------------------------------------------
Ran 39 tests in 303.607s

FAILED (failures=4, skipped=3)

**Comment by megies** [comment]
The thing with bitstream vera I reported to Debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802776), it's fixed for the future but the Jessie packages still have it.

I think you need to get rid of your mpl font cache (normally ~/.matplotlib/..), it's not automatically regenerated and the font isn't in there because it was created before you installed the font.
Then please try again.
