### ISSUE TITLE
Error using obspy.taup.get_travel_times()

### ISSUE THREAD

**Issue by FadelI** [obspy/obspy#1342]

**Comment by krischer** [comment]
Aeehm...if you actually intend to open an issue - please edit this one instead of creating a new one!

**Comment by FadelI** [comment]
Hi All,

I deigned a code earlier using ObsPy 0.10.2 where I used obspy.taup module to calculate the arrivals of an Earthquake. However, when I run the code using the recent version of ObsPy 1.0, I receive an error that was not appearing in the previous version. The code simply read Earthquake catalog and do looping over each event and calculate the travel times using this command:
>>   tt = model.get_travel_times(source_depth_in_km = eqdepth, distance_in_degree = distdeg) 
The error is not related to the data file or the earthquake event since it worked using the same file and the same event out of the loop. 

The error appears:
--------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/PATH/01_Get_EQ.py", line 142, in <module>
    distance_in_degree=distdeg)

  File "/usr/local/anaconda/lib/python2.7/site-packages/obspy/taup/tau.py", line 359, in get_travel_times
    tt.run()

  File "/usr/local/anaconda/lib/python2.7/site-packages/obspy/taup/taup_time.py", line 38, in run
    self.depth_correct(self.source_depth, self.receiver_depth)

  File "/usr/local/anaconda/lib/python2.7/site-packages/obspy/taup/taup_time.py", line 50, in depth_correct
    self.depth_corrected_model = self.model.depth_correct(depth)

  File "/usr/local/anaconda/lib/python2.7/site-packages/obspy/taup/tau_model.py", line 232, in depth_correct
    return self.load_from_depth_cache(depth)

  File "/usr/local/anaconda/lib/python2.7/site-packages/obspy/taup/tau_model.py", line 256, in load_from_depth_cache
    self._depth_cache.pop(last=False)

TypeError: pop() got an unexpected keyword argument 'last'
-------------------------------------------------------------------------------------------------------------------------------
When I changed tau.model.py file (lines 255-257):
-------------------------------------------------------------------------------------------------------------------------------
            while len(self._depth_cache) > 128:
                self._depth_cache.pop(last=False)
            return value
to :
            while len(self._depth_cache) > 128:
                self._depth_cache.pop(depth)
            return value
-------------------------------------------------------------------------------------------------------------------------------
The code worked fine without any complains. 
Please let me know if such work around does not harm any other things.
My previous ObsPy 0.10.2 was installed on Debian 8 "Jessie" using Apt Repository
My current version is ObsPy 1.0 and installed using Anaconda on Ubuntu 15.1.
Thank you in advance,
Fadel

**Comment by megies** [comment]
This is fixed in the current maintenance branch, see #1308. We will release a bug fix release including this fix within 1-2 weeks.
