### ISSUE TITLE
obspy-indexer not working

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#1369]
obspy-indexer does not work. I tried sqlalchemy versions 0.7, 0.8, 0.9 and 1.0. Its always the same error:

```
2016-04-12 11:47:36,562 [INFO] Starting indexer localhost:0 ...
Traceback (most recent call last):
  File "/home/richter/anaconda/bin/obspy-indexer", line 9, in <module>
    load_entry_point('obspy==1.0.1', 'console_scripts', 'obspy-indexer')()
  File "/home/richter/anaconda/lib/python2.7/site-packages/obspy/db/scripts/indexer.py", line 259, in main
    _run_indexer(args)
  File "/home/richter/anaconda/lib/python2.7/site-packages/obspy/db/scripts/indexer.py", line 146, in _run_indexer
    convert_unicode=True)
  File "/home/richter/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/richter/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dialect = dialect_cls(**dialect_args)
  File "/home/richter/anaconda/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 546, in __init__
    PGDialect.__init__(self, **kwargs)
  File "/home/richter/anaconda/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2022, in __init__
    default.DefaultDialect.__init__(self, **kwargs)
  File "/home/richter/anaconda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 213, in __init__
    encoding
  File "/home/richter/anaconda/lib/python2.7/site-packages/sqlalchemy/processors.py", line 138, in to_unicode_processor_factory
    return UnicodeResultProcessor(encoding).process
TypeError: __init__() argument 1 must be string, not unicode
```

I use a postgresql database. I did not try different obspy versions. I only know its working for `obspy=0.9` (also a requirement for seishub).

**Comment by megies** [comment]
That's almost certainly a `future` related problem (some piece(s) needing an `.encode()` or `.decode()`).

**Comment by trichter** [comment]
Unrelated related: The default Seishub server at teide is not reachable at the moment.

**Comment by megies** [comment]
> Seishub server at teide is not reachable at the moment

It never was.. it's an internal server at LMU.

**Comment by megies** [comment]
You could try to use a `... encoding=native_str('utf-8'), ...)` in this line: https://github.com/obspy/obspy/blob/master/obspy/db/scripts/indexer.py#L145

But probably there's gonna be more issues..

**Comment by trichter** [comment]
> It never was.. it's an internal server at LMU.

I see. I think thats the second time I stumbled over this default. :grimacing:
Maybe, we should change it to `http://localhost:8080` as this is the default in seishub?

> You could try to use a ... encoding=native_str('utf-8'), ...) in this line:  https://github.com/obspy/obspy/blob/master/obspy/db/scripts/indexer.py#L145

That's working! Do you have a sixth sense for `future`?

**Comment by megies** [comment]
> That's working! Do you have a sixth sense for future?

No, but we had to fix tons of these problems during migration to Py2+3 compatibility

> Maybe, we should change it to http://localhost:8080 as this is the default in seishub?

Not sure.. while I agree that in general it might not have been the best idea to put it as a default, it has been like this for years and some people working here at LMU might get their programs broken if we change it. I would agree though, that it would make sense to have some check running right after initialization that tries some handshake and raises if no server is encountered.

**Comment by megies** [comment]
Please reopen if there's other problems.
