### ISSUE TITLE
String representations of Event type objects are not unicode-safe

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1482]
Having non-ascii characters in Event type objects' fields leads to errors when trying to print their string representation (due to our (mis-?)use of `future`). E.g.:

``` python
# -*- coding: utf-8 -*-
from obspy.core.event import Event, Comment

e = Event()
e.comments.append(Comment(text=u"Somé Unicôde"))

print(e.comments)
```

```
Traceback (most recent call last):
  File "event_unicode.py", line 7, in <module>
    print(e.comments)
  File "/home/megies/git/obspy-maintenance_1.0.x/obspy/core/event/base.py", line 316, in __repr__
    return self.__str__(force_one_line=True)
  File "/home/megies/git/obspy-maintenance_1.0.x/obspy/core/event/base.py", line 286, in __str__
    for _i in attributes if _bool(getattr(self, _i))]
  File "/home/megies/git/obspy-maintenance_1.0.x/obspy/core/event/base.py", line 270, in get_value_repr
    value = native_str(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2: ordinal not in range(128)
```

The catalog can be output to QuakeML just fine, with proper Unicode encoding.

**Comment by QuLogic** [comment]
I didn't read what's in `get_value_repr`, but since we should be deriving from future's `object`, our `__str__` should always produce "unicode", not a native `str`.

**Comment by megies** [comment]
This isn't an issue on current master on Python 3
