### ISSUE TITLE
SSL certificates of obspy domains fail to verify

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1583]
```
======================================================================
ERROR: test_read (obspy.core.tests.test_stream.StreamTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "obspy\core\tests\test_stream.py", line 1720, in test_read
    tr = read('https://examples.obspy.org/test.sac', dtype=np.int32)[0]
  File "<decorator-gen-31>", line 2, in read
  File "obspy\core\util\decorator.py", line 294, in _map_example_filename
    return func(*args, **kwargs)
  File "obspy\core\stream.py", line 225, in read
    download_to_file(url=pathname_or_url, filename_or_buffer=fh)
  File "obspy\core\util\base.py", line 601, in download_to_file
    r = requests.get(url, stream=True)
  File "C:\Miniconda-x64\envs\test\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Miniconda-x64\envs\test\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Miniconda-x64\envs\test\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Miniconda-x64\envs\test\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Miniconda-x64\envs\test\lib\site-packages\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

CC @barsch

**Comment by barsch** [comment]
ups - will work on it ...

**Comment by barsch** [comment]
fixed - pls reopen if something fails
