### ISSUE TITLE
Obspy incompatible with mayaVi? 

### ISSUE THREAD

**Issue by BenjiDa** [obspy/obspy#1586]
Obspy version: 1.0.2
Python 2.7.12
MacOSX
Obspy, python and mayaVi are installed via anaconda in a virtual environment.

Issue:
mayaVi works fine until I install Obspy, after installation, running mayaVi provides this error:

```
ImportError: Could not import backend for traits
_______________________________________________________________________________
Make sure that you have either the TraitsBackendWx or the TraitsBackendQt
projects installed. If you installed Mayavi with easy_install, try
easy_install <pkg_name>. easy_install Mayavi[app] will also work.

If you performed a source checkout, be sure to run 'python setup.py install'
in Traits, TraitsGUI, and the Traits backend of your choice.

Also make sure that either wxPython or PyQT is installed.
wxPython: http://www.wxpython.org/
PyQT: http://www.riverbankcomputing.co.uk/software/pyqt/intro
```

PyQT is already installed, Installation of wxPython fixes this error but provides another:

```
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.
```

**Comment by QuLogic** [comment]
What versions of stuff do you have installed (`conda list`)? It sounds like a packaging bug to me.

**Comment by BenjiDa** [comment]
`conda list` before Obspy is installed: 
```
apptools                  4.2.1                    py27_0  
ca-certificates           2016.9.26                     0    conda-forge
certifi                   2016.9.26                py27_0    conda-forge
freetype                  2.7                           0    conda-forge
libpng                    1.6.26                        0    conda-forge
ncurses                   5.9                           9    conda-forge
openssl                   1.0.2h                        2    conda-forge
pip                       9.0.0                    py27_0    conda-forge
pyqt                      4.11.4                   py27_1    conda-forge
python                    2.7.12                        1    conda-forge
readline                  6.2                           0    conda-forge
setuptools                28.7.1                   py27_0    conda-forge
sip                       4.18                     py27_0    conda-forge
six                       1.10.0                   py27_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
zlib                      1.2.8                         3    conda-forge
configobj                 5.0.6                    py27_0  
envisage                  4.4.0                    py27_1  
mayavi                    4.4.0                np19py27_0  
mkl                       11.3.3                        0  
numpy                     1.9.3                    py27_3  
pyface                    4.4.0                    py27_0  
python.app                1.2                      py27_4  
qt                        4.8.7                         4  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
vtk                       5.10.1                   py27_0 
```

`conda list` after:

```
apptools                  4.2.1                    py27_0  
ca-certificates           2016.9.26                     0    conda-forge
certifi                   2016.9.26                py27_0    conda-forge
decorator                 4.0.10                   py27_0    conda-forge
future                    0.15.2                   py27_0    conda-forge
icu                       56.1                          4    conda-forge
libiconv                  1.14                          3    conda-forge
libxml2                   2.9.4                         3    conda-forge
libxslt                   1.1.29                        1    conda-forge
lxml                      3.6.4                    py27_0    conda-forge
ncurses                   5.9                           9    conda-forge
openssl                   1.0.2h                        2    conda-forge
pip                       9.0.0                    py27_0    conda-forge
pyqt                      4.11.4                   py27_1    conda-forge
python                    2.7.12                        1    conda-forge
python-dateutil           2.5.3                    py27_0    conda-forge
pytz                      2016.7                   py27_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.11.1                   py27_0    conda-forge
setuptools                28.7.1                   py27_0    conda-forge
sip                       4.18                     py27_0    conda-forge
six                       1.10.0                   py27_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
xz                        5.2.2                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
configobj                 5.0.6                    py27_0  
envisage                  4.4.0                    py27_1  
freetype                  2.5.5                         1  
libpng                    1.6.17                        0  
matplotlib                1.4.3                np19py27_3  
mayavi                    4.4.0                np19py27_0  
mkl                       11.3.3                        0  
numpy                     1.9.3                    py27_3  
obspy                     1.0.2                    py27_0    obspy
pyface                    4.4.0                    py27_0  
pyparsing                 2.0.3                    py27_0  
python.app                1.2                      py27_4  
qt                        4.8.7                         4  
scipy                     0.17.1               np19py27_1  
sqlalchemy                1.1.3                    py27_0  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
vtk                       5.10.1                   py27_0 
```

**Comment by QuLogic** [comment]
I can't really check this at the moment, but can you try installing obspy from the conda-forge channel instead?

**Comment by BenjiDa** [comment]
Ok, thanks! I just tried again installing obspy from conda-forge channel, and had the same problem.

**Comment by QuLogic** [comment]
I tried this out, but wasn't able to reproduce; the framework thing indicates it might be a Mac-specific problem.

Also, more than just obspy was installed in that "after" list; maybe try installing those one-by-one to see if it's obspy specifically, or one of its dependencies?

**Comment by megies** [comment]
Maybe updating `conda` (in the root environment) might help if it's packaging related.. just a wild guess.

**Comment by krischer** [comment]
I can reproduce this but its not our fault but rather the matplotlib installation. I'm not entirely sure why though. Steps to reproduces (on OSX):

```bash
$ conda config --add channels conda-forge
$ conda create -n mayavi python=2.7
$ source activate mayavi
$ conda install mayavi

# Mayavi works now!
$ python -c "x = [1, 2, 3, 4, 5, 6]; y = [0, 0, 0, 0, 0, 0]; z = y; s = [.5, .6, .7, .8, .9, 1]; from mayavi import mlab; pts = mlab.points3d(x, y, z, s); mlab.show()"

$ conda install matplotlib

# Mayavi no longer works.
$ python -c "x = [1, 2, 3, 4, 5, 6]; y = [0, 0, 0, 0, 0, 0]; z = y; s = [.5, .6, .7, .8, .9, 1]; from mayavi import mlab; pts = mlab.points3d(x, y, z, s); mlab.show()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lion/.miniconda3/envs/mayavi/lib/python2.7/site-packages/mayavi/tools/helper_functions.py", line 37, in the_function
    return pipeline(*args, **kwargs)
  File "/Users/lion/.miniconda3/envs/mayavi/lib/python2.7/site-packages/mayavi/tools/helper_functions.py", line 77, in __call__
    scene = tools.gcf().scene
  File "/Users/lion/.miniconda3/envs/mayavi/lib/python2.7/site-packages/mayavi/tools/figure.py", line 114, in gcf
    engine = get_engine()
  File "/Users/lion/.miniconda3/envs/mayavi/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 97, in get_engine
    return self.new_engine()
  File "/Users/lion/.miniconda3/envs/mayavi/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 142, in new_engine
    check_backend()
  File "/Users/lion/.miniconda3/envs/mayavi/lib/python2.7/site-packages/mayavi/tools/engine_manager.py", line 49, in check_backend
    ''')
ImportError: Could not import backend for traits
```


`conda-install matplotlib` log:

```bash
$ conda install matplotlib
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/lion/.miniconda3/envs/mayavi:

The following NEW packages will be INSTALLED:

    matplotlib:      1.4.3-np19py27_3
    pyparsing:       2.0.3-py27_0
    python-dateutil: 2.5.3-py27_0     conda-forge
    pytz:            2016.7-py27_0    conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    freetype:        2.7-0            conda-forge --> 2.5.5-1
    libpng:          1.6.26-0         conda-forge --> 1.6.17-0
```

This should probably be taken to the conda-forge repository.

**Comment by krischer** [comment]
Alright - the problem is actually that the default channel mayavi installation has a dependency on a fairly old numpy which in turn install the matplotlib from the default channel. Removing mayavi, installing matplotlib from conda-forge and then using pip to install mayavi does the trick (it might have some dependencies but my system might just have them).

```bash
$ conda uninstall mayavi
$ conda install -c conda-forge matplotlib=1.5.3 
$ pip install mayavi
```

then everything (at least on my system) works fine.

**Comment by ThomasLecocq** [comment]
just to say, `mayavi` and not `mayaVi` :-)

**Comment by BenjiDa** [comment]
First off, thanks for all the fast and insightful comments. 

looks like @krischer is right, 

I ended up installing all mayavi dependencies as shown here under: [ Doing it yourself](http://docs.enthought.com/mayavi/mayavi/installation.html)

Then installing mayavi from the [git repository](https://github.com/enthought/mayavi) **using pip** 

Then installing Obspy as shown [here](https://github.com/obspy/obspy/wiki/Installation-via-Anaconda) although i did use the conda-forge channel,

Now everything seems to be working fine.  Onward to science!

**Comment by krischer** [comment]
Great :-)

**Comment by MMesch** [comment]
I just want to add that you can use ```conda install -c menpo mayavi``` to get new mayavi versions . There seems to be some issue with mayavi + QT4 (works) and QT5 (buggy) sometimes as well.
