### ISSUE TITLE
ImportError: Could not load shared library "libmseed_Linux_64bit_py27.so"

### ISSUE THREAD

**Issue by mschieschke** [obspy/obspy#1721]
Obspy: python-obspy version 1.0.3 
Python 2.7.5
Platform: CentOS Linux release 7.3.1611 (Core) x86_64 with EPEL, freshly installed

Obspy installation:
```
cd /etc/yum.repos.d/
wget https://copr.fedorainfracloud.org/coprs/qulogic/obspy/repo/epel-7/qulogic-obspy-epel-7.repo
yum install python-obspy
```
How to reproduce:
```
$ python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import obspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/obspy/__init__.py", line 182, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/usr/lib64/python2.7/site-packages/obspy/core/util/base.py", line 520, in make_format_plugin_table
    "obspy.plugin.%s.%s" % (group, name), method)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib64/python2.7/site-packages/obspy/io/mseed/core.py", line 23, in <module>
    from . import util, InternalMSEEDReadingError, InternalMSEEDReadingWarning
  File "/usr/lib64/python2.7/site-packages/obspy/io/mseed/util.py", line 24, in <module>
    from .headers import (ENCODINGS, ENDIAN, FIXED_HEADER_ACTIVITY_FLAGS,
  File "/usr/lib64/python2.7/site-packages/obspy/io/mseed/headers.py", line 22, in <module>
    clibmseed = _load_cdll("mseed")
  File "/usr/lib64/python2.7/site-packages/obspy/core/util/libnames.py", line 97, in _load_cdll
    raise ImportError(msg)
ImportError: Could not load shared library "libmseed_Linux_64bit_py27.so".

 /usr/lib64/python2.7/site-packages/obspy/core/util/../../lib/libmseed_Linux_64bit_py27.so: undefined symbol: unpackheaderbyteorder
>>> 
```

Interestingly  **the same issue** can be reproduced on another machine where it previously used to work  
Obspy: python-obspy 0.10.3 
Platform Scientific Linux release 6.5 (Carbon) x86_64:

Obspy installation:
```
cd /etc/yum.repos.d/
wget https://copr.fedorainfracloud.org/coprs/qulogic/obspy/repo/epel-6/qulogic-obspy-epel-6.repo
yum install python-obspy
```

How to reproduce:
```
 python
Python 2.6.6 (r266:84292, Aug 18 2016, 12:06:14) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import obspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/site-packages/obspy/__init__.py", line 47, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/usr/lib64/python2.6/site-packages/obspy/core/util/base.py", line 476, in make_format_plugin_table
    "obspy.plugin.%s.%s" % (group, name), method)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib64/python2.6/site-packages/obspy/mseed/core.py", line 19, in <module>
    from obspy.mseed import util
  File "/usr/lib64/python2.6/site-packages/obspy/mseed/util.py", line 23, in <module>
    from obspy.mseed.headers import (ENCODINGS, ENDIAN,
  File "/usr/lib64/python2.6/site-packages/obspy/mseed/headers.py", line 22, in <module>
    clibmseed = _load_CDLL("mseed")
  File "/usr/lib64/python2.6/site-packages/obspy/core/util/libnames.py", line 97, in _load_CDLL
    raise ImportError(msg)
ImportError: Could not load shared library "libmseed_Linux_64bit_py26.so".

 /usr/lib64/python2.6/site-packages/obspy/core/util/../../lib/libmseed_Linux_64bit_py26.so: undefined symbol: unpackheaderbyteorder
```

On this SL6 machine obspy worked some weeks ago, and the package not been updated since. Is there  something wrong with my installation? Maybe some recent security update in SL6 _and_ Centos7  broke it ?

Best Regards

**Comment by megies** [comment]
ping @QuLogic

**Comment by QuLogic** [comment]
This is my fault; EL6 cannot be upgraded past 0.10.3 due to missing dependencies. It should not have received the libmseed upgrade since that breaks older obspy. I think I will have to break out EL6 into a separate repo that no longer receives updates.

The problem with EL7 is a bit weird; it _did_ receive the latest obspy and the latest libmseed, so it should be working. I will have to check it when I have access to my build.

**Comment by QuLogic** [comment]
Actually, I'm going to take back part of that. EL6 should be fixed now; I've removed the extraneous libmseed build, and you will have to downgrade back to the old version (2.17).

But EL7 _and_ Fedora are broken with the latest libmseed. It looks like `unpackheaderbyteorder` is missing from the linker map. A new build should be on the way shortly and I'll send the patch upstream in a bit.

**Comment by QuLogic** [comment]
New patched version of libmseed are available for EL7 + Fedora,so this should be working there. On EL6, I've removed the latest version because it should not be in use. Downgrading to 2.17 should work there.

**Comment by mschieschke** [comment]
Can comfirm that a downgrade of libmseed to 2.17 works in EL6.  I needed lock the version of libmseed to 2.17  though to pervent getting 2.19 again with the next "yum update". Maybe 2.19 should be removed from the EL6 repository for now?  
Did not get the update in EL7 yet, will report back.  Thanks for the quick help!

**Comment by QuLogic** [comment]
It should be gone already. I just tried this out in mock (which would be completely fresh) and the latest libmseed is 2.17 on EL6. You probably just need to clear a cache (which would also work to get it to refresh the updates on EL7 too, probably)

**Comment by chad-iris** [comment]
Merged PR from @QuLogic and cut new libmseed release: https://github.com/iris-edu/libmseed/releases/tag/v2.19.3

The effort to limit the functionality exported by libmseed to avoid folks using internal routines was a bit overzealous.  Hopefully addressed now.
