### ISSUE TITLE
SEGY trace header attribute error

### ISSUE THREAD

**Issue by s-harder** [obspy/obspy#1823]
I get the following attribute error whenever I try to read segy trace header attributes after I have written them.  The following is the output and errors generated.

66 1001 1
66 1001 2
66 1001 3
3 Trace(s) in Stream:
Seq. No. in line:    1 | 2016-07-16T00:37:00.020000Z - 2016-07-16T00:39:00.020000Z | 250.0 Hz, 30001 samples
Seq. No. in line:    2 | 2016-07-16T00:37:00.020000Z - 2016-07-16T00:39:00.020000Z | 250.0 Hz, 30001 samples
Seq. No. in line:    3 | 2016-07-16T00:37:00.020000Z - 2016-07-16T00:39:00.020000Z | 250.0 Hz, 30001 samples
0.004
Traceback (most recent call last):
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/core/util/attribdict.py", line 123, in __getattr__
    return self.__getitem__(name, default)
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/core/util/attribdict.py", line 72, in __getitem__
    return self.__dict__[name]
KeyError: 'segy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stevenharder/Dropbox/Alex/data/mseed2segy.py", line 50, in <module>
    print (st2[0].stats.segy.trace_header.uphole_time_at_group_in_ms)
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/core/util/attribdict.py", line 125, in __getattr__
    raise AttributeError(e.args[0])
AttributeError: segy

The code that generates this error is below.

        st.trim(dt, dt + 120)
        if not len(st) == 0:
            tr = st[0]
            i = i + 1
            seistr = st[0].data
            sst = Stream(traces=Trace(data=np.require(seistr, dtype="float32"),
                                      header={'delta': tr.stats.delta,'starttime': tr.stats.starttime}))
                                      
            # Create SEGY Trace header to write SEGY specific header values.
            sst[0].stats.segy = AttribDict()
            sst[0].stats.segy.trace_header = AttribDict()
            sst[0].stats.segy.trace_header.uphole_time_at_group_in_ms = 66
            sst[0].stats.segy.trace_header.geophone_group_number_of_trace_number_one = tr.stats.station
            sst[0].stats.segy.trace_header.trace_sequence_number_within_line = i

            # Add trace to stream
            stream.append(sst[0])
            print (sst[0].stats.segy.trace_header.uphole_time_at_group_in_ms, sst[0].stats.segy.trace_header.geophone_group_number_of_trace_number_one, sst[0].stats.segy.trace_header.trace_sequence_number_within_line)

#print "Stream object before writing..."
print (stream)

stream.write("TEST.su", format="SU")

st2 = read("TEST.su")
print (st2[0].stats.delta)
print (st2[0].stats.segy.trace_header.uphole_time_at_group_in_ms)

I'm attempting to run this on ObsPy 1.0.3, on OSX Sierra, with an Anaconda install.

**Comment by krischer** [comment]
Hmm - I cannot see any obvious issue with your code at first glance. Can you provide an (as minimial as possible) example we can run to narrow down the issue?

**Comment by QuLogic** [comment]
You're saving in SU format and then trying to read SEGY attributes from it?

**Comment by s-harder** [comment]
SU and SEGY trace headers are identical.  I need to load more than the bare minimum parameters (delta, npts, and start time) in the trace headers. Below is the first portion of the code that reads mseed data.

import io
from obspy.core import read, UTCDateTime, AttribDict, Stream, Trace
import obspy.io.segy
from obspy.io.segy.core import SEGYTraceHeader, SUFile, TRACE_HEADER_FORMAT
import numpy as np
import sys

stream = Stream()
i = 0
reclen = 512
chunksize = 100000 * reclen # Around 50 MB
dt = UTCDateTime("2016-07-16T00:37:00.020")

with io.open("./1001.YW.mseed", "rb") as fh:
    while True:
        with io.BytesIO() as buf:
            c = fh.read(chunksize)
            if not c:
                break
            buf.write(c)
            buf.seek(0, 0)
            st = read(buf)
    
        # Cut out 2 minute section and output to SU.
        st.trim(dt, dt + 120)

**Comment by krischer** [comment]
> SU and SEGY trace headers are identical. I need to load more than the bare minimum parameters (delta, npts, and start time) in the trace headers. Below is the first portion of the code that reads mseed data.

Yes the headers are identical and internally ObsPy of course uses the same code to read these but regarding the high-level `obspy.read()` and `Stream.write()` functions these are still treated as two distinct file formats. So `Stream.write(format="su")` will only honor `Trace.stats.su` headers; `Stream.write(format="segy")` will honor `Trace.stats.segy` headers. The same are filled when reading the files. So in your example script you'll have to either write as SEG-Y or change all the `.segy` to `.su`.
