### ISSUE TITLE
obspy import in python 2.7 fails with new version of matplot lib

### ISSUE THREAD

**Issue by magixsno** [obspy/obspy#1827]
**Issue**

Using a newer version of matplotlib caused import to fail for obspy. I have matplotlib version 2.0.2 installed and saw the requirements fail on import for obspy. I downgraded to matplotlib version 1.5.3, and still had the issue. I downgraded again to matplotlib version 1.4.3 and import behaved as desired.

**Stack Trace**
```
Traceback (most recent call last):
  File "directory/my_code.py", line 11, in <module>
    import obspy
  File "/Library/Python/2.7/site-packages/obspy/__init__.py", line 182, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/Library/Python/2.7/site-packages/obspy/core/util/base.py", line 520, in make_format_plugin_table
    "obspy.plugin.%s.%s" % (group, name), method)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2369, in load
    self.require(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2386, in require
    items = working_set.resolve(reqs, env, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (matplotlib 1.4.x (/Library/Python/2.7/site-packages), Requirement.parse('matplotlib>=1.1.0'))
```

**Details**
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)

ObsPy 1.0.3
Python: 2.7
Mac OSX 10.12.5

  -  How did you install ObsPy and Python (pip, anaconda, from source ...)

pip 

  -  If possible please supply a short, self contained, correct example that
     demonstrates the issue.

Recreation steps:

pip install --upgrade matplotlib
python
import obspy

  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.

Unsure. Installed today.

**Comment by krischer** [comment]
Hmm - seems to be some kind of issue with `pkg_resources` which ships as part of `setuptools`. ObsPy only requires a ` matplotlib` >= 1.1.0 which all of these clearly are. You could update `setuptools` which I imaging would fix the issue but as you are using OSX's system Python I would advise against it - one never knows what happens when tampering with system installations.

I'd strongly recommend installing ObsPy via `conda` (https://github.com/obspy/obspy/wiki/Installation-via-Anaconda) - this works really well on OSX, can just be installed in the home folder, and is completely isolated from the system Python installation. If that is not an option, try to update `setuptools`. Please report back if it works/does not work.

**Comment by megies** [comment]
👍  for using a local Anaconda

**Comment by megies** [comment]
No further action in this ticket, so closing. Feel free to reopen if problems persist.
