### ISSUE TITLE
xcorr_pick_correction: Inconsistant shape

### ISSUE THREAD

**Issue by bvicic** [obspy/obspy#1831]
Dear all!

I am using latest Obspy version installed via Anaconda on Ubuntu 17.04.

I am trying to xcorr around real P arrival time and arrival time on synthetic signal. 

basically I have:

```
> 1 Trace(s) in Stream:
> SL.KNDS..HHZ | 2014-04-22T08:58:26.871700Z - 2014-04-22T09:00:03.871700Z | 5.0 Hz, 486 samples
> 1 Trace(s) in Stream:
> SL.KNDS..HHZ | 1969-12-31T23:59:33.800000Z - 1970-01-01T00:01:10.800000Z | 5.0 Hz, 486 samples
```

and I try to correlate them with 

```
> dt, coeff = xcorr_pick_correction(CEY_ts_r, streal[0], CEY_ts_s, stsynth[0], 0.05, 0.5, 0.1, plot=True)
```
Well, I am getting this error:
```
> Traceback (most recent call last):
>   File "compare.py", line 89, in <module>
>     dt, coeff = xcorr_pick_correction(KNDS_ts_r, streal[0], KNDS_ts_s, stsynth[0], 0.05, 0.5, 0.1, plot=True)
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/obspy/signal/cross_correlation.py", line 334, in xcorr_pick_correction
>     cc_convex = np.ma.masked_where(np.sign(cc_curvature) >= 0, cc)
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/numpy/ma/core.py", line 1869, in masked_where
>     " (got %s and %s)" % (cshape, ashape))
> IndexError: Inconsistant shape between the condition and the input (got (2,) and (1,))
```

the code looks like that:
```
from obspy import read, read_inventory, Stream, UTCDateTime
from obspy.signal.cross_correlation import xcorr_pick_correction
import os

real_list = os.listdir("../miniseeds/")
synth_list = os.listdir("dc_vel/")

# P arrival
KNDS_ts_r = UTCDateTime(2014,4,22,8,58,31.873)
KNDS_ts_s = UTCDateTime(1970,1,1,0,0,2.022)

for real in real_list:
	str_all = read("../miniseeds/"+str(real))
	if str_all[0].stats.channel == "HHZ":

		staname = str_all[0].stats.station

		if staname =="KNDS":
			streal = str_all.copy()
			streal.merge()
			streal = streal.slice(starttime=KNDS_ts_r-5, endtime=KNDS_ts_r+92)
			streal = streal.filter('lowpass', freq=5.0)
			streal = streal.decimate(factor=10, strict_length=False)
			streal = streal.decimate(factor=4, strict_length=False)
		else:
			pass

		print(streal)
		
		stsynth = read("dc_vel/"+str(staname)+"-vel.mseed")
		stsynth = stsynth.select(channel="Z")
		for tr in stsynth:
			if not tr.stats.channel == "HHZ":
				tr.stats.channel = "HHZ" 

		print(stsynth)

		if staname =="KNDS":
			dt, coeff = xcorr_pick_correction(KNDS_ts_r, streal[0], KNDS_ts_s, stsynth[0], 0.05, 0.5, 0.1, plot=True)
		else:
			pass

		print("*******")
```

Thank you very much,
Blaž

**Comment by trichter** [comment]
Hi,

it seems that your data only consists of 1 or very few data points?

**Comment by megies** [comment]
In cases like these, there's no way around using a debugger to see what is really going on (or rather going wrong) during execution. We could also just do the same..

https://pymotw.com/2/pdb/index.html

For a bit more comfort, I'd recommend [pdb++](https://pypi.python.org/pypi/pdbpp/).

**Comment by d-chambers** [comment]
should we close this due to lack of activity?

**Comment by megies** [comment]
Yep, I agree. No feedback and no self-contained example.
