### ISSUE TITLE
Infinite recursion while using apache_beam (in session serialization)

### ISSUE THREAD

**Issue by hjfreyer** [obspy/obspy#1894]
On OS X:

    virtualenv /tmp/repro
    source /tmp/repro/bin/activate
    pip install numpy
    pip install obspy
    pip install dill  # Used by apache_beam
    
    echo 'import obspy; import dill; dill.dump_session("/tmp/dump"); dill.load_session("/tmp/dump")' | python

Gives the following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/repro/lib/python2.7/site-packages/dill/dill.py", line 385, in load_session
    module = unpickler.load()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1221, in load_build
    setstate = getattr(inst, "__setstate__", None)
  File "/tmp/repro/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py", line 50, in __getattr__
    if self.__function_map and name in self.__function_map:
  File "/tmp/repro/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py", line 50, in __getattr__
    if self.__function_map and name in self.__function_map:
  File "/tmp/repro/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py", line 50, in __getattr__
    if self.__function_map and name in self.__function_map:
<snip>
  File "/tmp/repro/lib/python2.7/site-packages/obspy/core/util/deprecation_helpers.py", line 50, in __getattr__
    if self.__function_map and name in self.__function_map:
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

This gets called as part of the apache_beam start-up process, using the DataflowRunner (for Google Cloud). I'd love to use obspy as part of a pipeline, so it'd be nice if this worked :)

**Comment by krischer** [comment]
This particular functionality no longer exists in the `master` branch. So if you just update it might already work.

**Comment by krischer** [comment]
I just tried on the latest master and I get this error message:

I'd be happy to help along to resolve this but I'm not sure what the cause of this is - we don't use zipimport.

```python
...
    StockPickler.save_dict(pickler, obj)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/dill/dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/dill/dill.py", line 871, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle zipimport.zipimporter objects
```

**Comment by krischer** [comment]
A bit more digging with the debugger yields this call in `dill` which fails:

```python
[64] > /Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/dill/dill.py(871)save_module_dict()
-> StockPickler.save_dict(pickler, obj)
(Pdb++) pp obj
{'_dirindex': {'': ['cycler.py', '__pycache__', 'EGG-INFO'],
               'EGG-INFO': ['dependency_links.txt',
                            'PKG-INFO',
                            'requires.txt',
                            'SOURCES.txt',
                            'top_level.txt',
                            'zip-safe'],
               '__pycache__': ['cycler.cpython-36.pyc']},
 'egg_info': '/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg/EGG-INFO',
 'egg_name': 'cycler-0.10.0-py3.6.egg',
 'egg_root': '/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg',
 'loader': <zipimporter object "/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg">,
 'module_path': '/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg',
 'zip_pre': '/Users/lion/.miniconda/envs/obspy_py36/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg/'}
```

Just importing `cycler` or `matplotlib` (or any of our other dependencies...) does not trigger this warning so.

**Comment by hjfreyer** [comment]
Yeah, as of HEAD the issue has changed, but it still doesn't work on Cloud Dataflow. Something in the code which collects all the dependent modules misses obspy, so on the worker machine you get:

```

(bc10cabf81e243b9): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 706, in run
    self._load_main_session(self.local_staging_directory)
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 446, in _load_main_session
    pickler.load_session(session_file)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 247, in load_session
    return dill.load_session(file_path)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 363, in load_session
    module = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 766, in _import_module
    return __import__(import_name)
ImportError: No module named obspy
```

**Comment by megies** [comment]
stale, closing.
