### ISSUE TITLE
error import obspy 

### ISSUE THREAD

**Issue by gposada** [obspy/obspy#2017]
Hello,

I have a problem to import obspy. I have always worked with ObsPy and is the first time that I see this error :

```pytb
import obspy
Traceback (most recent call last):

  File "<ipython-input-2-6960ca51d676>", line 1, in <module>
    import obspy

  File "/home/gustavo/.local/lib/python2.7/site-packages/obspy/__init__.py", line 59, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)

  File "/home/gustavo/.local/lib/python2.7/site-packages/obspy/core/util/base.py", line 474, in make_format_plugin_table
    func = buffered_load_entry_point(*ep_list)

  File "/home/gustavo/.local/lib/python2.7/site-packages/obspy/core/util/misc.py", line 638, in buffered_load_entry_point
    _ENTRY_POINT_CACHE[hash_str] = load_entry_point(dist, group, name)

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)

  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)

ContextualVersionConflict: (chardet 2.3.0 (/usr/lib/python2.7/dist-packages), Requirement.parse('chardet<3.1.0,>=3.0.2'), set(['requests']))
```

Which is the problem?

**Comment by krischer** [comment]
Seems to be some kind of dependency fight. Can you try to update `chardet`? Or just install the obspy dep package? Or use conda? One of these should work.

**Comment by gposada** [comment]
Ok, I will use conda, I can't update the chardet packages and I think that have problems with some repositories. 

Thanks!

**Comment by megies** [comment]
Like @krischer mentioned, if you're not picky with dependency versions and since you at least partially rely on the system Python, you could use our Debian/Ubuntu `apt` repository. See wiki under installation via apt.
