### ISSUE TITLE
NRL KeyError

### ISSUE THREAD

**Issue by rantanplan77** [obspy/obspy#2018]
Hi all,

I am trying to download responses from the NRL. First, I start with a Taurus and look up the keys using nrl.dataloggers:
```
from obspy.clients.nrl import NRL
nrl = NRL()
nrl.dataloggers["Nanometrics"]["Taurus"]["16 Vpp (1)"]["Low (default)"]["Off"]["500"]

('Taurus, 16 vpp (gain 1), 500 sps, low impedance, DC removal filter off',
 'http://ds.iris.edu/NRL/dataloggers/nanometrics/taurus/RESP.XX.NN287..HHZ.TAURUS.1.500.LO.OFF')
```
then I load the response, which works fine:
```
resp = nrl.get_response(sensor_keys=['Lennartz','LE-3Dlite Classic'], datalogger_keys=["Nanometrics","Taurus","16 Vpp (1)","Low (default)","Off","500"])
```
Now I try the same with a Centaur, note how it fails to fetch the response even though I use the exact same keys:
```
nrl.dataloggers["Nanometrics"]["Centaur"]["40 Vpp (1)"]["Off"]["500"]

('Centaur, 40 vpp (gain 1), 500 sps, DC removal filter off',
 'http://ds.iris.edu/NRL/dataloggers/nanometrics/centaur/RESP.XX.NN453..HHZ.CENTAUR.1.500.OFF')

resp = nrl.get_response(sensor_keys=['Lennartz','LE-3Dlite Classic'], datalogger_keys=nrl.dataloggers["Nanometrics","Centaur","40 Vpp (1)","Off","500"])
Traceback (most recent call last):

  File "<ipython-input-64-ee129ebd7bae>", line 1, in <module>
    resp = nrl.get_response(sensor_keys=['Lennartz','LE-3Dlite Classic'], datalogger_keys=nrl.dataloggers["Nanometrics","Centaur","40 Vpp (1)","Off","500"])

  File "/Users/luckyluke/Documents/Python/miniconda3/envs/py36/lib/python3.6/site-packages/obspy/clients/nrl/client.py", line 250, in __getitem__
    value = super(NRLDict, self).__getitem__(name)

KeyError: ('Nanometrics', 'Centaur', '40 Vpp (1)', 'Off', '500')
```

Is there a reason why get_response uses different keys than nrl.dataloggers? And how do I find out the right ones to use for get_response?

obspy 1.1.0
python 3.6.2 via anaconda

**Comment by rantanplan77** [comment]
While checking the keys 100 times I ignored that I still had an uncessary nrl.dataloggers before it. 🙈
