### ISSUE TITLE
[MassDownloader] Exits abruptly on connection reset

### ISSUE THREAD

**Issue by paride** [obspy/obspy#2029]
When a connection fails, the mass downloader exits throwing an error, interrupting the ongoing download (which is done using several connections and others may succeed) and the script it was called from, which may contain other steps after the `md.download()` call. I think that, in case of a failed/reset connection, the mass downloader should retry for a few times and then give up gracefully. The full stack trace follows. I'm using the git head version on Python 3.6.3.

```
Traceback (most recent call last):
  File "./10_downloader.py", line 130, in <module>
    stationxml_storage=stationxml_storage)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/mass_downloader.py", line 201, in download
    threads_per_client=threads_per_client)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/download_helpers.py", line 857, in download_mseed
    [(self.client, self.client_name, chunk) for chunk in chunks])
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/download_helpers.py", line 842, in star_download_mseed
    *args, logger=self.logger)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/utils.py", line 228, in download_and_split_mseed_bulk
    client.get_waveforms_bulk(bulk, filename=temp_filename)
  File "/home/legovini/obspy/obspy/clients/fdsn/client.py", line 1009, in get_waveforms_bulk
    data=bulk)
  File "/home/legovini/obspy/obspy/clients/fdsn/client.py", line 1381, in _download
    timeout=self.timeout, use_gzip=use_gzip)
  File "/home/legovini/obspy/obspy/clients/fdsn/client.py", line 1798, in download_url
    data = io.BytesIO(f.read())
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/http/client.py", line 456, in read
    return self._readall_chunked()
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/http/client.py", line 566, in _readall_chunked
    value.append(self._safe_read(chunk_left))
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/http/client.py", line 612, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by krischer** [comment]
This should also be fixed by #2081. Can you check and close this issue if its the case?

It would not retry any failed downloads but the mass downloader has been designed to be restart-able so just running it again after it has been completed should grab any previously missing data.

**Comment by paride** [comment]
@krischer @megies I'm sorry for not following up: this slipped under my radar. I can't reproduce the issue with the latest git version. If you agree I'll close this report.

**Comment by megies** [comment]
Yeah, if it can not be reproduced on current maintenance branch, then we can close it. Feel free to reopen should you come across this again.
