### ISSUE TITLE
[MassDownloader] NotImplementedError (starttime > first["endtime"] or ...)

### ISSUE THREAD

**Issue by paride** [obspy/obspy#2030]
Here is another error I've got when using the mass downloader:

```
Traceback (most recent call last):
  File "./10_downloader.py", line 122, in <module>
    stationxml_storage=stationxml_storage)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/mass_downloader.py", line 201, in download
    threads_per_client=threads_per_client)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/download_helpers.py", line 857, in download_mseed
    [(self.client, self.client_name, chunk) for chunk in chunks])
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/download_helpers.py", line 842, in star_download_mseed
    *args, logger=self.logger)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/utils.py", line 245, in download_and_split_mseed_bulk
    c=filenames[channel_id])
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/utils.py", line 143, in get_filename
    raise NotImplementedError
NotImplementedError
```

I took a look at utils.py:143, the failing condition is:
```
# Make sure the assumptions about the type of overlap are correct.
if starttime > first["endtime"] or endtime < second["starttime"]:
    raise NotImplementedError
```

Couldn't be this just due to a corrupted file in the datacenter? Should ObsPy handle this situation more gracefully? I could try to make this reproducible, if you're interested in looking into it.

**Comment by krischer** [comment]
Can you post a minimal example reproducing this? I don't see right now how this can happen so I guess its some corrupt file? But would be nice to look at it.

**Comment by ThomasLecocq** [comment]
could it be an un-sorted mseed file ?

**Comment by paride** [comment]
@krischer Unfortunately now I forgot which station and data interval was causing this error. The next time I encounter the issue I'll try to isolate what is causing the problem and let you have a minimal example.

**Comment by krischer** [comment]
> could it be an un-sorted mseed file ?

I don't think so because the records are sorted by time right before this line is called.



> @krischer Unfortunately now I forgot which station and data interval was causing this error. The next time I encounter the issue I'll try to isolate what is causing the problem and let you have a minimal example.

Please do - I don't really understand how this can happen so I would need to be able to reproduce it to fix it. 

I'll remove this issue from the milestone until we have a reproducible example.

**Comment by paride** [comment]
Cc: @petrrr 

OK, I'm back with an example to reproduce the issue. The following script is supposed to download everything available between 1985 and 1999 for a station named `TNV` that lies below -59S. By "everything" I mean the data for all the networks, channels, locations for `TNV` within the defined `RectangularDomain`. I don't care if there are gaps or other issues with the data, I want to retrieve *everything*.

The process is split in yearly requests (the `for` loop) because sometimes data centers do not like extremely large requests (this is probably not the case, but I've made bigger ones). Suggestions on doing this in a better way are of course welcome. 

```
#!/usr/bin/env python3

import obspy
from obspy.clients.fdsn import mass_downloader as MD

domain = MD.RectangularDomain(minlatitude=-90, maxlatitude=-59, minlongitude=-180, maxlongitude=180)

restrictions = MD.Restrictions(
        # Get data for a whole year
        starttime=obspy.UTCDateTime(1985, 1, 1),
        endtime=obspy.UTCDateTime(1999, 12, 31),

        # We want daily chunks
        chunklength_in_sec=86400,

        station="TNV",
        channel_priorities=["*"],
        location_priorities=["*"],

        reject_channels_with_gaps=False,
        minimum_length=0.0,
        minimum_interstation_distance_in_m=0.0
)

mdl = MD.MassDownloader(providers=['IRIS'])

# Years to download (inclusive)
first_year = 1985
last_year  = 1999

for y in range(first_year, last_year+1):
    print("### YEAR: " + str(y))
    restrictions.starttime=obspy.UTCDateTime(y, 1, 1)
    restrictions.endtime=obspy.UTCDateTime(y, 12, 31)

    mdl.download(domain, restrictions, download_chunk_size_in_mb=50,
            threads_per_client=3, mseed_storage="waveforms/" + str(y),
            stationxml_storage="stations/" + str(y))
    print("### END YEAR: " + str(y))
```

This script systematically fails in this way:
```
[2018-06-16 16:50:46,906] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - No data available for request.
[2018-06-16 16:50:47,382] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - No data available for request.
Traceback (most recent call last):
  File "./10_downloader.py", line 42, in <module>
    stationxml_storage="stations/" + str(y))
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/mass_downloader.py", line 201, in download
    threads_per_client=threads_per_client)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/download_helpers.py", line 857, in download_mseed
    [(self.client, self.client_name, chunk) for chunk in chunks])
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/legovini/miniconda3/envs/sismo/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/download_helpers.py", line 842, in star_download_mseed
    *args, logger=self.logger)
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/utils.py", line 245, in download_and_split_mseed_bulk
    c=filenames[channel_id])
  File "/home/legovini/obspy/obspy/clients/fdsn/mass_downloader/utils.py", line 143, in get_filename
    raise NotImplementedError
NotImplementedError
```

I did this using the tip of ObsPy's master branch, currently 06906f389bdaeb5fa4c4bd0cab9f066082e7da42. I hope this helps!

**Comment by paride** [comment]
I stripped down the example, this won't require you to download >2GB of data to reproduce the issue:
```
#!/usr/bin/env python3

import obspy
from obspy.clients.fdsn import mass_downloader as MD

domain = MD.RectangularDomain(minlatitude=-90, maxlatitude=-59, minlongitude=-180, maxlongitude=180)

restrictions = MD.Restrictions(
    # Get data for a whole year
    starttime=obspy.UTCDateTime(1991, 2, 21, 0, 0),
    endtime=obspy.UTCDateTime(1991, 2, 23, 0, 0),

    # We want daily chunks
    chunklength_in_sec=86400,

    station="TNV",
    channel="VHZ",
)

mdl = MD.MassDownloader(providers=['IRIS'])

mdl.download(domain, restrictions, mseed_storage="waveforms/", stationxml_storage="stations/")
```
I can systematically reproduce the issue, just remember to delete the `waveforms/` directory between tries (if you change `starttime` or `endtime`). I added a `print(candicates)` at `utils.py:157`:
```
# Make sure the assumptions about the type of overlap are correct.
if starttime > first["endtime"] or endtime < second["starttime"]:
    print(candidates)
    raise NotImplementedError
```
The result is:
```
[...]
[2018-06-17 18:02:32,835] - obspy.clients.fdsn.mass_downloader - INFO: Client 'IRIS' - Status for 2 time intervals/channels before downloading: NEEDS_DOWNLOADING
[{'starttime': UTCDateTime(1991, 2, 21, 0, 0), 'endtime': UTCDateTime(1991, 2, 22, 0, 0), 'filename': 'waveforms/MN.TNV..VHZ__19910221T000000Z__19910222T000000Z.mseed', 'curr
ent_latest_endtime': UTCDateTime(1991, 2, 21, 21, 13, 50, 430000), 'sequence_number': 5}, {'starttime': UTCDateTime(1991, 2, 22, 0, 0), 'endtime': UTCDateTime(1991, 2, 23, 0,
 0), 'filename': 'waveforms/MN.TNV..VHZ__19910222T000000Z__19910223T000000Z.mseed', 'current_latest_endtime': None, 'sequence_number': None}]
Traceback (most recent call last):
[...]
```

**Comment by paride** [comment]
This is probably important: if I comment out the `chunklength_in_sec=86400` line the script works fine.

**Comment by krischer** [comment]
Dealt with in #2191. It was an issue with one of the internal functions used to split up the miniSEED files after downloading.

Thanks a lot for the easy to reproduce failure! I'm not sure I would have been able to find it otherwise. I think this should work now.
