### ISSUE TITLE
Exception occurring suring reading a Reftek130 file

### ISSUE THREAD

**Issue by tafro** [obspy/obspy#2036]
I got following exception while trying to read the Reftek130 raw file (
[112828970_0036EE80.zip](https://github.com/obspy/obspy/files/1611645/112828970_0036EE80.zip)
)

```
from obspy import read
read('112828970_0036EE80',dtype='float32')`

```

```
/opt/obspy/src/obspy/obspy/io/reftek/core.py:157: UserWarning: Detected permuted packet sequence, sorting.
  warnings.warn(msg)
/opt/obspy/src/obspy/obspy/io/reftek/core.py:322: UserWarning: No channel code specified in the data file and no component codes specified. Using stream label and number of channel in file as channel codes.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/opt/obspy/src/obspy/obspy/io/reftek/core.py", line 333, in to_stream
    t_last + (npts_last - 1) * delta)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./ref2segy.py", line 130, in <module>
    stadd=read(file,dtype='float32')
  File "<decorator-gen-31>", line 2, in read
  File "/opt/obspy/src/obspy/obspy/core/util/decorator.py", line 299, in _map_example_filename
    return func(*args, **kwargs)
  File "/opt/obspy/src/obspy/obspy/core/stream.py", line 231, in read
    st.extend(_read(file, format, headonly, **kwargs).traces)
  File "<decorator-gen-32>", line 2, in _read
  File "/opt/obspy/src/obspy/obspy/core/util/decorator.py", line 209, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/opt/obspy/src/obspy/obspy/core/stream.py", line 273, in _read
    headonly=headonly, **kwargs)
  File "/opt/obspy/src/obspy/obspy/core/util/base.py", line 410, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/opt/obspy/src/obspy/obspy/io/reftek/core.py", line 102, in _read_reftek130
    verbose=verbose)
  File "/opt/obspy/src/obspy/obspy/io/reftek/core.py", line 342, in to_stream
    raise Reftek130Exception(msg)
obspy.io.reftek.core.Reftek130Exception: Reftek file has a trace with an inconsistent endtime or number of samples. Please open an issue on GitHub and provide your file fortesting.


```

**Comment by megies** [comment]
It seems we're running into floating point accuracy issues here, similar to descriptions in #2034..

**Comment by megies** [comment]
@tafro, see #2038 which should fix the issue.

**Comment by tafro** [comment]
Works. Thanks a lot.

**Comment by megies** [comment]
Merged into maintenance branch.
