### ISSUE TITLE
KeyError: 'station' using RoutingClient

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#2134]
I wanted to create a plot of all available permanent stations.

What would be the best way to do it?

On my way I stumbled upon the following Exception.

Code:
```
from obspy.clients.fdsn import RoutingClient
from obspy import UTCDateTime as UTC

client = RoutingClient('iris-federator', debug=True)
inv1 = client.get_stations(
        starttime=UTC('2018-01-01'),
        endtime=UTC('2018-02-01'),
        level='station')
inv1.write('station.txt', 'STATIONTXT', level='station')
```

Tail of the output:

```
Error while downloading: http://eida-service.koeri.boun.edu.tr/fdsnws/dataselect/1/application.wadl
Error while downloading: http://eida-service.koeri.boun.edu.tr/fdsnws/event/1/application.wadl
Error while downloading: http://eida-service.koeri.boun.edu.tr/fdsnws/station/1/application.wadl
Error while downloading: http://eida-service.koeri.boun.edu.tr/fdsnws/event/1/contributors
Error while downloading: http://eida-service.koeri.boun.edu.tr/fdsnws/event/1/catalogs
/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py:103: UserWarning: No FDSN services could be discovered at 'http://eida-service.koeri.boun.edu.tr'. This could be due to a temporary service outage or an invalid FDSN service address.It will not be used for routing. Try again later?
  warnings.warn(msg)
Downloaded http://ws.resif.fr/fdsnws/station/1/query with HTTP code: 200
Error while downloading: http://service.scedc.caltech.edu/fdsnws/dataselect/1/application.wadl
Error while downloading: http://service.scedc.caltech.edu/fdsnws/event/1/catalogs
Error while downloading: http://service.scedc.caltech.edu/fdsnws/event/1/contributors
Error while downloading: http://service.scedc.caltech.edu/fdsnws/station/1/application.wadl
Discovered event service
Storing discovered services in cache.
Uncompressing gzipped response for http://service.iris.edu/fdsnws/station/1/query
Downloaded http://service.iris.edu/fdsnws/station/1/query with HTTP code: 200
Uncompressing gzipped response for http://webservices.ingv.it/fdsnws/station/1/query
Downloaded http://webservices.ingv.it/fdsnws/station/1/query with HTTP code: 200
HTTP error 504, reason Gateway Time-out, while downloading 'http://geofon.gfz-potsdam.de/fdsnws/station/1/query': b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor="white">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.12.2</center>\r\n</body>\r\n</html>\r\n'
Error while downloading: http://service.ncedc.org/fdsnws/station/1/query
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    inv1 = get_stations()
  File "test.py", line 12, in get_stations
    level='station')
  File "<decorator-gen-61>", line 2, in get_stations
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py", line 79, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/federator_routing_client.py", line 110, in get_stations
    return super(FederatorRoutingClient, self).get_stations(**kwargs)
  File "<decorator-gen-58>", line 2, in get_stations
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py", line 79, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py", line 344, in get_stations
    return self.get_stations_bulk([bulk], **kwargs)
  File "<decorator-gen-62>", line 2, in get_stations_bulk
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py", line 79, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/federator_routing_client.py", line 147, in get_stations_bulk
    return self._download_stations(split, **kwargs)
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py", line 228, in _download_stations
    return self._download_parallel(split, data_type="station", **kwargs)
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py", line 254, in _download_parallel
    results = pool.map(_download_bulk, dl_requests)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/eule/anaconda/envs/workhorse/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/eule/dev/obspy/obspy/clients/fdsn/routing/routing_client.py", line 115, in _download_bulk
    service = c.services["station"]
KeyError: 'station'
```

**Comment by krischer** [comment]
I could not reproduce this particular error but it should now be handled in a nicer fashion in #2138 and execution now continues when an fdsn endpoint acts up in an unexpected fashion.

I also see the timeout from the GFZ which is a bit more troubling as it means that you will not get data from it. Fixing this would require server side changes - as a workaround you could try to loop over all letters in the alphabet and only request networks starting with that letter each loop iteration. This should make the single requests smaller and maybe more of them succeed?
