### ISSUE TITLE
FDSN routing client has a locale dependency

### ISSUE THREAD

**Issue by adam-iris** [obspy/obspy#2147]
There's a dummy call to `time.strptime` in the module init that uses locale-specific formatting, which fails under locales that don't use the same names (ie. "Nov" for the 11th month of the year).

```
>>> import locale
>>> locale.setlocale(locale.LC_TIME, ('zh_CN', 'UTF-8'))
'zh_CN.UTF-8'
>>> from obspy.clients.fdsn.routing.routing_client import RoutingClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/anaconda/envs/django/lib/python2.7/site-packages/obspy/clients/fdsn/__init__.py", line 242, in <module>
    from .routing.routing_client import RoutingClient  # NOQA
  File "/workspace/anaconda/envs/django/lib/python2.7/site-packages/obspy/clients/fdsn/routing/__init__.py", line 25, in <module>
    time.strptime("30 Nov 00", "%d %b %y")
  File "/workspace/anaconda/envs/django/lib/python2.7/_strptime.py", line 478, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/workspace/anaconda/envs/django/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data u'30 Nov 00' does not match format u'%d %b %y'
```

I believe switching this to an ISO8601-like string would be locale-agnostic:

    time.strptime("2000/11/30", "%Y/%m/%d")

**Comment by megies** [comment]
Closed by #2148
