### ISSUE TITLE
I can't save a numbers frame in mseed format - Raspberry

### ISSUE THREAD

**Issue by scg94** [obspy/obspy#2398]
Hi, 

I am trying to export an MSEED file from a 100 data array that comes from an accelerometer. At the time I created the file with `stream.write('out.miniseed',format='MSEED', encoding=11)` , I received a couple of errors. My code is this:

```python
import numpy
from obspy.core import Trace,Stream,UTCDateTime, read

ser = serial.Serial('/dev/Acc', 38400, timeout = 0.5) #'/dev/Acc' para Acelero sin 5TE
time.sleep(3)
ser.flushInput()
ser.flushOutput()

data_Acc = ""
flag = 0
datapoints = 100
starttime = UTCDateTime()
gyro = ["" for x in range(100)]
data=numpy.zeros([datapoints],dtype=numpy.int32)
def readData():
    global data_Acc, flag
    trama=ser.readline()
    if trama != "":
        print(trama)
        trama = trama.split("\r\n")
        trama = trama[0].split(":")
        if len(trama)>6:
            flag = 1
            data_Acc = trama
            #print (trama)
        else:
            flag = 0

while 1:

    readData()
    if data_Acc != "":
        if flag == 1:
            for x in range (datapoints):
                readData()
                #sample = int(float(data_Acc[3])*1000)
                data[x]= int(float(data_Acc[3])*1000) #sample
                timenow=UTCDateTime()
                print timenow, data
            starttime = UTCDateTime()
            stats= {'network': 'MPU6050', 'station': '999', 'location': '6.34, -75.34',  
            'channel':'WLZ', 'npts': len(gyro), 
            'sampling_rate': 0.1, 'mseed' : {'dataquality' : 'D'}, 'starttime': starttime}
            stream =Stream([Trace(data=data, header=stats)]) 
            stream.write('out.miniseed',format='MSEED', encoding=11)
            #stream.plot()
```

The issue output is this:

```
Traceback (most recent call last):
File "Acelerometro_V3.py", line 86, in <module>
    stream.write('out.miniseed',format='MSEED', encoding=11)
File "/usr/lib/python2.7/dist-packages/obspy/core/stream.py", line 1443, in write
    write_format(self, filename, **kwargs)
File "/usr/lib/python2.7/dist-packages/obspy/io/mseed/core.py", line 826, in _write_mseed
    mst = MST(trace, data, dataquality=trace_attr['dataquality'])
File "/usr/lib/python2.7/dist-packages/obspy/io/mseed/core.py", line 960, in __init__
    encode('ascii', 'strict')
ValueError: string too long (12, maximum length 11)
```

Can you help me, please?

**Comment by aringler-usgs** [comment]
Hello @scg94, your location should be a location code and not a physical location.  The location codes are two character codes (e.g. 00 or 10).  I also think your network code needs to be two characters and not 7.

Best,
Adam
