### ISSUE TITLE
Triggered warning: The StationXML file has version ...

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#2539]
This warning is now omnipresent not only when running tests, but also when just loading the example stream.

```
In [1]: from obspy import read                                                  
In [2]: read()                                                                  
/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/io/stationxml/core.py:98: UserWarning: The StationXML file has version 1, ObsPy can read versions (1.0, 1.1). Proceed with caution.
  version, ", ".join(READABLE_VERSIONS)))
Out[2]: 
3 Trace(s) in Stream:
BW.RJOB..EHZ | 2009-08-24T00:20:03.000000Z - 2009-08-24T00:20:32.990000Z | 100.0 Hz, 3000 samples
BW.RJOB..EHN | 2009-08-24T00:20:03.000000Z - 2009-08-24T00:20:32.990000Z | 100.0 Hz, 3000 samples
BW.RJOB..EHE | 2009-08-24T00:20:03.000000Z - 2009-08-24T00:20:32.990000Z | 100.0 Hz, 3000 samples
```

**Comment by trichter** [comment]
OK, it is now clear to me why this is even happening when loading the example stream. The example inventory is read for attaching the response.

```
(workhorse) eule@kiste:~$ python -Werror -c "from obspy import read; read()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "</home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/decorator.py:decorator-gen-31>", line 2, in read
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/stream.py", line 210, in read
    st = _create_example_stream(headonly=headonly)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/stream.py", line 302, in _create_example_stream
    inv = read_inventory(os.path.join(data_dir, "BW_RJOB.xml"))
  File "</home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/decorator.py:decorator-gen-49>", line 2, in read_inventory
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/inventory/inventory.py", line 89, in read_inventory
    **kwargs)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/util/base.py", line 701, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "</home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/decorator.py:decorator-gen-50>", line 2, in _read
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/inventory/inventory.py", line 98, in _read
    **kwargs)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/core/util/base.py", line 443, in _read_from_plugin
    is_format = is_format(filename)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.7/site-packages/obspy/io/stationxml/core.py", line 98, in _is_stationxml
    version, ", ".join(READABLE_VERSIONS)))
UserWarning: The StationXML file has version 1, ObsPy can read versions (1.0, 1.1). Proceed with caution.
```

**Comment by megies** [comment]
@trichter should be fixed, let me know if the issue persists or if you see any other warnings that should not be there when using core functionality like the example stream
