### ISSUE TITLE
UnboundLocalError while reading an inventory

### ISSUE THREAD

**Issue by jbtruffault** [obspy/obspy#2552]
Hi ! 

I loaded some station.xml files from a datacenter using Arclink, and I got an error while loading them with obspy.

Here is the code: 

```python
from obspy import read_inventory
read_inventory("data/UB.XXXX.xml")
```

Here is the error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\decorator.py:decorator-gen-45>", line 2, in read_inventory
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\core\util\decorator.py", line 301, in _map_example_filename
    return func(*args, **kwargs)
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\core\inventory\inventory.py", line 98, in read_inventory
    format=format, *args, **kwargs)[0]
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\core\util\base.py", line 459, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 151, in _read_inventory_xml
    networks.append(_read_network(root, net_element))
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 217, in _read_network
    stations.append(_read_station(inventory_root, sta_element))
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 272, in _read_station
    channels.append(_read_channel(inventory_root, channel))
  File "C:\Users\Cooperant\Anaconda3\envs\py_37\lib\site-packages\obspy\io\arclink\inventory.py", line 460, in _read_channel
    response_element, cha_element,
UnboundLocalError: local variable 'response_element' referenced before assignment
```

This error happens with obspy 1.1.0 and 1.1.1, python 3.5 and 3.7.
I was able to load Station XML files from GEOSCOPE network. 

It seems that the error would come from my XML file, I do not know what are the next debug steps to follow. 

Here is the file: https://framabin.org/p/?63afac071754cd9d#RyZL4euIFktS6l2RgYP5hqk3VxMyp+TCEBnK7dLfGkg=

Do you have any idea ? Could my XML be in a special format that is not handle by obspy ? 

Thank you !

**Comment by Jollyfant** [comment]
The code assumes that publicID is delimited by a `#` character while yours are delimited by `/`. You can replace all instances of:

    response="ResponsePAZ/20190918025408.862188.43"

with

    response="ResponsePAZ#20190918025408.862188.43"

to make it work with this version of ObsPy.

To fix this the code should follow the same approach as `io/seiscomp/inventory.py` and create a lookup table for publicID -> elements.

**Comment by jbtruffault** [comment]
The workaround works perectly ! Thank you !

**Comment by jbtruffault** [comment]
Ater trying to remove instrumental response, I got another error.

Do you think that it could be resolved with a similar trick ? 

```
**Traceback (most recent call last):
  File "E:/Cooperant/Documents/draw_dsp.py", line 158, in <module>
    main()
  File "E:/Cooperant/Documents/draw_dsp.py", line 129, in main
    st = load_file_as_stream(args.file, args.inventory)
  File "E:/Cooperant/Documents/draw_dsp.py", line 36, in load_file_as_stream
    st.remove_response(inventory=inv)
  File "C:\Users\Cooperant\Anaconda3\envs\py_35\lib\site-packages\obspy\core\stream.py", line 3063, in remove_response
    tr.remove_response(*args, **kwargs)
  File "<C:\Users\Cooperant\Anaconda3\envs\py_35\lib\site-packages\decorator.py:decorator-gen-28>", line 2, in remove_response
  File "C:\Users\Cooperant\Anaconda3\envs\py_35\lib\site-packages\obspy\core\trace.py", line 232, in _add_processing_info
    result = func(*args, **kwargs)
  File "C:\Users\Cooperant\Anaconda3\envs\py_35\lib\site-packages\obspy\core\trace.py", line 2821, in remove_response
    output=output, **kwargs)
  File "C:\Users\Cooperant\Anaconda3\envs\py_35\lib\site-packages\obspy\core\inventory\response.py", line 1431, in get_evalresp_response
    freqs, output=output, start_stage=start_stage, end_stage=end_stage)
  File "C:\Users\Cooperant\Anaconda3\envs\py_35\lib\site-packages\obspy\core\inventory\response.py", line 1393, in get_evalresp_response_for_frequencies
    end_stage=end_stage)
  File "C:\Users\Cooperant\Anaconda3\envs\py_35\lib\site-packages\obspy\core\inventory\response.py", line 914, in _call_eval_resp_for_frequencies
    raise ObsPyException(msg)
obspy.core.util.obspy_types.ObsPyException: Can not use evalresp on response with no response stages.**
```

**Comment by megies** [comment]
There seems to be some implicit information encoded in the `publicID` @Jollyfant? The schema just says it's a string but in the code we are looking for very specific key strings in those IDs. Is there a definitive documentation for the format or how these publicID strings are supposed to be built up?

> Not sure if this is worth fixing considering that the Arclink protocol is being deprecated.

Yes and no. You're right that arclink should die out, but on the other hand you never know, local metadata files in that format might be around for decades yet. There's a reason why we have dozens

**Comment by Jollyfant** [comment]
> There seems to be some implicit information encoded in the publicID @Jollyfant? The schema just says it's a string but in the code we are looking for very specific key strings in those IDs. Is there a definitive documentation for the format or how these publicID strings are supposed to be built up?

Right now I think the publicID's can be any string and have no semantics.. When I implemented this I thought it was standard to use `ResponseFIR#` to reference a `<responseFIR>` element but woe is me and that seems not to be the case.

**Comment by Jollyfant** [comment]
@jbtruffault try replacing all the `/` characters in the publicID section with a # (e.g. ResponseFIR, ResponsePAZ, Station). It has trouble finding the elements because the identifiers do not much.

Seems to have changed on this commit from 2017: https://github.com/SeisComP3/seiscomp3/commit/e71e904332fbb12b4b93be37106759ebce36e8be

**Comment by megies** [comment]
@Jollyfant I think we should accommodate that change since what SeisComP is outputting can't be neglected here. Are you able to prepare a fix for 1.2.0 maybe, accepting both `#` and `/` as that delimiter?

**Comment by Jollyfant** [comment]
I don't think it's enough since I believe publicID can be an arbitrary string.. and that warrants a refactor of the full parsing code. But it will stop this common case from occurring.. we could try something hacky like:

    resp_type = response_id.replace("#", "/").split("/")[0]

**Comment by megies** [comment]
Good for me for now. I imagine files output by seiscomp are the majority of files this is being used on, so this is an important fix, and other cases not covered yet might be marginal (at least nobody ever reported not being able to read a file with this).
