### ISSUE TITLE
inconsistencies in bool(catalog)

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2556]
Catalog object can report `True` or `False` depending on installation when catalog contains no events but has some meta attributes set (in the case where it popped up, `Catalog.description` was set)

```
cat = Catalog()
cat.description = "hello world"
if cat:  # this is not consistent across all installations
    pass
```

See http://tests.obspy.org/108590/#1, this used to not show up before so `bool(cat)` is returning `True` on newer installations.

```
Traceback (most recent call last):
File "/obspy/obspy/io/iaspei/tests/test_core.py", line 101, in test_reading
cat = _read_ims10_bulletin(self.path_to_ims, _no_uuid_hashes=True)
File "/obspy/obspy/io/iaspei/core.py", line 629, in _read_ims10_bulletin
reset_fp=False, **kwargs)
File "/obspy/obspy/io/iaspei/core.py", line 617, in _buffer_proxy
return function(fh, *args, **kwargs)
File "/obspy/obspy/io/iaspei/core.py", line 643, in __read_ims10_bulletin
return ISFReader(fh, **kwargs).deserialize()
File "/obspy/obspy/io/iaspei/core.py", line 89, in deserialize
self._deserialize()
File "/obspy/obspy/io/iaspei/core.py", line 106, in _deserialize
self.cat[-1].scope_resource_ids()
File "/obspy/obspy/core/event/catalog.py", line 167, in __getitem__
return self.events.__getitem__(index)
IndexError: list index out of range
```

We should consider delegating `bool` to `def __len__` maybe?

```python
class Catalog(object):
    def __bool__(self):
        return len(self) and True or False
```

**Comment by d-chambers** [comment]
Wouldn't it be simpler like this, or is there a reason you are avoiding the `bool`?

```python
def __bool__(self):
    return bool(self.events)
```

**Comment by megies** [comment]
Yeah that looks good to me @d-chambers  :+1:

**Comment by ThomasLecocq** [comment]
did this make it to 1.2.1?

**Comment by megies** [comment]
Nope don't think its in the code yet, also, all issues in 1.2.1 can be punted to 1.2.2. But to be honest, I would focus on 2.0.0, put mostly everything into master and only backport really important stuff into 1.2.x
