### ISSUE TITLE
Error in plotting for new cartopy release 0.18

### ISSUE THREAD

**Issue by PSHA-research** [obspy/obspy#2624]
I'm trying to read and plot an ndk file i have obtained from CMT, just a simple example form Obspy gives me the following error:

Traceback (most recent call last):
  File "obspy-io-ndk-1.py", line 4, in <module>
    cat.plot()
  File "/home/nima/src/conda/lib/python3.7/site-packages/obspy/core/event/catalog.py", line 760, in plot
    show=False, fig=fig, **kwargs)
  File "/home/nima/src/conda/lib/python3.7/site-packages/obspy/imaging/maps.py", line 795, in plot_map
    return plot_cartopy(*args, **kwargs)
  File "/home/nima/src/conda/lib/python3.7/site-packages/obspy/imaging/maps.py", line 737, in plot_cartopy
    transform=ccrs.Geodetic())
  File "/home/nima/src/conda/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 307, in wrapper
    'PlateCarree/RotatedPole.'.format(func.__name__))
ValueError: Invalid transform: Spherical scatter is not supported - consider using PlateCarree/RotatedPole.

I have **_cartopy_** installed instead of basemap and I have install OBSPY using Anaconda nad it's version is: 1.2.1
Please Help in this issue,
Regards.

[obspy-io-ndk-1.txt](https://github.com/obspy/obspy/files/4740651/obspy-io-ndk-1.txt)

**Comment by trichter** [comment]
Thanks for reporting. I can confirm this bug for cartopy 0.18 released in May 2020.
`read_events().plot()` is enough to trigger it. One work-around would be to downgrade cartopy to version 0.17.

**Comment by trichter** [comment]
Same problem for `read_inventory().plot()`.

**Comment by trichter** [comment]
This should be fixed in master now.
