### ISSUE TITLE
Bug in hypodd PHA read

### ISSUE THREAD

**Issue by WayneCrawford** [obspy/obspy#2627]
HypoDD PHA read does not read a catalog file that I downloaded from the OOI website: http://axial.ocean.washington.edu/#name6 because it could not handle "NaN" as a magnitude
nor seconds outside the range of 0..59.  Neither of these are explicitly allowed (or disallowed) 
in the HypoDD docs I found, but the file is of general interest and the solution simple.  Here is
the code that reproduces the error, using the files attached in [error_example.zip](https://github.com/obspy/obspy/files/4756520/error_example.zip):

```python
#!/bin/env python3
from obspy.core.inventory.inventory import read_inventory
from obspy.core.event.catalog import read_events

inv = read_inventory('OO_SP_stationonly.xml')
cat = read_events('ph2dt_example_errors.dat', 'HYPODDPHA', inventory=inv,
                  id_default='OO.{}.00.EH{}')
print(cat)
```
which results in:
```
Traceback (most recent call last):
  File "error_example.py", line 7, in <module>
    id_default='OO.{}.00.EH{}')
  File "<decorator-gen-46>", line 2, in read_events
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 812, in read_events
    return _generic_reader(pathname_or_url, _read, format=format, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 701, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-47>", line 2, in _read
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 821, in _read
    **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 469, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 112, in _read_pha
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 112, in <listcomp>
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 51, in _block2event
    magnitude = Magnitude(mag=mg, resource_id="smi:local/magnitude/" + id_)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/base.py", line 405, in __init__
    **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/base.py", line 226, in __init__
    setattr(self, key, value)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/base.py", line 391, in __setattr__
    raise ValueError(msg)
ValueError: On Magnitude object: Value 'nan' for 'mag' is not a finite floating point value.
```
To make it work, I had to change the first lines in `io/hypodd/pha.py:_block2event()`
Original:
```python
    lines = block.strip().splitlines()
    yr, mo, dy, hr, mn, sc, la, lo, dp, mg, eh, ez, rms, id_ = lines[0].split()
    time = UTCDateTime(int(yr), int(mo), int(dy), int(hr), int(mn), float(sc))
```
Final:
```python
    lines = block.strip().splitlines()
    yr, mo, dy, hr, mn, sc, la, lo, dp, mg, eh, ez, rms, id_ = lines[0].split()
    if mg == 'NaN':
        mg = None
    time = UTCDateTime(int(yr), int(mo), int(dy), int(hr), int(mn)) + float(sc)
```
(there is probably a smarter "if" statment that covers other possible problems).

The code now returns:
```
18 Event(s) in Catalog:
2015-03-04T01:59:55.413000Z | +45.950, -129.986 | 0.0 None
2015-03-04T02:00:35.871000Z | +45.984, -129.993 | None None
...
2015-03-29T22:40:10.109000Z | +45.927, -129.997 | -0.0 None
2015-03-29T22:40:20.110000Z | +45.953, -129.983 | -0.3 None
To see all events call 'print(CatalogObject.__str__(print_all=True))'
```
If I change only  the lines with `mg` I get the following error:
```
Traceback (most recent call last):
  File "error_example.py", line 7, in <module>
    id_default='OO.{}.00.EH{}')
  File "<decorator-gen-46>", line 2, in read_events
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 812, in read_events
    return _generic_reader(pathname_or_url, _read, format=format, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 701, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-47>", line 2, in _read
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/event/catalog.py", line 821, in _read
    **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/util/base.py", line 469, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 114, in _read_pha
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 114, in <listcomp>
    for block in text.split('#')[1:]]
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/io/hypodd/pha.py", line 31, in _block2event
    time = UTCDateTime(int(yr), int(mo), int(dy), int(hr), int(mn), float(sc))
  File "/Users/crawford/anaconda3/envs/obspy/lib/python3.6/site-packages/obspy/core/utcdatetime.py", line 466, in __init__
    dt = datetime.datetime(*args, **kwargs)
ValueError: second must be in 0..59
```
I have attached a version of `pha.py` with these modifications

obspy version = 1.2.1, installed using Anaconda

**Comment by trichter** [comment]
Thanks for raising this issue. I can create a PR to fix it. PHA support is quite new, if you stumble upon other issues, please drop a note.

By the way, I implemented the reader, but actually I didn't use HYPODD. Are these pha files with 60.0 as seconds created by HYPODD?

**Comment by megies** [comment]
Pretty sure we saw some "60 seconds" files with some other file format before.. I think it was nonlinloc?

With regard to unexpected file content ("NaN" in a float field), I would encourage talking to the person "in charge" of the file format and finding out if this is widely used (so we should implement the workaround) or rather some community code making bad use of the file format (then the institution/code producing those files should be contacted to fix it upstream).

**Comment by WayneCrawford** [comment]
OK, I will talk to the author about the NaN.  NORDIC files have the 60-second problem, which is why I knew quickly how to "fix" it!

_______________________________
Wayne Crawford
CNRS Researcher
Institut de Physique du Globe de Paris
1, rue Jussieu
75238 Paris Cedex 05
+33 6 5151 1054

On 10 June 2020 at 10:33:57, Tobias Megies (notifications@github.com) wrote:

Pretty sure we saw some "60 seconds" files with some other file format before.. I think it was nonlinloc?

With regard to unexpected file content ("NaN" in a float field), I would encourage talking to the person "in charge" of the file format and finding out if this is widely used (so we should implement the workaround) or rather some community code making bad use of the file format (then the institution/code producing those files should be contacted to fix it upstream).

**Comment by megies** [comment]
Pretty sure, thats the flag we put into UTCDateTime to handle those 60s problems (and consorts):

```python
 460         except ValueError:
 461             if not strict:
 462                 self._handle_overflow(*args, **kwargs)
 463             else:
 464                 raise
 465         else:
 466             self._from_datetime(dt)
 467 
 468     def _handle_overflow(self, year, month, day, hour=0, minute=0, second=0,
 469                          microsecond=0):
```

```
~/git/obspy/obspy｢master｣$ pygrep 'strict=False'
io/nlloc/core.py
191:    time = UTCDateTime(year, mon, day, hour, min, seconds, strict=False)
331:        t = UTCDateTime(*(ymd + hm), strict=False) + float(sec)
```

**Comment by WayneCrawford** [comment]
Another comment, on the documentation.  It would be nice to have  couple of lines explaining how this function "chooses" between possible seed ids.  I had a long list of stations with many networks, some stations with several different band-instrument codes for the same orientation code, etc.  Looking at the documentation for "id_default" I was afraid that they were all going to be forced to the same network code and band/instrument code.  I was preparing an "id_map" listing them all, but it seems that your function did the right thing almost all of the time: choosing the faster-sampling and higher gain option wherever possible.  I don't even know if it used the id_default I supplied.  

Could you write in the top of the docstring that your code tries to find the appropriate seed code in the station file and, if there is ambiguity, it :
   1) looks at id_map for a direct station name match
  2) looks at id_default for a direct match to the other seed_id parameters, 
  3) makes the best choice it can based on ....
I assume this is the order!

Anyway, I'm impressed by what it selected, much better than what the docstring made me fear!

**Comment by trichter** [comment]
Yes, good idea. I think it works the following

1. look at id_map for a direct station name match and use the specified template
2. if 1 did not succeed, look if the station is present in inventory and use its first channel as template
3. if 1 and 2 did not succeed, use specified default template (id_default)

> but it seems that your function did the right thing almost all of the time: choosing the faster-sampling and higher gain option wherever possible

Probably that is, because these higher gains are specified before the other channels in your inventory file.

One case which is not covered: station changing SEED id within the period covered by the pha file.

**Comment by megies** [comment]
I actually have no clue what this is on about, guess some looking up full SEED ID from an inventory based on a net/sta only info from that PHA file?
Anyway.. looks like you have the best idea about it @trichter so you in charge now here ;-P

**Comment by megies** [comment]
Would be good if somebody could look at this ASAP for 1.2.2. see #2655. If we dont get volunteers it might have to be shelved for later

**Comment by trichter** [comment]
I can have a look. Still need feedback if NaN values for the magnitude should get accepted.

**Comment by megies** [comment]
Feedback from somebody in particular? Ping anybody you need feedback from. without looking at details I would vote to completely omit a Magnitude node, if the value as a NaN. What's a magnitude worth if it has no magnitude? Just my 2 cents :thinking:

**Comment by megies** [comment]
I checked. QuakeML requires Magnitude to have a value and it must be a double. So we are talking something QuakeML-invalid with a NaN magnitude value..

**Comment by trichter** [comment]
@WayneCrawford wanted to talk with the author of the files in question.

Sure, I did not intent to actually set a NaN value for the magnitude, just if these files should get accepted (and not set the magnitude for the corresponding event). For me it des not matter much. I'd say why not? But on the other hand, if it is regarded as an invalid file, it will be trivial to make it valid for everyone.

**Comment by megies** [comment]
I don't care too much, whatever you folks think is best :+1:

**Comment by megies** [comment]
Resolved in linked PR

**Comment by trichter** [comment]
@megies, this still needs to land in master, may I assume that you cherry pick the relevant PRs after the release of 1.2.2?

**Comment by megies** [comment]
Yeah, we'll just merge maintenance branch into master, so all good
Cherry picking / backporting is only needed if a fix was done in master.

I was kind of hoping we wouldn't need a 1.2.2, that's why there was a bit confusion lately and sometimes fixes being done on maintenance branch and sometimes in master. My bad. Master is just so different from maintenance right now, that's why I was hoping to avoid more work in maintenance 1.2.x branch.
