### ISSUE TITLE
SC3 xml inventory read error

### ISSUE THREAD

**Issue by a-oth** [obspy/obspy#2633]
When trying to use `read_inventory` to read a sc3 xml inventory file generated with the SMP tool of Gempa, I receive the following error:

```
Traceback (most recent call last):
  File "./resave_SC3XML.py", line 12, in <module>
    inv = read_inventory(invfile)
  File "<decorator-gen-49>", line 2, in read_inventory
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/core/inventory/inventory.py", line 88, in read_inventory
    return _generic_reader(path_or_file_object, _read, format=format,
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/core/util/base.py", line 701, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-50>", line 2, in _read
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/core/inventory/inventory.py", line 97, in _read
    inventory, format = _read_from_plugin('inventory', filename, format=format,
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/core/util/base.py", line 469, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/io/seiscomp/inventory.py", line 181, in _read_sc3ml
    networks.append(_read_network(instrumentation_register,
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/io/seiscomp/inventory.py", line 236, in _read_network
    stations.append(_read_station(instrumentation_register,
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/io/seiscomp/inventory.py", line 300, in _read_station
    channels.append(_read_channel(instrumentation_register,
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/io/seiscomp/inventory.py", line 540, in _read_channel
    channel.response = _read_response(instrumentation_register['responses'],
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/io/seiscomp/inventory.py", line 663, in _read_response
    analogue_response = _read_response_stage(analogue_element, _ns,
  File "/Users/adrien/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/obspy/io/seiscomp/inventory.py", line 818, in _read_response_stage
    zeros_array = stage.find(_ns("zeros")).text
AttributeError: 'NoneType' object has no attribute 'text'
```

I tracked this down and it is due to the fact that if for a PAZ response of a channel (analogue stage of datalogger), the number of zeros is zero (`<numberOfZeros>0</numberOfZeros>`), the `<zeros>` field is not written to the xml file (same thing for the poles) instead of being written but empty. 

I use ObsPy version 1.2.1 installed using pip on macOS 10.15, with python3 installed in pyenv environment.

**Comment by heavelock** [comment]
Thanks for report. Could you provide a minimal xml file that is causing this issue?

**Comment by a-oth** [comment]
Sure, sorry for the omission in my prior message! Please find an example for one station attached.
[example_II_MBAR.xml.zip](https://github.com/obspy/obspy/files/4770665/example_II_MBAR.xml.zip)

**Comment by a-oth** [comment]
As a side note, I also noted that ObsPy does not support schemas 0.10 and 0.11, but that's a side note only.

**Comment by megies** [comment]
Would be good if somebody could look at this ASAP for 1.2.2. see #2655. If we dont get volunteers it might ave to be shelved for later

**Comment by aringler-usgs** [comment]
@megies I will look into this in the next hour or so.

**Comment by megies** [comment]
Fixed

**Comment by a-oth** [comment]
Many thanks!
