### ISSUE TITLE
Installation Issues with numpy 1.19

### ISSUE THREAD

**Issue by mlin26** [obspy/obspy#2651]
Hi,

I'm trying to install the latest obspy on Cluster and Local Linux System by using:

```
pip install obspy
```

But they both show same errors as follows:

```
(py37) mlin4@UW-2UA90215W1:/mnt/x/pysit$ pip install obspy
Collecting obspy
  Using cached obspy-1.2.1.zip (24.7 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/mlin4/miniconda3/envs/py37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wz2itmyf/obspy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wz2itmyf/obspy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e3zssxfz
         cwd: /tmp/pip-install-wz2itmyf/obspy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wz2itmyf/obspy/setup.py", line 47, in <module>
        from numpy.distutils.core import DistutilsSetupError, setup
    ImportError: cannot import name 'DistutilsSetupError' from 'numpy.distutils.core' (/home/mlin4/.local/lib/python3.7/site-packages/numpy/distutils/core.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Version Information:
pip 20.1.1
python3.7.7
numpy1.19.0

Could you tell me how to solve this problem?

Regards,
ML

**Comment by trichter** [comment]
Hi,

this is a known bug fixed in master, see #2643.

Until a new obspy version is released, the easiest work-around is downgrading numpy to 1.18.

**Comment by heavelock** [comment]
Alternatively, if you need numpy 1.19 and you are willing to install current master, `python -m pip install git+git://github.com/obspy/obspy@master`.

**Comment by megies** [comment]
I think this can be closed as it's properly answered above, but feel free to post in here again @mlin26 if anything is still unclear.
