### ISSUE TITLE
Beachball plotting bug for a specific size

### ISSUE THREAD

**Issue by qianchengliu0** [obspy/obspy#2664]
Dear Obspy Team,

I am using ObsPy 1.2.2 installed via Conda on Linux. Recently, when plotting some beachball, I encountered this small bug
```
/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/beachball.py:54: UserWarning: Encountered an exception while plotting the beachball. Falling back to the mopad wrapper which is slower but more stable.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/beachball.py", line 49, in mopad_fallback
    result = func(*args, **kwargs)
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/beachball.py", line 154, in beach
    plot_zerotrace=True, xy=xy, width=width)
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/beachball.py", line 441, in plot_mt
    azi[n][0] = az
IndexError: index 3 is out of bounds for axis 0 with size 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "</home/ql5/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-38>", line 2, in beach
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/beachball.py", line 70, in mopad_fallback
    result = _mopad_beach(**final_kwargs)
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/mopad_wrapper.py", line 133, in beach
    bb._setup_BB(unit_circle=False)
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/scripts/mopad.py", line 2537, in _setup_BB
    self._correct_curves()
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/scripts/mopad.py", line 2564, in _correct_curves
    obj2cor_in_right_order = self._sort_curve_points(obj2cor)
  File "/home/ql5/anaconda3/envs/obspy/lib/python3.7/site-packages/obspy/imaging/scripts/mopad.py", line 3416, in _sort_curve_points
    angle_point_3 = (math.atan2(sorted_curve[0, 2],
IndexError: index 2 is out of bounds for axis 1 with size 2
```
whch can be reproduced by
```
from obspy.imaging.beachball import beach
Mrr=-9.518911810845E+02
Mtt=8.038472535133E+17
Mpp=-8.038472535133E+17
Mrt=2.712661573813E+17
Mrp=-7.768046389853E+18
Mtp=-1.149555129387E+19
mt = [Mrr,Mtt,Mpp,Mrt,Mrp,Mtp]
b = beach(mt, linewidth=1, xy=(0, 0.6), width=1, size=2, facecolor='r')
```
However, it works fine when size=3. Could you advise on this?

Cheers,
Qiancheng

**Comment by qianchengliu0** [comment]
It works fine now.

**Comment by heavelock** [comment]
Well, It's hard to say that it's a bug. I would rather say that's a feature. You are going below minimum number of minimum interpolation points that mopad is accepting. Also, way below suggested number (default is 100). The only thing I would do here is to raise more informative error, I think.

**Comment by qianchengliu0** [comment]
Yes, you are right. I realize this soon after arising the issue and have it closed. Thanks for your very kind response!
