### ISSUE TITLE
Unsupported data type int32: Writing data to miniseed from seedlink on Windows

### ISSUE THREAD

**Issue by calum-chamberlain** [obspy/obspy#2683]
Using the `EasySeedlinkClient` and trying to write out the traces provided by the Client to miniseed on Windows results in an odd error:

```python
Traceback (most recent call last):
  File "seedlink_int32_issue.py", line 21, in <module>
    client.run()
  File "C:\Users\gorid\anaconda3\lib\site-packages\obspy\clients\seedlink\easyseedlink.py", line 426, in run
    self.on_data(trace)
  File "seedlink_int32_issue.py", line 13, in on_data
    trace.write("test_data.mseed", format="MSEED")
  File "C:\Users\gorid\anaconda3\lib\site-packages\obspy\core\trace.py", line 990, in write
    Stream([self]).write(filename, format, **kwargs)
  File "C:\Users\gorid\anaconda3\lib\site-packages\obspy\core\stream.py", line 1462, in write
    write_format(self, filename, **kwargs)
  File "C:\Users\gorid\anaconda3\lib\site-packages\obspy\io\mseed\core.py", line 820, in _write_mseed
    raise Exception(msg)
Exception: Unsupported data type int32 in Stream[0].data
```

## Install info

- ObsPy 1.2.2 (from Anaconda)
- Windows 10
- Python 3.7

## Example

I can reproduce this in a fresh anaconda install using the following example:

```python
""" Example of issue with writing mseed from seedlink client. """

import os
import numpy as np
from obspy.clients.seedlink import EasySeedLinkClient

class MyClient(EasySeedLinkClient):
    def on_data(self, trace):
        print("Writing data")
        print(f"{trace.data.dtype}")
        trace.write("test_data.mseed", format="MSEED")


if __name__ == "__main__":
    client = MyClient("link.geonet.org.nz")
    client.select_stream(net="NZ", station="FOZ", selector="HHZ")
    print(client)
    try:
        client.run()
    finally:
        if os.path.isfile("test_data.mseed"):
            print("Cleaning test_data.mseed")
            os.remove("test_data.mseed")
```

This looks like it stems from checking whether `trace.data.dtype.type == np.int32`. On Ubuntu and MacOS this comparison seems fine, but on Windows there is something funny going on.  The code that checks the data type is [here](https://github.com/obspy/obspy/blob/master/obspy/io/mseed/core.py#L788).

Interestingly (or to me at least, because I don't know why this happens),
- `trace.data.dtype == np.int32` evaluates to `True` in the above example, but
- `trace.data.dtype.type == np.int32` evaluates `False`.

I'm not sure if this is an issue in writing miniseed, or how data are handled coming from a seedlink service?

**Comment by megies** [comment]
No idea why that `.type` is there in the first place.. comparing `.dtype == np....` would be what I'd do

**Comment by megies** [comment]
Also, numpy is advertising `is` for comparison: https://numpy.org/doc/stable/reference/arrays.dtypes.html

![Screenshot from 2020-07-16 16-11-55](https://user-images.githubusercontent.com/1842780/87681596-1d071980-c77f-11ea-8542-1c4ccf0de3c1.png)

**Comment by megies** [comment]
Can you reproduce that problem without the seedlink client, after reading the problematic miniseed you are writing to disk? Having a reliable regression test would be the most important thing to get. @calum-chamberlain

**Comment by calum-chamberlain** [comment]
> No idea why that `.type` is there in the first place.. comparing `.dtype == np....` would be what I'd do

Me too.  I will have a play today and try and make a useful (breaking) file and make a PR. It seems strange that the example works fine on Linux, but not on Windows - I will see if I can break Linux as well...

**Comment by calum-chamberlain** [comment]
So on Windows the data that come in have:
```python
trace.data.dtype == np.int32
trace.data.dtype.type == np.intc
```
On Linux the same script gets data of the form:
```python
trace.data.dtype == np.int32 == trace.data.dtype.type
```

Hacking so that writing is possible (by changing from checking `dtype.type` to `dtype`) ends up with the data that come back into Windows after `trace.write(fname); st_back = read(fname)` has `dtype == dtype.type == np.int32`. I don't see a way to write a file with these datatypes - we could hack a test that changes `dtype.type` to `np.intc`?

**Comment by megies** [comment]
> we could hack a test that changes `dtype.type` to `np.intc`?

sounds good to me :+1: essentially what mock does in testing

**Comment by megies** [comment]
Never seen that `np.intc` btw.. really weird. Kind of curious how we end up with it, might be even a numpy version dependent issue? Or even something worth reporting to numpy upstream? Although we'd better reproducibility, outside of a seedlink client.. ;-)

**Comment by vb-mesilat** [comment]
Having the same problem with RaspberryPI: trace.write works on Mac, but not on Raspberry :(
