### ISSUE TITLE
Rotation with inconsistent traces crashes with unexpected error

### ISSUE THREAD

**Issue by yetinam** [obspy/obspy#2691]
Obspy version: 1.2.2 (installed from source)
Python version: 3.7.7
OS: Ubuntu 18.04

When calling rotation on a stream with inconsistent channels, the rotation crashes with the error "Unexpected behavior in rotation. Please file a bug report on github.". An example trace consists of four channels for one station, BH1, BH1, BH2 and BHZ, where waveforms for the two versions of BH1 do not agree.

The error can be reproduced with the following script:
```
import obspy
from obspy.clients.fdsn import Client

client = Client('IPGP')

inv = client.get_stations(net='G', station='KIP', location='10', channel='BH*', level='response')

stream = obspy.read('illegal_rotation.mseed')
stream2 = stream.copy()

print(f'Stream before:\n{stream}')
stream.rotate('->ZNE', inventory=inv)
print(f'Stream after correct rotation:\n{stream}')
stream2.remove_response(inventory=inv)
print(f'Stream after response removal:\n{stream2}')
stream2.rotate('->ZNE', inventory=inv)
```
The code requires the following mseed files: [illegal_rotation.mseed.zip](https://github.com/obspy/obspy/files/5007834/illegal_rotation.mseed.zip)

Code output:
```
Stream before:
4 Trace(s) in Stream:
G.KIP.10.BH1 | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
G.KIP.10.BH1 | 2012-08-16T06:43:06.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 641 samples
G.KIP.10.BH2 | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
G.KIP.10.BHZ | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
Stream after correct rotation:
3 Trace(s) in Stream:
G.KIP.10.BHZ | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
G.KIP.10.BHN | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
G.KIP.10.BHE | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
Stream after response removal:
4 Trace(s) in Stream:
G.KIP.10.BH1 | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
G.KIP.10.BH1 | 2012-08-16T06:43:06.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 641 samples
G.KIP.10.BH2 | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
G.KIP.10.BHZ | 2012-08-16T06:42:52.169500Z - 2012-08-16T06:43:22.169500Z | 40.0 Hz, 1201 samples
Traceback (most recent call last):
  File "rotation.py", line 16, in <module>
    stream2.rotate('->ZNE', inventory=inv)
  File "obspy/obspy/core/stream.py", line 2709, in rotate
    return self._rotate_to_zne(inventory, **kwargs)
  File "obspy/obspy/core/stream.py", line 3444, in _rotate_to_zne
    net, sta, loc, channels_, inventory)
  File "obspy/obspy/core/stream.py", line 3506, in _rotate_specific_channels_to_zne
    raise NotImplementedError(msg)
NotImplementedError: Unexpected behavior in rotation. Please file a bug report on github.
```

The first rotation succeeds, because the `_cleanup` from https://github.com/obspy/obspy/blob/88687a146a7c3ca8f35c608db2243cf5fed6813c/obspy/core/stream.py#L3377 works, but after removing response the waveforms do not agree anymore and can not be cleaned up.

While this is clearly a case where an error should be raised, I'd suggest an explicit error, rather than the current `NotImplementedError` if the user tries to rotate inconsistent traces.

**Comment by megies** [comment]
Yeah we need to change this somehow. Side note: always a good idea to do a `st.merge(-1)` before any processing, also you should always use like 2 minutes at start/end of time window of interest for all processing and then cut out the time window of interest after all preprocessing is done. You'll have strong artifacts if you use a 30s time window for instrument removal, filtering etc
