### ISSUE TITLE
taup pierce for phase 2kmps raises error

### ISSUE THREAD

**Issue by crotwell** [obspy/obspy#2754]
"2kmps" is a fake phase name in TauP for a 2kmps surface wave. Pierce points for this are mostly not useful, just the start and ending points, but not raising an error in this case would be nice.

```
from obspy.taup import TauPyModel
taumodel = TauPyModel(model="prem" )
arrivals = taumodel.get_pierce_points(source_depth_in_km=origin.depth/1000,
                                   distance_in_degree=daz.getDistanceDeg(),
                                   phase_list=["2kmps"])
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'origin' is not defined
>>> arrivals = taumodel.get_pierce_points(source_depth_in_km=10, distance_in_degree=30, phase_list=["2kmps"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/crotwell/opt/miniconda3/envs/obspy/lib/python3.7/site-packages/obspy/taup/tau.py", line 680, in get_pierce_points
    pp.run()
  File "/Users/crotwell/opt/miniconda3/envs/obspy/lib/python3.7/site-packages/obspy/taup/taup_time.py", line 39, in run
    self.calculate(self.degrees)
  File "/Users/crotwell/opt/miniconda3/envs/obspy/lib/python3.7/site-packages/obspy/taup/taup_pierce.py", line 73, in calculate
    self.calculate_pierce(degrees)
  File "/Users/crotwell/opt/miniconda3/envs/obspy/lib/python3.7/site-packages/obspy/taup/taup_pierce.py", line 82, in calculate_pierce
    self.arrivals += phase.calc_pierce(degrees)
  File "/Users/crotwell/opt/miniconda3/envs/obspy/lib/python3.7/site-packages/obspy/taup/seismic_phase.py", line 1047, in calc_pierce
    self.calc_pierce_from_arrival(arrival)
  File "/Users/crotwell/opt/miniconda3/envs/obspy/lib/python3.7/site-packages/obspy/taup/seismic_phase.py", line 1090, in calc_pierce_from_arrival
    len(self.down_going)
AssertionError

```

But in java version:
```
taup_pierce -h 10 -deg 30 -ph 2kmps
> 2kmps at  1667.92 seconds at    30.00 degrees for a     10.0 km deep source in the iasp91 model with rayParam   55.597 s/deg.
    0.00    10.0     0.0
   30.00     0.0  1667.9
> 2kmps at 18347.16 seconds at   330.00 degrees for a     10.0 km deep source in the iasp91 model with rayParam   55.597 s/deg.
    0.00    10.0     0.0
 -330.00     0.0 18347.2
```

```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

obspy                     1.2.2            py37h10e2902_0    conda-forge
```

**Comment by johnrudge** [comment]
This is now fixed in master
```
from obspy.taup import TauPyModel
model = TauPyModel(model="prem")
arrivals = model.get_pierce_points(0.0, 30.0, phase_list=["2kmps"])
print(arrivals[0].pierce)
```
```
[(3185.5,    0.        , 0.        , 0.)
 (3185.5, 1667.92389967, 0.52359878, 0.)]
```
