### ISSUE TITLE
MassDownloader  :  NameError: name 'is_in_db' is not defined

### ISSUE THREAD

**Issue by vivigb** [obspy/obspy#2768]
I was just copy pasting the given code snippet from official obspy example code snippet to mass download the data.
```def get_stationxml_storage(network, station, channels, starttime, endtime):
    available_channels = []
    missing_channels = []
    for location, channel in channels:
        if is_in_db(network, station, location, channel, starttime,endtime):
            available_channels.append((location, channel))
        else:
            missing_channels.append((location, channel))

    start=str(starttime).split('.')[0].replace(':','-')
    end=str(endtime).split('.')[0].replace(':','-')
    ROOT_xml="ROOT/stationXML_{}_{}".format(start,end)

    filename = os.path.join(ROOT_xml, "%s.%s.xml" % (network, station))

    return {"available_channels": available_channels,
        "missing_channels": missing_channels,
        "filename": filename}
```
I am using the obspy on windows conda environment

```
Traceback (most recent call last):
  File "E:\WIHG\Programming\python\seismology\test.py", line 63, in <module>
    mdl.download(domain, restrictions, mseed_storage=get_mseed_storage,stationxml_storage = get_stationxml_storage)
  File "c:\python37\lib\site-packages\obspy\clients\fdsn\mass_downloader\mass_downloader.py", line 210, in download
    helper.prepare_stationxml_download()
  File "c:\python37\lib\site-packages\obspy\clients\fdsn\mass_downloader\download_helpers.py", line 661, in prepare_stationxml_download
    logger=self.logger)
  File "c:\python37\lib\site-packages\obspy\clients\fdsn\mass_downloader\download_helpers.py", line 241, in prepare_stationxml_download
    starttime=s, endtime=e)
  File "c:\python37\lib\site-packages\obspy\clients\fdsn\mass_downloader\utils.py", line 490, in get_stationxml_filename
    path = str_or_fct(network, station, channels, starttime, endtime)
  File "E:\WIHG\Programming\python\seismology\test.py", line 79, in get_stationxml_storage
    if is_in_db(network, station, location, channel, starttime,endtime):
NameError: name 'is_in_db' is not defined
```

**Comment by ThomasLecocq** [comment]
this is an example, _you_ have to define this ``is_in_db`` function yourself.

I'll leave the issue open because this shows maybe a lack of explanation in the documentation.
