### ISSUE TITLE
Problem in removing the instrument response (bad station.xml file from IRIS)

### ISSUE THREAD

**Issue by vivigb** [obspy/obspy#2771]
I mass downloaded data and corresponding station.xml files from IRIS using Obspy. But when I tried to remove the response some files are showing the following error.

```
from obspy import read
from obspy.core.inventory.inventory import read_inventory
st=read('KZ.KKAR..BHE.2008-01-18T19-16-51.mseed')
st+=read('KZ.KKAR..BHN.2008-01-18T19-16-51.mseed')
st+=read('KZ.KKAR..BHZ.2008-01-18T19-16-51.mseed')
inv=read_inventory('KZ.KKAR.xml')
st_rem=st.copy()
st_rem.remove_response(output='VEL',inventory=inv)
```
-->
  -  ObsPy 1.2.2
  -  Anaconda, Windows 10
```
Traceback (most recent call last):
  File "<ipython-input-5-9b75406f6a63>", line 2, in <module>
    st_rem.remove_response(output='VEL',inventory=inv)
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\obspy\core\stream.py", line 3155, in remove_response
    tr.remove_response(*args, **kwargs)
  File "<decorator-gen-147>", line 2, in remove_response
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\obspy\core\trace.py", line 273, in _add_processing_info
    result = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\obspy\core\trace.py", line 2885, in remove_response
    output=output, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\obspy\core\inventory\response.py", line 1674, in get_evalresp_response
    freqs, output=output, start_stage=start_stage, end_stage=end_stage)
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\obspy\core\inventory\response.py", line 1632, in get_evalresp_response_for_frequencies
    end_stage=end_stage)
  File "C:\ProgramData\Anaconda3\envs\roses\lib\site-packages\obspy\core\inventory\response.py", line 1581, in _call_eval_resp_for_frequencies
    raise e('check_channel: ' + m)
ValueError: check_channel: Illegal RESP format
 EVRESP ERROR (... [File: <stdin>; Start date: ; Stage: 3]):
	check_channel; units mismatch between stages,
	skipping to next response now
```
Is this something that normally occurs?

**Comment by megies** [comment]
Somebody will have to debug into the code / look at the StationXML file to see whats wrong with it..

**Comment by vivigb** [comment]
I compared the XML files. The XML file which gave me the error is giving the empty response plots for inv.plot_response(0.001, output="VEL").
Also for the code inv[0][0][0].plot(0.001, start_stage=1, end_stage=3)
the error is :
ValueError: check_channel: Illegal RESP format
 So If the IRIS response file itself is buggy, How can I report it?
Is there any other way around to get a correct response file? ( I have 100+ files with same problem)

**Comment by megies** [comment]
So I had a quick look and it seems we are running a function `check_channel` from official `evalresp` C code which produces this error.

What you could try is run [IRIS' stationxml-validator](https://github.com/iris-edu/stationxml-validator/) on the file and see what that has to say.

Other than that, problems should be reported to the people running the said network. If you can not find out who to contact, go through IRIS.

**Comment by vivigb** [comment]
```
`../IRIS_data$ java -jar stationxml-validator-1.7.1.jar KZ.KKAR.xml`

321,Warning,KZ,KKAR,BHZ,,2001-12-11T00:00:00,2018-09-19T00:00:00,Instrument code H should have stage last output units similar to count* but output units are M/S**2
321,Warning,KZ,KKAR,BHE,,2001-12-11T00:00:00,2018-09-19T00:00:00,Instrument code H should have stage last output units similar to count* but output units are M/S**2
321,Warning,KZ,KKAR,BHN,,2001-12-11T00:00:00,2018-09-19T00:00:00,Instrument code H should have stage last output units similar to count* but output units are M/S**2
402,Warning,KZ,KKAR,BHE,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 01] invalid input units M/S**2
402,Warning,KZ,KKAR,BHN,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 01] invalid input units M/S**2
402,Warning,KZ,KKAR,BHZ,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 01] invalid input units M/S**2
402,Warning,KZ,KKAR,BHE,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 02] invalid output units M/S**2
402,Warning,KZ,KKAR,BHZ,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 02] invalid output units M/S**2
402,Warning,KZ,KKAR,BHN,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 02] invalid output units M/S**2
402,Warning,KZ,KKAR,BHE,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 10] invalid input units M/S**2
402,Warning,KZ,KKAR,BHN,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 10] invalid input units M/S**2
402,Warning,KZ,KKAR,BHZ,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 10] invalid input units M/S**2
402,Warning,KZ,KKAR,BHE,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 10] invalid output units M/S**2
402,Warning,KZ,KKAR,BHZ,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 10] invalid output units M/S**2
402,Warning,KZ,KKAR,BHN,,2001-12-11T00:00:00,2018-09-19T00:00:00,[stage 10] invalid output units M/S**2
403,Error,KZ,KKAR,BHN,,2001-12-11T00:00:00,2018-09-19T00:00:00,Stage [03] input unit V must equal stage[02] output unit M/S**2
403,Error,KZ,KKAR,BHZ,,2001-12-11T00:00:00,2018-09-19T00:00:00,Stage [03] input unit V must equal stage[02] output unit M/S**2
403,Error,KZ,KKAR,BHE,,2001-12-11T00:00:00,2018-09-19T00:00:00,Stage [03] input unit V must equal stage[02] output unit M/S**2
403,Error,KZ,KKAR,BHN,,2001-12-11T00:00:00,2018-09-19T00:00:00,stage [10] input unit M/S**2 must equal stage[9] output unit V
403,Error,KZ,KKAR,BHE,,2001-12-11T00:00:00,2018-09-19T00:00:00,stage [10] input unit M/S**2 must equal stage[9] output unit V
403,Error,KZ,KKAR,BHZ,,2001-12-11T00:00:00,2018-09-19T00:00:00,stage [10] input unit M/S**2 must equal stage[9] output unit V
```

**Comment by ThomasLecocq** [comment]
your response file is wrong, you need to contact the KZ network manager; Sorry we can't help you more here.

**Comment by vivigb** [comment]
I accentuated this situation in IRIS mailing list, They will inform this to the network manager and solve this problem. 
I am first time using this station.XML format, But it seems like it is hard to identify and correct the errors in this format. I hope there will be options to download files in different formats ( just like in https://ds.iris.edu/wilber3/find_event) in future versions of `Obspy.MassDownloader`.

**Comment by geneichinose** [comment]
The OutputUnits under InstrumentSensitivity should be in COUNTS not M/S**2     

Model KS-54000-CTBT was designed to be an accelerometer so input is M/S**2

<Response>
     <InstrumentSensitivity>
       <Value>3.92718E9</Value>
       <Frequency>1.0</Frequency>
       <InputUnits>
         <Name>M/S**2</Name>
         <Description>Acceleration in Meters Per Second^2</Description>
       </InputUnits>
       <OutputUnits>
         <Name>M/S**2</Name>
         <Description>Acceleration in Meters Per Second^2</Description>
       </OutputUnits>
     </InstrumentSensitivity>
