### ISSUE TITLE
error performing network trigger due to missing or obsolete module

### ISSUE THREAD

**Issue by Donavin97** [obspy/obspy#2804]
Hello everyone.
I am a seismologist with a few questions about obspy and network triggering and detection examples.
It seems that there is a module missing from tr.stats, namely tr.stats.coordinates.
I am trying to perform continuous triggering without having predefined events, however for that to work, I'd have to find the closest triggered station.
My code is as follows:

```
from __future__ import print_function

from math import log10

import numpy as np

from obspy.clients.fdsn import Client
from obspy import Stream, UTCDateTime
from obspy.geodetics import gps2dist_azimuth
from obspy.signal.trigger import coincidence_trigger


client = Client("IRIS")

starttime = UTCDateTime("2017-04-03T03:00:00")
endtime = starttime + 1100

network = "*"
stations = ["BOSA", "LBTB", "SUR", "TSUM", "LSZ", "POGA"]
st = Stream()

for station in stations:
    try:
        tmp = client.get_waveforms(network=network, station=station, location="*", channel="BHZ", starttime=starttime, endtime=endtime,
                                   attach_response=True)
    except Exception:
        print(station, "---")
        continue
    st += tmp

st.filter("bandpass", freqmin=1, freqmax=9)
triglist = coincidence_trigger("recstalta", 10, 2, st, 4, sta=0.5, lta=10)
print(len(triglist), "events triggered.")

for trig in triglist:
    closest_sta = trig['stations'][0]
    tr = st.select(station=closest_sta)[0]
    trig['latitude'] = tr.stats.coordinates.latitude
    trig['longitude'] = tr.stats.coordinates.longitude

paz_wa = {'sensitivity': 2800, 'zeros': [0j], 'gain': 1,
          'poles': [-6.2832 - 4.7124j, -6.2832 + 4.7124j]}

for trig in triglist:
    t = trig['time']
    print("#" * 80)
    print("Trigger time:", t)
    mags = []

    stations = client.get_stations(starttime, starttime + 300, network=network)

    for station in stations:
        station = station['code']
        try:
            st = client.get_waveforms(network=network, station=station, location="*", channel="BH[ZNE]", starttime=starttime - 300,
                                      endtime=starttime + 300, attach_response=True)
            assert(len(st) == 3)
        except Exception:
            print(station, "---")
            continue

        st.simulate(paz_remove="self", paz_simulate=paz_wa, water_level=10)
        st.trim(t, t + 50)

        tr_n = st.select(component="N")[0]
        ampl_n = max(abs(tr_n.data))
        tr_e = st.select(component="E")[0]
        ampl_e = max(abs(tr_e.data))
        ampl = max(ampl_n, ampl_e)

        sta_lat = st[0].stats.coordinates.latitude
        sta_lon = st[0].stats.coordinates.longitude
        event_lat = trig['latitude']
        event_lon = trig['longitude']

        epi_dist, az, baz = gps2dist_azimuth(event_lat, event_lon, sta_lat,
                                             sta_lon)
        epi_dist = epi_dist / 1000

        if epi_dist < 60:
            a = 0.018
            b = 2.17
        else:
            a = 0.0038
            b = 3.02
        ml = log10(ampl * 1000) + a * epi_dist + b
        print(station, ml)
        mags.append(ml)

    net_mag = np.median(mags)
    print("Network magnitude:", net_mag)
```
and here is the error I get when running this code:

```(python)
Traceback (most recent call last):
  File "/home/seismo/.local/lib/python3.8/site-packages/obspy/core/util/attribdict.py", line 128, in __getattr__
    return self.__getitem__(name, default)
  File "/home/seismo/.local/lib/python3.8/site-packages/obspy/core/trace.py", line 235, in __getitem__
    return super(Stats, self).__getitem__(key, default)
  File "/home/seismo/.local/lib/python3.8/site-packages/obspy/core/util/attribdict.py", line 74, in __getitem__
    return self.__dict__[name]
KeyError: 'coordinates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "detect", line 38, in <module>
    trig['latitude'] = tr.stats.coordinates.latitude
  File "/home/seismo/.local/lib/python3.8/site-packages/obspy/core/util/attribdict.py", line 130, in __getattr__
    raise AttributeError(e.args[0])
AttributeError: coordinates
```
What can I do to fix this?
Any help would be appreciated.

**Comment by barsch** [comment]
You need to extract station coordinates from the results of the station web service (```client.get_stations(...))``` and not from the dataselect web service (```client.get_waveform(...)```).

Also consider not to query with ```network="*"``` - that is bad practice. In your case e.g. station ```POGA``` exists in multiple networks:
```
>>> inventory = client.get_stations(network=network, station=station,starttime=starttime,endtime=endtime)
>>> print(inventory)
Inventory created at 2021-03-05T09:06:48.000000Z
	Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.47
		    http://service.iris.edu/fdsnws/station/1/query?starttime=2017-04-03...
	Sending institution: IRIS-DMC (IRIS-DMC)
	Contains:
		Networks (2):
			AF, SY
		Stations (2):
			AF.POGA (Pongola, Kwazulu-Natal, South Africa)
			SY.POGA (POGA synthetic)
		Channels (0):
>>> inventory[0][0].latitude
-27.346
```

**Comment by Donavin97** [comment]
Hi there.
Thanks for your reply.
The reason I am using * as a network wildcard, is because I have stations spanning multiple networks.
How can I extract data across multiple networks?
Also, any solution to the trigger module error?

**Comment by barsch** [comment]
(1) the trigger module itself raises no error - its those lines:
```
trig['latitude'] = tr.stats.coordinates.latitude
trig['longitude'] = tr.stats.coordinates.longitude
```

-> ```tr.stats``` has no coordinates - waveform data (`Trace/Stream) does not include station coordinates - you have to use ```client.get_station``` as shown in the example above

(2) you can loop over e.g. a list of tuples:

```
NETSTA = [
 ('AF', 'POGA'),
 ('SY', 'POGA'),
]

for network, station in NETSTA:
  # do something
  print(network, station)
```

**Comment by Donavin97** [comment]
Hi there.
I once again thank you for your help.
note: I'm following this example:
https://docs.obspy.org/tutorial/advanced_exercise/advanced_exercise_solution_5.html

I am getting another error now:


1 events triggered.
################################################################################
Trigger time: 2017-04-03T03:11:34.569538Z
Traceback (most recent call last):
  File "detect", line 55, in <module>
    station = station['code']
  File "/home/seismo/.local/lib/python3.8/site-packages/obspy/core/inventory/network.py", line 146, in __getitem__
    return self.stations[index]
TypeError: list indices must be integers or slices, not str

Any thoughts?

**Comment by barsch** [comment]
that example you are following is a different web service: ArcLink - which is deprecated and partly shut down afaik

however, you should stick to your first code - and go from there - all you need is given above 

Hint (untested):
```
st = Stream()
for network, station in NETSTA:
    try:
        tr = client.get_waveforms(network=network, station=station, location="*", channel="BHZ", starttime=starttime, endtime=endtime, attach_response=True)
        inventory = client.get_stations(network=network, station=station, location="*", channel="BHZ", starttime=starttime, endtime=endtime)
        station = inventory[0][0]  # unsafe - could be multiple entries! we just take the first one
        tr.stats.coordinates = AttribDict({'latitude': station.latitude, 'longitude': station.longitude})
     except Exception:
        print(station, "---")
        continue
    st += tr
```

I won't program it for you nor do I introduce you to basic Python principles - as a seismologist I expect from you to figure it out by yourself ;)

**Comment by Donavin97** [comment]
Thanks for all the help, I'll close this now.
