### ISSUE TITLE
Time Data Error

### ISSUE THREAD

**Issue by JeldrikGaal** [obspy/obspy#2809]
-  ObsPy version 1.2.2 Python version 2.7 and Platform Linux
  -  How did you install ObsPy: pip

The _read_single_hypocenter function in io/nlloc/core.py has a problem with Parsing Dates from March and October.

``` python
File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/io/nlloc/core.py", line 179, in _read_single_hypocenter
    creation_time = UTCDateTime.strptime(date + time, str("%d%b%Y%Hh%Mm%S"))
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/utcdatetime.py", line 1349, in strptime
    return UTCDateTime(datetime.datetime.strptime(date_string, format))
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '11Oct202113h30m47' does not match format '%d%b%Y%Hh%Mm%S'
```
``` python
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/io/nlloc/core.py", line 179, in _read_single_hypocenter
    creation_time = UTCDateTime.strptime(date + time, str("%d%b%Y%Hh%Mm%S"))
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/utcdatetime.py", line 1349, in strptime
    return UTCDateTime(datetime.datetime.strptime(date_string, format))
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '10Mar202113h46m07' does not match format '%d%b%Y%Hh%Mm%S'
```

**Comment by ThomasLecocq** [comment]
what locale is your computer ? 

what does ``UTCDateTime(2021,3,10).strftime("%d%b%Y%Hh%Mm%S")`` give ?

**Comment by ThomasLecocq** [comment]
you can reproduce this ? it works correctly for me using the error given above:
```
In [1]: from obspy import UTCDateTime

In [2]: UTCDateTime().strptime("10Mar202113h46m07", "%d%b%Y%Hh%Mm%S")
Out[2]: 2021-03-10T13:46:07.000000Z

In [3]: import datetime

In [4]: datetime.datetime.strptime("10Mar202113h46m07", "%d%b%Y%Hh%Mm%S")
Out[4]: datetime.datetime(2021, 3, 10, 13, 46, 7)
```

**Comment by JeldrikGaal** [comment]
It does for me as well. 
```python
>>> from obspy import UTCDateTime
>>> UTCDateTime().strptime("10Mar202113h46m07", "%d%b%Y%Hh%Mm%S")
UTCDateTime(2021, 3, 10, 13, 46, 7)
>>> import datetime
>>> datetime.datetime.strptime("10Mar202113h46m07", "%d%b%Y%Hh%Mm%S")
datetime.datetime(2021, 3, 10, 13, 46, 7)
```

Here's the full traceback :
```python
Traceback (most recent call last):
  File "/home/jeldrik/pylot/./PyLoT.py", line 3033, in locate_event
    self.get_data().applyEVTData(lt.read_location(locpath), typ='event')
  File "/home/jeldrik/pylot/pylot/core/loc/nll.py", line 107, in read_location
    return read_events(fn)[0]
  File "<decorator-gen-46>", line 2, in read_events
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/event/catalog.py", line 812, in read_events
    return _generic_reader(pathname_or_url, _read, format=format, **kwargs)
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/util/base.py", line 702, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-47>", line 2, in _read
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/event/catalog.py", line 821, in _read
    **kwargs)
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/util/base.py", line 470, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/io/nlloc/core.py", line 129, in read_nlloc_hyp
    original_picks=original_picks)
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/io/nlloc/core.py", line 179, in _read_single_hypocenter
    creation_time = UTCDateTime.strptime(date + time, str("%d%b%Y%Hh%Mm%S"))
  File "/home/jeldrik/.local/lib/python2.7/site-packages/obspy/core/utcdatetime.py", line 1349, in strptime
    return UTCDateTime(datetime.datetime.strptime(date_string, format))
  File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '10Mar202114h19m52' does not match format '%d%b%Y%Hh%Mm%S'

```

**Comment by JeldrikGaal** [comment]
When changing my System Time to a Month other than March of October the error does not occur.

**Comment by trichter** [comment]
Maybe you can provide the file which is loaded in line 5 of the traceback.

**Comment by JeldrikGaal** [comment]
The problem actually was the locale LC_TIME being set to de_DE. The german words for march and october have different 3 Letter abbreviations than the english ones. The example worked in the shell because the locale is not being loaded there. 
I added a fix for myself by updating the locale to en_US.utf8

**Comment by trichter** [comment]
Does it mean, we can only read those files with English locale setting? Then I would consider this a bug and your fix a good work-around.

**Comment by JeldrikGaal** [comment]
It does look like the code only works with english LC_TIME settings.

**Comment by ThomasLecocq** [comment]
It is indeed a bug, reading I/O shouldn't be LOCALE specfic - so the I/O module should make sure this is checked!

**Comment by JeldrikGaal** [comment]
The closing was not intentional.

**Comment by ThomasLecocq** [comment]
no prob, it's best indeed to keep it open so we can link the PR bugfix to it !
