### ISSUE TITLE
Error when Routing Service returns code 204

### ISSUE THREAD

**Issue by javiquinte** [obspy/obspy#2847]
The Routing Service from EIDA can be queried to know where can you get (meta)data for a particular stream and timewindow.
In the case that the stream was not active in that time frame an HTTP code 204 is returned, following the style of FDSN services.

Error codes from the specification can be checked here
https://routing.readthedocs.io/en/latest/specification.html#abnormal-responses

Somehow, Obspy is crashing when this happens. It is weird, because we make heavy use of this and despite of that we never faced this problem.

The following is a minimalistic example showing this behavior:

```
>>> rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': '/Users/javier/.eidatoken'})
>>> bulk1=[('GE', 'APE', '*', '*H*', UTCDateTime(1990, 1, 1), UTCDateTime(1990, 1, 1, 0, 10, 0))]
>>> st = rsClient.get_waveforms_bulk(bulk1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-57>", line 2, in get_waveforms_bulk
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 82, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
  File "<decorator-gen-56>", line 2, in get_waveforms_bulk
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 89, in _assert_attach_response_not_in_kwargs
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/fdsn/routing/eidaws_routing_client.py", line 104, in get_waveforms_bulk
    inv = self.get_stations_bulk(_b, format="text",
  File "<decorator-gen-59>", line 2, in get_stations_bulk
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 82, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/fdsn/routing/eidaws_routing_client.py", line 179, in get_stations_bulk
    r = self._download(self._url + "/query", data=bulk_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/base.py", line 245, in _download
    self._handle_requests_http_error(r)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 307, in _handle_requests_http_error
    raise_on_error(r.status_code, buf)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/obspy/clients/fdsn/client.py", line 1722, in raise_on_error
    raise FDSNNoDataException("No data available for request.",
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
Detailed response of server:

No Content --
```

ObsPy version 1.2.2 (installed via pip)
Python 3.9 and 3.7
OSX 11.4 and 10.14.6

**Comment by petrrr** [comment]
This one is rather old.
Gived that we did not get to may EIDA feedback on this one, I could imagine it has been solved.

@javiquinte Does this problem still exist or can we close this one?

**Comment by javiquinte** [comment]
I tried with version 1.4.2 and the behavior is the same for all clients and all data centres, so I would not consider this a bug if no one else complained about this for 4 years.

```
>>> c = Client("IRIS")
>>> bulk1=[('IU', 'XXXX', '*', '*', UTCDateTime(1990, 1, 1), UTCDateTime(1990, 1, 1, 0, 10, 0))]
>>> st = c.get_waveforms_bulk(bulk1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/javier/.pyenv/versions/geofon12/lib/python3.12/site-packages/obspy/clients/fdsn/client.py", line 1051, in get_waveforms_bulk
    data_stream = self._download(
                  ^^^^^^^^^^^^^^^
  File "/home/javier/.pyenv/versions/geofon12/lib/python3.12/site-packages/obspy/clients/fdsn/client.py", line 1486, in _download
    raise_on_error(code, data)
  File "/home/javier/.pyenv/versions/geofon12/lib/python3.12/site-packages/obspy/clients/fdsn/client.py", line 1834, in raise_on_error
    raise FDSNNoDataException("No data available for request.",
obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
HTTP Status code: 204
Detailed response of server:

```

**Comment by megies** [comment]
I tried the query from above today and it raises a fine-grained exception (like stated before):

```
   1840 # No data.
   1841 if code == 204:
-> 1842     raise FDSNNoDataException("No data available for request.",
   1843                               server_info)
   1844 elif code == 400:
   1845     msg = ("Bad request. If you think your request was valid "
   1846            "please contact the developers.")
FDSNNoDataException: No data available for request.
HTTP Status code: 204
Detailed response of server:

No Content -- 
```

This can be caught and handled in user code as the "no data" scenario. I guess the other option would have been to return an empty stream, but having the exception provides more information and options to handle it fine-grained.

Unless I am missing something here..?
