### ISSUE TITLE
Obspy.io.mseed.utils.get_flags returns error but obspy.core.read does not

### ISSUE THREAD

**Issue by JoshRichW** [obspy/obspy#2880]
-Obspy 1.2.1, Python 3.7, Windows
- Anaconda installation

I am trying to extract the timing quality from a file (attached), and I noticed a strange behaviour.
If I try to use the obspy.io.mseed.utils.get_flags method, I get the following error:
`get_flags(filename)`
Traceback (most recent call last):
  File "DIRECTORY\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-5a15938a91f0>", line 1, in <module>
    get_flags(new_fname)
  File "DIRECTORY\lib\site-packages\obspy\io\mseed\util.py", line 482, in get_flags
    "min": tq.min(),
  File "DIRECTORY\lib\site-packages\numpy\core\_methods.py", line 34, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

I get the same error if I turn off everything but the timing quality:
`get_flags(filename, io_flags=False, activity_flags=False, data_quality_flags=False, timing_quality=True)`

But if I use the normal obspy.core.read method:
`st = read(filename, details=True)`
`st[0].stats.mseed.blkt1001`
`Out[38]: AttribDict({'timing_quality': 100})`

Then I get a timing quality value.

I'm confused as to why one method errors out whilst the other returns a value - they should both be accessing the same blockette 1001.
Am I missing something about some difference in how each of these functions work?

File:
https://github.com/JoshRichW/Test_files/blob/3bcb4c186691550af1e42edf33c9c9914e2a6bf9/test.mseed
Let me know if the file is not accessible.

**Comment by calum-chamberlain** [comment]
I don't know the fix for this one, but it looks like the underlying clib isn't able to read the header properly when called from `get_flags` for the miniseed file when calling [`msr_parse`](https://github.com/obspy/obspy/blob/576d781a693479ac96f601834e9365c13404c5b4/obspy/io/mseed/util.py#L247) - this returns a non-zero return code, which ends up causing the read loop to break.

@chad-iris might know more about the cause of this?

**Comment by ThomasLecocq** [comment]
``read(..., details=True)`` and ``get_flags`` don't use the same reading routine, the issue is probably there

**Comment by Jollyfant** [comment]
Indeed, `get_flags` uses a separate routine to read and aggregate header flags. The problem is here:

https://github.com/obspy/obspy/blob/9dd8ccc493ba6e0d70d26966246e5d7641c5a6d0/obspy/io/mseed/util.py#L243

It looks ahead for the next record up to a maximum of 8192 bytes. The record size of the mSEED you provided is double that at 16384, which I guess is not unusual for 250 Hz data. The routine is then calling clibmseed with half a record which of course returns an error. Right now a simply hacky fix is to bump this number, but its probably better to modify to read mSEED headers proper.

**Comment by JoshRichW** [comment]
Thanks for all the information! Sound like I have a choice to either use the `read(..., details=True)` method or to adjust the record size output by the instruments - both good options.

**Comment by Jollyfant** [comment]
For what it's worth, 16384 is absolutely a valid record size following the mSEED manual (any power of two is for that matter), and ideally ObsPy should support it. Record lengths of 4096 bytes are most common at all the big data centers though. Larger records make sense if storage space becomes a concern.
