### ISSUE TITLE
Issue with importing obspy

### ISSUE THREAD

**Issue by tianzeliu** [obspy/obspy#2948]
Hi There,
I just reinstalled obspy on my machine running OSX 11.6.1 but found that I was no longer able to import it in python. Here are the error messages:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/obspy/lib/python3.8/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'
```
I have tried it on both python 3.8.12 and 3.10.2, and the problem is the same. My obspy was installed via Anaconda and is Version 1.2.2. 

* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by d-chambers** [comment]
See this issue: #2912 - a new obspy release is coming to fix this. In the meantime you can downgrade to numpy 1.21.
