### ISSUE TITLE
Erorr when creating traveltime table by regional velocity model

### ISSUE THREAD

**Issue by yangshunCHN** [obspy/obspy#2974]
When I tried to create traveltime table by regional velocity model, I met with such erorr: 

Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/seismic_phase.py", line 1303, in _refine_arrival
    shoot = self.shoot_ray(degrees, new_estimate.ray_param)
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/seismic_phase.py", line 1338, in shoot_ray
    self.max_ray_param))
obspy.taup.helper_classes.SlownessModelError: Ray param 1354.268186 is outside range for this phase: min=0.000000 max=1353.347732

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "taup_tt.py", line 32, in <module>
    distance_in_degree=dist)
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/tau.py", line 653, in get_travel_times
    tt.run()
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/taup_time.py", line 39, in run
    self.calculate(self.degrees)
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/taup_time.py", line 97, in calculate
    self.calc_time(degrees)
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/taup_time.py", line 107, in calc_time
    self.arrivals += phase.calc_time(degrees)
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/seismic_phase.py", line 1034, in calc_time
    self._settings["max_recursion"]))
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/seismic_phase.py", line 1289, in refine_arrival
    tolerance, recursion_limit)
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/obspy/taup/seismic_phase.py", line 1327, in _refine_arrival
    'error should not occur.'), e)
  File "/opt/anaconda3/envs/tf_v2/lib/python3.6/site-packages/future/utils/__init__.py", line 403, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
RuntimeError: Please contact the developers. This error should not occur.

**Comment by JUNZHU-SEIS** [comment]
I met the same problem as yours with great arc=.84, source depth=20 km, southern California community velocity 1-D model

**Comment by ThomasLecocq** [comment]
is your 1D model extended down to the centre of the Earth?

**Comment by JUNZHU-SEIS** [comment]
> is your 1D model extended down to the centre of the Earth?

yes

**Comment by calum-chamberlain** [comment]
Can you provide code to replicate this error please so that we can try to find the source of this issue.

**Comment by johnrudge** [comment]
This may now be fixed in `master`. @yangshunCHN can you check?

**Comment by megies** [comment]
> This may now be fixed in `master`. @yangshunCHN can you check?

CC @JUNZHU-SEIS

**Comment by megies** [comment]
Closing for now, lacking feedback. Assuming this might be fixed
