### ISSUE TITLE
Error loading Obspy

### ISSUE THREAD

**Issue by SeismoFelix** [obspy/obspy#2982]
Python version: 3.8
Obspy version: 1.2.2

I needed to upgrade the Python version to 3.8 for using the MTUQ package, but I cannot load the Obspy library. I got an error related with numpy. 

```
(mtuq) bash-3.2$ python
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:33:09) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from obspy import read
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/Users/felix/opt/anaconda3/envs/mtuq/lib/python3.8/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'

```

**Comment by calum-chamberlain** [comment]
See issue #2959 and related issues. A new release of obspy is on its way that fixes this. In the meantime please downgrade numpy to 1.21.

**Comment by megies** [comment]
original ticket #2912
