### ISSUE TITLE
Can't import obspy

### ISSUE THREAD

**Issue by mlmarius** [obspy/obspy#2983]
Versions:
os: MacOS Monterey 12.1
python: 3.9.7
obspy: obspy==1.2.2

I installed obspy via pip

Getting the following error when trying to `import obspy`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/Users/liviu/Documents/Work/infp/helicorder/worker/venv/lib/python3.9/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'
```

**Comment by trichter** [comment]
See issue #2959 and related issues. A new release of obspy is on its way that fixes this. In the meantime please downgrade numpy to 1.21.

**Comment by megies** [comment]
original ticket #2912
