### ISSUE TITLE
AttributeError when importing obspy

### ISSUE THREAD

**Issue by SpacelySpaceSprockets** [obspy/obspy#2992]
Stuck before I could even start :-( 

Beginning with a fresh conda environment with python 3.8
```conda create -n my_env python=3.8```

I installed obspy into that environment from conda-forge
```(my_env)> conda install -c conda-forge obspy```

No problems with the installation
Now I get an AttributeError just trying to import obspy...

```
$ python
Python 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import obspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/home/spacely/miniconda3/envs/pyside/lib/python3.8/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'
```

**Comment by trichter** [comment]
Please see #2912. A temporary work-around is to downgrade numpy to 1.21.
