### ISSUE TITLE
seedlink manual tests not working

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#2997]
Some of seedlink's tests are marked as manual. I tried to run them within the branch from #2996, but they got stuck in a loop:

```
(workhorse) eule@kiste:~/dev/obspy$ python obspy/clients/seedlink/tests/test_slclient.py 
Complete INFO:
<?xml version="1.0"?>
<seedlink software="HMB SeedLink v0.1 (2018.351)" organization="GEOFON" started="2021/03/30 08:50:25.0617">
<capability name="dialup"/>
<capability name="multistation"/>
<capability name="window-extraction"/>
<capability name="info:id"/>
<capability name="info:capabilities"/>
<capability name="info:stations"/>
<capability name="info:streams"/>
</seedlink>
.SLClient: packet seqnum: 3102923: blockette type: 1000
SLClient: blockette contains a trace: 
G.FDFM.00.BHZ 2022-02-28T13:17:10.600000Z  dt:0.05  npts:240  sampletype:i  dataquality:D
SLClient: packet seqnum: 3102924: blockette type: 1000
SLClient: blockette contains a trace: 
G.FDFM.00.BHZ 2022-02-28T13:17:22.600000Z  dt:0.05  npts:239  sampletype:i  dataquality:D
SLClient: packet seqnum: 3102925: blockette type: 1000
SLClient: blockette contains a trace: 
G.FDFM.00.BHZ 2022-02-28T13:17:34.550000Z  dt:0.05  npts:227  sampletype:i  dataquality:D
SLClient: packet seqnum: 3171918: blockette type: 1000
SLClient: blockette contains a trace: 
G.FDFM.00.BHZ 2022-02-28T13:17:45.900000Z  dt:0.05  npts:241  sampletype:i  dataquality:D
SLClient: packet seqnum: 3171919: blockette type: 1000
SLClient: blockette contains a trace: 
G.FDFM.00.BHZ 2022-02-28T13:17:57.949998Z  dt:0.05  npts:247  sampletype:i  dataquality:D
SLClient: packet seqnum: 3171920: blockette type: 1000
SLClient: blockette contains a trace: 
G.FDFM.00.BHZ 2022-02-28T13:18:10.300000Z  dt:0.05  npts:251  sampletype:i  dataquality:D
SLClient: packet seqnum: 3254074: blockette type: 1000
SLClient: blockette contains a trace: 
G.SSB.00.BHZ 2022-02-28T13:17:48.350000Z  dt:0.05  npts:320  sampletype:i  dataquality:D
SLClient: packet seqnum: 3254075: blockette type: 1000
SLClient: blockette contains a trace: 
G.SSB.00.BHZ 2022-02-28T13:18:04.350000Z  dt:0.05  npts:318  sampletype:i  dataquality:D
SLClient: packet seqnum: 3254076: blockette type: 1000
SLClient: blockette contains a trace: 
G.SSB.00.BHZ 2022-02-28T13:18:20.250000Z  dt:0.05  npts:305  sampletype:i  dataquality:D
.SLClient: packet seqnum: 8722548: blockette type: 1000
SLClient: blockette contains a trace: 
GE.STU..BHZ 2022-02-28T13:17:36.345000Z  dt:0.05  npts:281  sampletype:i  dataquality:D
SLClient: packet seqnum: 8722563: blockette type: 1000
SLClient: blockette contains a trace: 
GE.STU..BHZ 2022-02-28T13:17:50.395000Z  dt:0.05  npts:275  sampletype:i  dataquality:D
SLClient: packet seqnum: 8722579: blockette type: 1000
SLClient: blockette contains a trace: 
GE.STU..BHZ 2022-02-28T13:18:04.145000Z  dt:0.05  npts:268  sampletype:i  dataquality:D
SLClient: packet seqnum: 8722594: blockette type: 1000
SLClient: blockette contains a trace: 
GE.STU..BHZ 2022-02-28T13:18:17.545000Z  dt:0.05  npts:286  sampletype:i  dataquality:D
socket read error: timed out, reconnecting in 30ss
response: DATA/FETCH/TIME command is not accepted
negotiation with remote SeedLink failed: 'no stations accepted'
response: DATA/FETCH/TIME command is not accepted
negotiation with remote SeedLink failed: 'no stations accepted'
response: DATA/FETCH/TIME command is not accepted
negotiation with remote SeedLink failed: 'no stations accepted'
response: DATA/FETCH/TIME command is not accepted
negotiation with remote SeedLink failed: 'no stations accepted'
response: DATA/FETCH/TIME command is not accepted
negotiation with remote SeedLink failed: 'no stations accepted'
response: DATA/FETCH/TIME command is not accepted
negotiation with remote SeedLink failed: 'no stations accepted'
^CTraceback (most recent call last):
  File "obspy/clients/seedlink/tests/test_slclient.py", line 59, in <module>
    unittest.main(defaultTest='suite')
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/eule/anaconda/envs/workhorse/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "obspy/clients/seedlink/tests/test_slclient.py", line 38, in test_time_window
    sl_client.run()
  File "/home/eule/dev/obspy/obspy/clients/seedlink/slclient.py", line 246, in run
    slpack = self.slconn.collect()
  File "/home/eule/dev/obspy/obspy/clients/seedlink/client/seedlinkconnection.py", line 811, in collect
    time.sleep(0.5)
KeyboardInterrupt
```

**Comment by megies** [comment]
I'll have a look

**Comment by megies** [comment]
```
~$ python ~/git/obspy/obspy/clients/seedlink/tests/test_slclient.py
Complete INFO:
<?xml version="1.0"?>
<seedlink software="HMB SeedLink v0.1 (2018.351)" organization="GEOFON" started="2021/03/30 08:50:25.0617">
<capability name="dialup"/>
<capability name="multistation"/>
<capability name="window-extraction"/>
<capability name="info:id"/>
<capability name="info:capabilities"/>
<capability name="info:stations"/>
<capability name="info:streams"/>
</seedlink>
.Complete INFO:
<?xml version="1.0" encoding="utf-8"?>
<seedlink software="SeedLink v3.1 (2018.078 RingServer) :: SLPROTO:3.1 CAP EXTREPLY NSWILDCARD BATCH WS:13" organization="IRIS DMC RTSERVE3 ADC1 Ring Server" started="2021-11-17 17:54:01" />
.Complete INFO:
<?xml version="1.0"?>
<seedlink software="HMB SeedLink v0.1 (2018.351)" organization="GEOFON" started="2021/03/30 08:50:25.0617">
<capability name="dialup"/>
<capability name="multistation"/>
<capability name="window-extraction"/>
<capability name="info:id"/>
<capability name="info:capabilities"/>
<capability name="info:stations"/>
<capability name="info:streams"/>
</seedlink>
.
----------------------------------------------------------------------
Ran 3 tests in 0.633s

OK
```

Hmmm.. i just ran them on python 3.10.2 and it seemed ok (i upped the verbosity manually)

**Comment by megies** [comment]
Ok, nevermind, the `INFOLEVEL` setting actually is what gets it stuck in that loop you saw, I guess some of the requests need a minimum info level set in the client. But yea, that client is real low-level, so it might not be that surprising..

**Comment by megies** [comment]
> So setting the INFOLEVEL in the tests is all which need to be done?

Yes, it looks like 2 of the test cases dont even receive the information they need because INFOLEVEL on the seedlink client is not set and then the request brings back insufficient info from the server (INFOLEVEL is pretty similar to `level=...` in FDSWS client actually)

I don't think that more than a dozen people even use the seedlink low level clients. That code base is quite hacky and translated literally from C i believe and is not in the best shape, tbh. We should not worry about it too much I think. People that really feel the need to use that low level stuff are probably good enough coders to get done whatever they need from there. I think it's good enough if the high-level basic Client that I put on top (basically non realtime mode, with individual finite requests) is what we should worry about most

**Comment by megies** [comment]
> I assume these tests have to be manually started to not send too much load to the servers?

I think the load on servers isn't any different from our other network tests. And I assume the big seedlink servers out there will have means implemented to block clients/people on excessive requests

**Comment by trichter** [comment]
@megies Thanks for the insights. Can we close this issue?

**Comment by megies** [comment]
I just had a last look at it, and actually I'm not sure if what I stated above is accurate even. 

In any case, `slclient.SLClient.packet_handler` is not meant to be actually used, but expected to be reimplemented by subclassed custom clients. There simply is no `return True` that would break the main loop looking for packets, and there's also no storing of the received waveforms in variables or anything. So, not sure if it's worth bothering more with this, I'll add a short comment in that "manual" test file and leave it at that.
I'm kinda happy if the "basic" high-level request client is tested and working.
