### ISSUE TITLE
numpy error when importing obspy

### ISSUE THREAD

**Issue by marcianito** [obspy/obspy#3007]
Dear all,

I just installed obspy and wanted to read a local file. This failed. As far as I know, I have everything up-to-date, I could not find any reference to this error in the net. Any help would be appreciated.

OS: Manjaro (linux)
python version: 3.10.2
obspy version: 1.2.2 (installed via pip)
numpy version 1.22.2

```
from obspy import read

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mreich/.local/lib/python3.10/site-packages/obspy/__init__.py", line 39, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/mreich/.local/lib/python3.10/site-packages/obspy/core/__init__.py", line 124, in <module>
    from obspy.core.utcdatetime import UTCDateTime  # NOQA
  File "/home/mreich/.local/lib/python3.10/site-packages/obspy/core/utcdatetime.py", line 27, in <module>
    from obspy.core.util.deprecation_helpers import ObsPyDeprecationWarning
  File "/home/mreich/.local/lib/python3.10/site-packages/obspy/core/util/__init__.py", line 27, in <module>
    from obspy.core.util.base import (ALL_MODULES, DEFAULT_MODULES,
  File "/home/mreich/.local/lib/python3.10/site-packages/obspy/core/util/base.py", line 36, in <module>
    from obspy.core.util.misc import to_int_or_zero, buffered_load_entry_point
  File "/home/mreich/.local/lib/python3.10/site-packages/obspy/core/util/misc.py", line 214, in <module>
    loadtxt(np.array([0]), ndmin=1)
  File "/usr/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1086, in loadtxt
    ncols = len(usecols or split_line(first_line))
  File "/usr/lib/python3.10/site-packages/numpy/lib/npyio.py", line 977, in split_line
    line = line.split(comment, 1)[0]
AttributeError: 'numpy.int64' object has no attribute 'split'
```

**Comment by megies** [comment]
original ticket #2912
