### ISSUE TITLE
Seg2 read error for NOTE keyword

### ISSUE THREAD

**Issue by HZeyen** [obspy/obspy#3174]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Hi, I am having problems reading seg2 files if the keyword 'NOTE' exists but has no contents behind :

Initial code (function "parse_free_form" near the end, around line 327 in file seg2.py:

```
       if key == 'NOTE':
            value = [cleanup_and_decode_string(line)
                     for line in value.split(self.line_terminator)
                     if line]
        else:
            value = cleanup_and_decode_string(value)
```
I suggest:
```
        if key == 'NOTE':
            try:
                value = [cleanup_and_decode_string(line)
                         for line in value.split(self.line_terminator)
                         if line]
            except:
                value = ''
        else:
            value = cleanup_and_decode_string(value)
```

[Rec_00001.zip](https://github.com/obspy/obspy/files/9765136/Rec_00001.zip)

### Code to Reproduce

```python
from obspy.io.seg2 import seg2
filename = "rec_00001.seg2"
st = seg2._read_seg2(filename)
```

### Error Traceback

```Python traceback
Traceback (most recent call last):

  File "C:\Users\Hermann\anaconda3\envs\pg\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\sources_2010\python_programs\obspy_error.py", line 13, in <module>
    st = seg2._read_seg2(filename)

  File "C:\Users\Hermann\anaconda3\envs\pg\lib\site-packages\obspy\io\seg2\seg2.py", line 364, in _read_seg2
    st = seg2.read_file(filename)

  File "C:\Users\Hermann\anaconda3\envs\pg\lib\site-packages\obspy\io\seg2\seg2.py", line 83, in read_file
    self.read_file_descriptor_block()

  File "C:\Users\Hermann\anaconda3\envs\pg\lib\site-packages\obspy\io\seg2\seg2.py", line 167, in read_file_descriptor_block
    self.parse_free_form(

  File "C:\Users\Hermann\anaconda3\envs\pg\lib\site-packages\obspy\io\seg2\seg2.py", line 329, in parse_free_form
    for line in value.split(self.line_terminator)

TypeError: must be str or None, not bytes
```

### ObsPy Version?

1.3.0

### Operating System?

Windows

### Python Version?

3.8.13

### Installation Method?

conda

**Comment by QuLogic** [comment]
Fixed by #3178.
