### ISSUE TITLE
module 'obspy' has no attribute 'core'

### ISSUE THREAD

**Issue by Razovsky** [obspy/obspy#3272]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Hello there, i have a strange issue while trying to read a instrument response file. 
Find below the code and the error message.
Thanks in advance for your help !
Everything worked fine until i added the "inv = read_inventory" line

### Code to Reproduce

```python
import os
 import obspy
 from obspy import read_inventory
 
 event="2020.092.221816"
 
 root=os.getcwd()
 seismicdatadir=root+"\\"+event+"\\seismicdata"
 temp=os.listdir(seismicdatadir)
 seismicdatafiles=[f for f in temp if f.endswith(".mseed")]
 inv = read_inventory(root+"\\stations.xml",format="STATIONXML")
 
 for file in seismicdatafiles:
     streams=obspy.read(seismicdatadir+"\\"+file) #stream
     for st in streams:
         if st.stats.npts>1:
             st.plot()
             tr=st
             tr.detrend('constant')
             tr.detrend('linear')
             tr.taper(0.05)
             tr.plot()
```

### Error Traceback

```Python traceback
runfile('D:/Documents/mercury/Travail/THESE/InvFormesDondes/mseed2DredgerSAC.py', wdir='D:/Documents/mercury/Travail/THESE/InvFormesDondes')
Traceback (most recent call last):

  File "<ipython-input-58-699e76ee5b8f>", line 1, in <module>
    runfile('D:/Documents/mercury/Travail/THESE/InvFormesDondes/mseed2DredgerSAC.py', wdir='D:/Documents/mercury/Travail/THESE/InvFormesDondes')

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Documents/mercury/Travail/THESE/InvFormesDondes/mseed2DredgerSAC.py", line 23, in <module>
    inv = read_inventory(root+"\\stations.xml",format="STATIONXML")

  File "<decorator-gen-177>", line 2, in read_inventory

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\core\util\decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\core\inventory\inventory.py", line 89, in read_inventory
    **kwargs)

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\core\util\base.py", line 701, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)

  File "<decorator-gen-178>", line 2, in _read

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\core\util\decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\core\inventory\inventory.py", line 98, in _read
    **kwargs)

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\core\util\base.py", line 469, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\io\stationxml\core.py", line 181, in _read_stationxml
    networks.append(_read_network(network, _ns))

  File "C:\Users\mercury\Anaconda3\envs\obspy37\lib\site-packages\obspy\io\stationxml\core.py", line 232, in _read_network
    network = obspy.core.inventory.Network(net_element.get("code"))

AttributeError: module 'obspy' has no attribute 'core'
```

### ObsPy Version?

1.2.1

### Operating System?

windows

### Python Version?

3.7.6

### Installation Method?

conda

**Comment by filefolder** [comment]
does it work if you do `inv = obspy.read_inventory(root+"\\stations.xml",format="STATIONXML")`  ?

just guessing but it smells like your installation got screwed up somewhere rather than this being a (extremely serious and unlikely to have slipped by for several years) bug

**Comment by Razovsky** [comment]
Hello, I found out that my stations.xml file was provoking this issue.
Changing to one xml per station fixed the problem, now everything works fine.
Should i delete this post ?
Thanks for your answer anyway

**Comment by filefolder** [comment]
that seems quite odd but glad it’s working now. I’ll just close the issue.
