### ISSUE TITLE
obspy.io.zmap.core Error: None type not handled

### ISSUE THREAD

**Issue by Andry92** [obspy/obspy#3290]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

Error when you want to convert a FDSN catalog in zmap format. If you request a large catalog, there may be NoneTypes in the Depth attribute. This case is not handled correctly

### Code to Reproduce

```python
from obspy.clients.fdsn.client import Client

client = Client("IRIS")

catalog = client.get_events(minlatitude=-40.0, maxlatitude=-15.0,
                            minlongitude=-78.0, maxlongitude=-66.0,
                            minmagnitude=6.0)

print(catalog)

catalog.write(filename="catalog_zmap2.txt", format="ZMAP", with_uncertainties=True)
```

### Error Traceback

```Python traceback
350 Event(s) in Catalog:
2023-03-30T17:33:06.366000Z | -35.663,  -73.540 | 6.3  mww
2023-03-22T16:00:31.218000Z | -23.480,  -66.511 | 6.5  mww
...
1960-01-13T15:40:24.000000Z | -16.020,  -73.020 | 7.1  None
1960-01-02T03:21:48.000000Z | -17.680,  -69.210 | 6.2  None
To see all events call 'print(CatalogObject.__str__(print_all=True))'
Traceback (most recent call last):
  File "/home/andrea/Documents/test_zmap/save_catalog_zmap_format.py", line 11, in <module>
    catalog.write(filename="catalog_zmap2.txt", format="ZMAP", with_uncertainties=True)
  File "/home/andrea/miniconda3/envs/obspy_env/lib/python3.11/site-packages/obspy/core/event/catalog.py", line 506, in write
    return write_format(self, filename, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/miniconda3/envs/obspy_env/lib/python3.11/site-packages/obspy/io/zmap/core.py", line 306, in _write_zmap
    Pickler(with_uncertainties).dump(catalog, filename)
  File "/home/andrea/miniconda3/envs/obspy_env/lib/python3.11/site-packages/obspy/io/zmap/core.py", line 53, in dump
    cat_string = self._serialize(catalog)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrea/miniconda3/envs/obspy_env/lib/python3.11/site-packages/obspy/io/zmap/core.py", line 141, in _serialize
    'depth': self._num2str(origin.depth / 1000.0),  # m to km
                           ~~~~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

### ObsPy Version?

1.4.0

### Operating System?

Ubuntu 22.04

### Python Version?

3.11.1

### Installation Method?

conda

**Comment by megies** [comment]
I don't really know zmap format, is there a way to express `None` or rather skip such events with a warning?

**Comment by SuwenJunliu** [comment]
I will try to provide more helpful information about this bug. The catalog return from iris might cause it.

I print the Origin infomation which caused bug here

```
Origin
           resource_id: ResourceIdentifier(id="smi:service.iris.edu/fdsnws/event/1/query?originid=3156893")
                  time: UTCDateTime(2002, 3, 28, 4, 56, 22, 570000)
             longitude: -68.305
              latitude: -21.663
         creation_info: CreationInfo(author='ISC')
```

The code is equivalent to acquiring by curl, and there is no depth label in the XML result.

```
curl http://service.iris.edu/fdsnws/event/1/query?eventid=1306873  
```

Here are the output of curl

```
<?xml version="1.0" encoding="UTF-8"?>
<q:quakeml xmlns:q="http://quakeml.org/xmlns/quakeml/1.2" xmlns:iris="http://service.iris.edu/fdsnws/event/1/" xmlns="http://quakeml.org/xmlns/bed/1.2" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://quakeml.org/schema/xsd http://quakeml.org/schema/xsd/QuakeML-1.2.xsd">
<eventParameters publicID="smi:service.iris.edu/fdsnws/event/1/query">
<event publicID="smi:service.iris.edu/fdsnws/event/1/query?eventid=1306873">
<type>earthquake</type>
<description xmlns:iris="http://service.iris.edu/fdsnws/event/1/" iris:FEcode="124">
<type>Flinn-Engdahl region</type>
<text>CHILE-BOLIVIA BORDER REGION</text>
</description><preferredMagnitudeID>smi:service.iris.edu/fdsnws/event/1/query?magnitudeid=16778594</preferredMagnitudeID>
<preferredOriginID>smi:service.iris.edu/fdsnws/event/1/query?originid=3156893</preferredOriginID>
<origin xmlns:iris="http://service.iris.edu/fdsnws/event/1/" publicID="smi:service.iris.edu/fdsnws/event/1/query?originid=3156893" iris:contributorOriginId="5628669" iris:contributor="ISC" iris:contributorEventId="3951419" iris:catalog="ISC">
<time>
<value>2002-03-28T04:56:22.570</value>
</time>
<creationInfo>
<author>ISC</author>
</creationInfo>
<latitude>
<value>-21.663</value>
</latitude>
<longitude>
<value>-68.305</value>
</longitude>
</origin>
<magnitude publicID="smi:service.iris.edu/fdsnws/event/1/query?magnitudeid=16778594">
<mag>
<value>6.5</value>
</mag>
<type>MW</type><creationInfo>
<author>HRVD</author>
</creationInfo>
</magnitude>
</event>
</eventParameters>
</q:quakeml>
```

So I think it is fine to skip it if the depth is not in the origin. The quick fix might be adding the following code:

```
if origin.depth is None:
    print("some waning messages here")
    continue
```

before strings.update around the line 141 of obspy/io/zmap/core.py

**Comment by megies** [comment]
So with the proposed changes in #3343 it would look like this, can somebody confirm that is OK? Note the `NaN`s at the end, and there is also one event with origin depth unset that ends up with a `NaN` in column 7.

```python
from obspy.clients.fdsn.client import Client
import io

client = Client("IRIS")

catalog = client.get_events(minlatitude=-40.0, maxlatitude=-15.0,
                            minlongitude=-78.0, maxlongitude=-66.0,
                            minmagnitude=6.0)

for e in catalog[::2]:
    for o in e.origins:
        o.depth = 123456

bio = io.BytesIO()
catalog.write(bio, format="ZMAP", with_uncertainties=True)
bio.seek(0)
print(bio.read().decode('ASCII'))
```

```
-70.426000	-38.185800	2023.540078370466	7	17	6.600000	186.000000	3	5	11.491	NaN	NaN	NaN
-73.496500	-35.666300	2023.243099585997	3	30	6.300000	26.000000	17	33	8.544	NaN	NaN	NaN
-66.501600	-23.412200	2023.221005666350	3	22	6.400000	228.000000	16	0	34.694	NaN	NaN	NaN
-73.675100	-37.465300	2022.866029231038	11	13	6.200000	18.000000	2	24	57.83	NaN	NaN	NaN
-73.766000	-37.551800	2022.866027430207	11	13	6.200000	20.682000	2	24	1.039	NaN	NaN	NaN
-70.339900	-21.928400	2022.570348298357	7	28	6.100000	54.000000	4	15	3.9370000000000003	NaN	NaN	NaN
-68.578900	-22.187600	2022.569290281139	7	27	6.200000	112.000000	18	58	58.306	NaN	NaN	NaN
-66.651900	-23.496000	2022.356062675609	5	10	6.800000	220.000000	23	6	32.538	NaN	NaN	NaN
...
-71.270000	-29.634000	2002.248857581494	4	1	6.300000	72.700000	19	59	32.69	NaN	NaN	NaN
-68.305000	-21.663000	2002.236180319952	3	28	6.500000	NaN	4	56	22.57	NaN	NaN	NaN
-69.245000	-19.518000	2001.559475169330	7	24	6.300000	33.000000	5	0	8.94	NaN	NaN	NaN
...
```

**Comment by megies** [comment]
see https://github.com/obspy/obspy/pull/3343#issuecomment-1702475792
