### ISSUE TITLE
read SAC error

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [obspy/obspy#3299]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

using
```
st = read('MA.y85.SHX', format='SAC')
```
I got
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 297, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/core/stream.py", line 208, in read
    st = _generic_reader(pathname_or_url, _read, **kwargs)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/core/util/base.py", line 658, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 208, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/core/stream.py", line 249, in _read
    stream, format = _read_from_plugin('waveform', filename, format=format,
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/core/util/base.py", line 423, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/io/sac/core.py", line 344, in _read_sac
    return _internal_read_sac(buf=fh, headonly=headonly,
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/io/sac/core.py", line 389, in _internal_read_sac
    sac = SACTrace.read(buf, headonly=headonly, ascii=False,
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/io/sac/sactrace.py", line 1086, in read
    hf, hi, hs, data = _io.read_sac(source, headonly=headonly,
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/io/sac/arrayio.py", line 134, in read_sac
    if not is_valid_byteorder(hi):
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/io/sac/arrayio.py", line 649, in is_valid_byteorder
    nvhdr = hi[HD.INTHDRS.index('nvhdr')]
IndexError: index 6 is out of bounds for axis 0 with size 0
```

### ObsPy Version?

1.4.0

### Installation Method?

None

**Comment by megies** [comment]
Are you able to share that data file that makes problems?

CC @jkmacc-LANL

**Comment by JUNZHU-SEIS** [comment]
Fixed now, thank you. The problem seems to be due to the SAC data have been attributed with invalid headers, not related to Obspy package.
