### ISSUE TITLE
FDSN: client service discovery (WADL requests) and other requests to EarthScope randomly failing sometimes

### ISSUE THREAD

**Issue by megies** [obspy/obspy#3465]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

**EDIT: this seems to document two different server side bugs. one in gzip compression injecting random bytes into the resulting gzipped payload making the data unreadable and a second omitting the `chunked` response header which also messes up the data response**

It seems, client requests (or rather connection/service discovery?) to EarthScope via our FDSN client randomly fail sometimes (e.g. [here](https://tests.obspy.org/140213/#2 and also as mentioned on [EarthScope mailing list](http://ds.iris.edu/message-center/thread/9521/)).
From first local testing, it seems it might exclusively happen during service discovery (i.e. requesting the three wadl files and also catalogs+contributors) during client initialization, which we do threaded for all services in parallel.

I have chased this down and I have documented a case in which the server returns a payload which seems to be a garbled gzip payload, claiming in the headers of the request response that the content is xml, encoded with gzip.

We do tell the server via request headers that we are fine with gzip encoded response payloads and in the WADL cases we always get gzip in return, while for shorter responses like "catalogs" info, we get a plain text reply.

Requested URL:
http://service.iris.edu/fdsnws/station/1/application.wadl

Response headers:
```
Access-Control-Allow-Origin: *                                                  
Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
Vary: origin,access-control-request-method,access-control-request-headers,accept-encoding
X-Content-Type-Options: nosniff                                                 
X-XSS-Protection: 1; mode=block                                                 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate                   
Pragma: no-cache                                                                
Expires: 0                                                                      
X-Frame-Options: DENY                                                           
Content-Encoding: gzip                                                             
Content-Type: application/xml                                                      
Date: Wed, 29 May 2024 13:55:30 GMT                                                
Date: Wed, 29 May 2024 13:55:30 GMT                                                
Connection: close                                                                  
```

<details open>
<summary>Response payload</summary>

```
b'a\r\n\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\r\n200\r\n\xccZ[o\xdb6\x14~\xee\x80\xfd\x07N\x8fAl\xd9^\x1fZ\xcfn\xd0K\xba\x06H\xd2\xadv\x81a/\x03-\x1d[\xdc(R#)_\xfe}\x0f)\xc9\x96\x13\xcb\x8ej\xd9\x8d\x11 \x10/\x87\xe7\xfb\xbe\xc3;\x07W\xcb\x98\x939(\xcd\xa4\x18z\xddv\xc7# \x02\x1921\x1bz_\xc7\x1f[\xaf<\xa2\r\x15!\xe5R\xc0\xd0[\x81\xf6\xae\xde\xfc\xfc\xd3\x80&\tg\x015X\x8f\xa0\r\xa1\x87^dL\xd2\xf7\xfd\x05\ry;\x84y\xfb_:\xa7m\x01\xc6\xefu:\xaf\xfdN\xcf\xc3z\x04\x7f\x83P\x06\xc40\xc3\xd1\xde\xc7\x0f\xa3{\xdb\x80\xb3\xb3\x80\t\xd1\xa0\xe6,\x00b]\xf1\x8b\n3E\xe3\x98*\xbdNP\xa0e\xaa\x02\xd0dB5\xac\x9b\xce+\xb7\x99b\xba\ra\xeaOC-\x16\xda\xcf\x1b\xf0\xbb~\xe1\xc3\x96\x15\x92P\x13\r\xbd\xadLW \x06\x13\xc9\x90\x08\x1ac\x1b\xbf_\x8f=\xc2\xc2\xa1\xa7\xa44\x0f\x8b\x16\xf6\x12)4\xec\xc8\xcb\xf3\x13,\x02"\x87\x1bC\xc8\xe8x\x95\xa0m\x03K\xe3G&\xe6k\xcc[\x15\xfd\n\xcb\x03?\xf3\xf0a\xf2\x03`\xff\xa7\xa0V;=\xde\r\xf0q\xf9\x17/r\xbb\x98\xa5\xcd\xe3\x1c\xccK(\x8a\x94[B\xbe\x951,\x06\x1b<+\xabsf\x92\x18\x87v\xa9\xfb!5\xb0\xcb\xa3\x8dk6H0\xb0\xfa\x9c\xdaP\x041\xe3LG^\x117\x9c\xc5\xcc\x10#I\x10Q!\x80kb"j\x08U@h`\xd8\x1c\x08\x12,\x15\xa1S\x03\n\xf3\x80\xe8\x04\x026e\x10\x12\xe7\x1dq\xee\xed\xf3\x80\x90\xeb%\x8d\x13\x0e\xbaO\xd6\x80\x86\xbdN\xb7\xd7\xeav[\xbd\xd7\xd6\xfc\xe6k\xdc\xe9\xf4\xdd_Er\xbb\xd3\xe9T76\xf0\x11n\x953\x03\xdfq{\x90u\x10\xe1\xb3\xe0|\x02S\x89i\xdb\xa4\xa3s\xf5(\xcf\xd1<g\xc2]TdhOOz>\x86\xe9,\x16q|\xde\xcds\xfd\xb0\xce\xcc<{\x9e]O\xfe\x114\xef\x1aB\xea\xb3\xec\xac<g\x92\xb1\r\n200\r\n\xbf\x9d=\x94\xb1\xcdf\x02y\xed\xfc3g\xf8\xdcA\x9c\x13|t\x08\x17\xae?gzq\xa5\xb9\x90\xea\xbfJv\xb5Q\xc8\xc5>\xc8\x07\xe8\x1d\x01\x87\xc0\xe0$\x07\x16dlC6o\xd3~\xcf\x992)\xe5\xeb$\\D\x83n\x93[\xa6\x8d&\xb8\x80&\x0b\xc6\xc3\x80\xaaP\xe73f\x00\x89\x81\xf0\xa9\x12\xe4f\x877_mc\x9b\xaf\xcb\x9b\x9b\xad\x84\xab\xf2\xd7?o\xbf\xbc\x1f\xdf\xbc?\xfd\xf0l\xa3\xed\xac\xc4\x8f\xae\xaf?\xac\xf7\r\rS]\xd8\x1d\xbe\xbd\xbf\xfbl[,\x7f_\xbe\xbd\x1fo\'^\x94\xbf\xae\xee\xef\xae\xf6\xb6r/\r\xf4\xc9\x1d]\x11!\rI5\x94\x9c]D \x08\x879\xf0a\xb1\xe0?\xb1t\\\x06?H\xbb\xa2\xe5B\xbc\xaf\xc8D\xabE\xa6\x96\xcb\x84\x06\x8d\xeaY\xb45\xc4\x06\xd0\xfe\xfa\xf3\xaa\xb3\xf5\xd9j]vO=H\xe5K\xe7\xf3\xf3\x9d7\xdcl_\xe9\xe7V\x87\xef>\xfdm\x9b\xdb|v/\xdf}\xea\x95\x93.\x1e\x14\xd8\xd3K\x1a!:f\x82\xa3\xac&\r\xf7,hd:\xe1\x98\x1d\xc2\x94\xa6\xdc\x0c\xbd\xd6k\x9c\xa8\x8e!\xdf\xcd\xae+\x82\xbbo\x9cl\x95 \x13\x99\xe2\xcc\xa9VY\\\x03UA\xb4s\x87_\x0f\x1a]\xd6\x87v\x08\xd9S\xa1\t\xa9\xbe\x03Z-\xd9\xa4\x98\xd5\xd5\xad\xfb\xaa\x19\xe1\x16\xa0\xcd\t\xc1\xa1p\xf5\xc15\x85\r\xe8w`{\xf2DR; \x9b\x01e\xd7\xb4\x01\x08\xa3p\xe5U\xf8@\x12\xc9\x84q\xf0(Q4d\x98\xd7\x18\xce\xfa\xfa\x9d\x00h\xe1\xc4)\x91bO\xb4\x16S}n\xa4\xd8KX\x9c\xc6$d\xf6\xe09\x002U2v\xf8g g\x8a&\x11\x0br\xe0\xd82\x13\xb8\x97\x99\xac6\xe2\xdb9m\xa3R\x13\x83m]\x1a\x9a\xea\xb0\xa8\xc03"\xc2\xadK\x0f\xad[6$\x14\x9b\x82f"\xdf5N\xe4\x14\xed\x1b\xcaxv\xf0\xc84Q`R\x85\xc0\xf7\x0c\xceYS2q\x8b\xcd9\xe5ii\xabX\xafV\x01\xa9^\xadb\xc5W\xafV\r\n200\r\n\xb1\xfe\xaf\xa1[Y\xc0\xacDY>&\x02\x8eq\x80vQ\xa9\xc0\xae\xf0\xaa\xa4\x9cH\xc9\x81\x8a\x92\x96F\xa5{\x8f\n\x0e\x08Y/\xf6vyM\xe7(:\x9d0\xce\xcc\xaa\x86\xdfS\xca\xf51\x8e\x17\x11\xc8\xa6\x18h\x1aMj\xa2#\x99\xf2\x90\xe4~\xe1\x7f\x1c{\xe3l#Cqb\xcd\xae\x15\xec%\x16\x03MBj()\xfb\xde>\xbe\x1b\xa6\x89=%:\xf2 \xe9\x00\xee\xdb\xe2\x1c)\xc6\xde\xe6@\xe4\xad\xe6\x07I\x9bC$\x9b\xfa[\x9e\x9bm \\q;Qm\xca\x05\xb5P\x97\x7fU\xb5~i\xb5*\xc1}t\x82\\\xe2\x16\xdb\x04\xd1\x18\xd5\x1891.\xddxx/3M\xecN\x87sr\xa3p\x0c\x81\xa5\x01\xa1\xddq\x19B\xb6\xa3\x8d\xd3\x94\x93\xecn2\xc7\xe04\xaeh\xb4\xd5\xaa\x0b`{\x86AGm\xd8dQ\xf3\x03\xe2\xdb\x8d\xa6\x16x)Vm\xfcr\x9cSP\\\xdc"\x9a\xa8\xc8\xe3\x99\xc4m2\x8e\x90;f\xf7\x90\xe4\xe6\xcb\xcdhCc\xc1\xe2c\xfa\xbe;\x0e\xb6\xf8\xcaz\xdc\xd3g"\xc4\xdf\x00G\xd8\xb7\x93\xd4d\xa1a\x1aFO\x1e\r\xff\xd6\xe7\xf2\xfdp\xe9\xb6\xdd_V\xdc\x12W\x98\xb2W\xcb\xde\xa3\xbb\xe6\x84Sv\xb4\x1e\xee\xde\xbf\xbf,]\xfd/\x16\xed\xc5\xafm\xa9f\xf6\xce\xbf\xeb\xffuw;\n"\x88\xa9W\x9c\xd1\xba\xfeW\xa9\x1d.eJ\xc2\xf5:/\x9b\xd8\xd2\xe1*)"\x9f\xc6w\xb7d\x84\x13x\xaa\xdd\x11Hy\xf1\x90\x9d\xbb\t\x99\x8d]\x981\xb5;\xa4\x93kl\xe1\xd5(\xfer_\xf1\xca\xd9\xc3>\x1dxtg_\xaaw\xe0\xc9\xc2\xc17\x0b\x87\xe2\xa8\xba\xfa\xd3B\xba\xf2\xe9\x03\xa9|\xfd@\x1e\xbek\xf8\xe3\xf3(\x7f\xd8\x90Hm\xfe\xacz\x0c\x91\xfb\xbb\x87\xad\xfd\x80.\xfc\x8bJ"\x0e\xc8pX\x87c\x858^\x89\xfdZT>E\xf1\x8b\xb7(\x07\xde\xa8\xe4o\x90j\xbcR\xd9S\xe3\x1c\x94\x9e\x94\x8d\x92$m\xfb\x9e\xaa\x06-O\xa9z4?g\x0f\x99\r\n11\r\nG\x89\x9b\x04\x8d)\x03\xbf\xe4\xd1\x9bo\x00\x00\x00\xff\xff\r\na\r\n\x03\x00\xc7i1\x9b\xd6&\x00\x00\r\n0\r\n\r\n'
```

</details>

Note that close to the start of the payload there are the magic bytes which indicate a gzip file `b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00'` but lead by `'a'` and a windows type linebreak `'\r\n'`. I tried to crop at start/end to see if a valid gzip file is hidden in there but could not find an ending `\x00\x00` in there that made it a valid file (which seems to end all gzip files i briefly looked up).

I noted that the response header of all the "good" responses for the same URL had an additional header in the response:

```
Transfer-Encoding: chunked                                                      
```

Here's a diff I used for logging, since debugging into the threaded WADL downloads is painful:

```diff
diff --git a/obspy/clients/fdsn/client.py b/obspy/clients/fdsn/client.py
index b0836c5bb..112ea891e 100644
--- a/obspy/clients/fdsn/client.py
+++ b/obspy/clients/fdsn/client.py
@@ -1956,7 +1956,9 @@ def download_url(url, opener, timeout=10, headers={}, debug=False,
     code = url_obj.getcode()
 
     # Unpack gzip if necessary.
+    _gzip = False
     if url_obj.info().get("Content-Encoding") == "gzip":
+        _gzip = True
         if debug is True:
             print("Uncompressing gzipped response for %s" % url)
         # Cannot directly stream to gzip from urllib!
@@ -1969,6 +1971,10 @@ def download_url(url, opener, timeout=10, headers={}, debug=False,
             raise HTTPException(msg)
         buf = io.BytesIO(reader)
         buf.seek(0, 0)
+        _xxx = buf.read()
+        buf.seek(0, 0)
+        with open(f'/tmp/iris/{UTCDateTime().ns:d}.txt', 'wt') as fh:
+            fh.write('\n'.join(('GZIP', url, str(url_obj.info()), repr(_xxx))))
         f = gzip.GzipFile(fileobj=buf)
     else:
         f = url_obj
@@ -1978,6 +1984,11 @@ def download_url(url, opener, timeout=10, headers={}, debug=False,
     else:
         data = f.read()
 
+    if not _gzip:
+        # print('NO GZIP', url, url_obj.info(), data, end='\n')
+        with open(f'/tmp/iris/{UTCDateTime().ns:d}.txt', 'wt') as fh:
+            fh.write('\n'.join(('NO GZIP', url, str(url_obj.info()), repr(data))))
+
     if debug is True:
         print("Downloaded %s with HTTP code: %i" % (url, code))
```

### Code to Reproduce

```python
import time
from obspy.clients.fdsn import Client

while True:
    client = Client()
    # prevent reusing cached services in the loop
    Client._Client__service_discovery_cache = {}
    time.sleep(2)
```

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "/tmp/iris_issue.py", line 5, in <module>
    client = Client()
  File "/home/megies/git/obspy/obspy/clients/fdsn/client.py", line 284, in __init__
    self._discover_services()
  File "/home/megies/git/obspy/obspy/clients/fdsn/client.py", line 1591, in _discover_services
    decoded_wadl = wadl.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 4: invalid start byte
```

### ObsPy Version?

current master

### Operating System?

Debian

### Python Version?

3.10.5

### Installation Method?

developer installation / from source / git checkout

**Comment by megies** [comment]
CC @crotwell I tried to mail to that Earthscope mailing list but my sender mail address changed and my mails didn't go through, I contacted the person sending the original post though

**Comment by megies** [comment]
So, actually the problem also occurs outside of (threaded) service discovery in regular requests. At this point, I think this is a server side issue. Last thing to try is reproduce based on curl or something similar..

```python
import time
from obspy.clients.fdsn import Client

while True:
    client = Client(_discover_services=False)
    client.get_stations(network='IU', station='ANMO')
    time.sleep(2)
```

With these changes to create some dev output:

```diff
diff --git a/obspy/clients/fdsn/client.py b/obspy/clients/fdsn/client.py
index b0836c5bb..4e0b347fa 100644
--- a/obspy/clients/fdsn/client.py
+++ b/obspy/clients/fdsn/client.py
@@ -1956,7 +1956,9 @@ def download_url(url, opener, timeout=10, headers={}, debug=False,
     code = url_obj.getcode()
 
     # Unpack gzip if necessary.
+    _gzip = False
     if url_obj.info().get("Content-Encoding") == "gzip":
+        _gzip = True
         if debug is True:
             print("Uncompressing gzipped response for %s" % url)
         # Cannot directly stream to gzip from urllib!
@@ -1969,6 +1971,10 @@ def download_url(url, opener, timeout=10, headers={}, debug=False,
             raise HTTPException(msg)
         buf = io.BytesIO(reader)
         buf.seek(0, 0)
+        _xxx = buf.read()
+        buf.seek(0, 0)
+        with open(f'/tmp/iris/{UTCDateTime().ns:d}.txt', 'wt') as fh:
+            fh.write('\n'.join(('GZIP', url, str(url_obj.info()), repr(_xxx))))
         f = gzip.GzipFile(fileobj=buf)
     else:
         f = url_obj
@@ -1978,6 +1984,15 @@ def download_url(url, opener, timeout=10, headers={}, debug=False,
     else:
         data = f.read()
 
+    if not _gzip:
+        # print('NO GZIP', url, url_obj.info(), data, end='\n')
+        info = repr(data)
+        if isinstance(data, io.BytesIO):
+            info = data.read()
+            data.seek(0)
+        with open(f'/tmp/iris/{UTCDateTime().ns:d}.txt', 'wt') as fh:
+            fh.write('\n'.join(('NO GZIP', url, str(url_obj.info()), repr(info))))
+
     if debug is True:
         print("Downloaded %s with HTTP code: %i" % (url, code))
```

Many requests succeed but sometimes a random fail occurs, basically because of the server sending a response with (this time valid) gzip, but the response header missing to tell it's gzipped:

```
NO GZIP                                                                         
http://service.iris.edu/fdsnws/station/1/query?network=IU&station=ANMO          
Access-Control-Allow-Origin: *                                                  
Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
Vary: origin,access-control-request-method,access-control-request-headers,accept-encoding
Content-Disposition: inline; filename=fdsn-station_2024-05-29T17:24:23.6110.xml 
X-Content-Type-Options: nosniff                                                 
X-XSS-Protection: 1; mode=block                                                 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate                   
Pragma: no-cache                                                                
Expires: 0                                                                      
X-Frame-Options: DENY                                                           
Transfer-Encoding: chunked                                                      
Content-Type: application/xml                                                   
Transfer-Encoding: chunked                                                      
Date: Wed, 29 May 2024 17:24:23 GMT                                             
Connection: close                                                               
                                                                                
                                                                                
b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\xdd\x96]o\xa3F\x14\x86\xef\xf3+F\\T]\xc90\x0c\xb6cC1\x11\xc6\xac\x8bd\xe3\x8a\x81\xdd\xdeY\x04f\x13T\x0c^\xc0qV\xea\x8f\xef\x19\x06\xc7\x1f\xbbQ\\\xb5\xbb\x95ja0s\xdesfx\xcf3\xc8\xe6\xdd\xf3&GO\xac\xaa\xb3\xb2\x98HDQ%\xc4\x8a\xa4L\xb3\xe2a"yt%\x8f\xc7C]&\xd2\x9dus\x83\xcc\xf73\xea\xd3&n@\xfc\xfbr\x81 \xb7\xa8\'\xd2c\xd3l\r\x8c\xf7\xfb\xbd\xf2)\xad\x0b\xa5\xac\x1e0\x84p-\x94\x98HBi<\xd7\xd9\x99z\xdfo\xb5\x9a\xaa\x12\x0c\xf5h\xf2\xc86\xb1\x9c\x15\x90X$\xec\x90\x95U\xd95\x93`\xae\x83\x9c:3\xea\xb6\xd0\xa2L\xda\xd0\x15\xb9\xe8-\x05\x1f\x94\xbb\x1b\x99(Dy\xaeS\t\x89y>\x1c\xdd#\x92u\x83\x90I\xcb]\x950\xcb\x0b<*\xcf\x96\x8e\x89\xbb\x816\xc6\x8a\x94U\xa711\xc0c\xcb2\xdd\xe5"\x0f}t\xa7\x88\xba\xc1\x07\xcfq\r\xc4\xa7\xdf\xd7\x87\x05\xa0?\x0f\x1d3\x10_\xcbP3q\x97z\xac\x12\x05\x9e\xd5=U\xcd\xaa\xa7,a\n7Ha\xe9\x0e\x8br\'\xd6}\xde\xb1\xea\xcb]\xc1\x9a}Y\xfd1\xf1\xa2\x9f\xe2\xcd\xf6\x97.<\xb1\xfd\xe5\xea0\x01\xaf\xca\xe7p*\x167,\xb54U\x1b\xc8\xeaP\xd6\xf4\x90\x8c\x0cm`h}\xe5\x96\x90\x91\x89\x0f\n\xae\xf6Ea\x04\\1\xa0*\x02\xe7\x9a\xb8jf \x00\xd7\xf4\xf1XV\t\x1c\xa1\xaa\x1a\xed\xa1\xa8\xf0\x91P\xc5\xea\xa6\xca\x12\xa8\xc2\x99\xdb\x01\x04\xe5\x96\x15\xad\xc5\xc8\x9c\xb1:\xa9\xb2-_\xa15\xcf\xcb\xfb8G\x94e\xf5\xa6|\xa8\xe2\xed#:L)#\xee&\x8e\xe8\x9c\xa2\x9f\xe7\xd4\x7fg\xe2\xd3\xcc\xb6\x94\x97\xb2\xa2\xc9>e\xacB\xcd\x97-,i\xb6\xf2$\x8b\xa8\xcaH\'\x03L}\xecE\xad\x0e\x1f\x85"1,\x9b8\xf7w\x9b{Vu\xbb\xa2\xb6\x8866\xf1\xb7\x02m\x06e9\xe3\x0ft\x11\xebs\x0c\xbe\x19\x11Y]\xdf\x85\x7f\xbc\x1f\x97\x0e\xea\xb2:\xe6M\xb8p\x10\xd0\x12\x12\xd8b\xaaL\xe0\x80>\xdd^c2\xe2\xb0\x18q\xde\xb0\xaa\x80\n\x9d\x9d\x0e,\x00\x14\x8a\xe3F\xd4\x97\x9d\x95\x1f\x06\xde\xb4\xb7\xe6\xaf\x05q\x96\xed\xc5\xa2\xb7\x9e\xf3[8\xc9\xd3`e\xcf\xa6\xb6?\xeb\xad\x03\xd7^\x84\xde\xd2\xed)\xa1K\xc3\x9e\x12\xf9\x01\\\x03\xcf\t\xdd\x99h\xe9yO\xdbf\x9d6\xcf\x8b\xde\xa1\xb8H\x91\xedS\xfau\x13\x91\xb9\x00\x8f\x9a]\xca\xac\xfe@\xd1\x07C\xdd\xc4/#\x9d\xa0,\x1e\xc4=8q\xab\x0c\x86#\xd87\xc7A!rs\xf6\xd4\x9am\x91\xf1\x10<2\xf1qD(h\xd6tb\x00;\xde0\xcb\xce\xefw|\x03\xc1\xb7\x07\xdc\xed\xd1\x92=gI\xd9C\x11\xb5M\xdcJD&>\xa6\x8a\r\x04Ey{\xac\xd7\x1a\xd8\xed\xa2\x83Ld\x9e\xb0\xe5<\xc6E\xc1\xf2\xda\xd2t\xf5\x0c\xba\x97@\xb7\xe43\xb6^\x82\xea%ugi\x10l\x8e\xcf\xfd\x16\x83\xaf\x03v\xca\xa0&\x13\xc2%\x1a1\xd4\xd1\xff\x9d\xc1\xa1\xaa\xbd\xc9\xe0\xad\xfa\x06\x83}\xfd\x071\xf8Z\x03\xaffp4\xfa\xef\x11\xfc\x17\xf9Z\xf3\x1e\xcbS \xcb\xb1\x010Wv?R\xf8\xcd\xa1\xeb]\xb0\xa7\xb8v\x10\xfeJ\x9d\xd5o\xeeW\x1c*\xf3\xc0\x9d\xff}\x1a{\xeb\x88\n\x8e\xe1\x1a\xb8\xef\xdbkh\x7f\x97\x17%\xf9\xe7oJ\xedG\xbd)_\xeb\xf1\xd5\x94\xf6\x87\x83\xef\x8b)<\x87\xe0\x08nL|\xfe\x87\xd9\xfa\x0b\xd1\xee\xce\x9bo\x0b\x00\x00'
```

This misses the `Content-Encoding: gzip` header in response

**Comment by megies** [comment]
Confirmed to be a server side issue by EarthScope

**Comment by andres-h** [comment]
> lead by 'a' and a windows type linebreak '\r\n'

This probably indicates a missing "Transfer-Encoding: chunked" header.

**Comment by megies** [comment]
User-land workaround without hacking into installed obspy:

```python
from obspy.clients.fdsn import Client


# workaround 1
class NoGzipClient(Client):
    def _download(self, *args, **kwargs):
        kwargs['use_gzip'] = False
        return super(NoGzipClient, self)._download(*args, **kwargs)


# workaround 2
client = NoGzipClient(_discover_services=False)
client.get_stations(network='IU', station='ANMO')
client.get_whatever()
```

This has two parts:

1. gzip issue

Users can avoid the gzip issue by subclassing in their code to avoid gzip

2. "chunk" issue

Users can not easily avoid accepting gzip during our service discovery, you'd have to copy the whole `Client._discover_services()` code to the subclass and call `download_url()` without gzip. If even the chunk issue is connected to the gzip issue?
Anyway, it's possible to skip service discovery entirely with `_discover_services=False` with the only drawback being that any parameters beyond the default FDSN official service definition not being usable after that.

---

I had this running for testing for 10-20 minutes now and no problems:

```python
import time
from obspy.clients.fdsn import Client


# workaround 1
class NoGzipClient(Client):
    def _download(self, *args, **kwargs):
        kwargs['use_gzip'] = False
        return super(NoGzipClient, self)._download(*args, **kwargs)


while True:
    # workaround 2
    client = NoGzipClient(_discover_services=False)
    client.get_stations(network='IU', station='ANMO')
    time.sleep(2)
```

**Comment by crotwell** [comment]
FYI, was able to reproduce this with java, so not a obspy problem.

**Comment by megies** [comment]
For next release we could force no-gzip if FDSN client goes to an former-IRIS URL or at least we could maybe make it easier to opt-out of gzip if EarthScope can't fix it upstream

@chad-earthscope  (anybody else better suited to ping for this?)

> FYI, was able to reproduce this with java, so not a obspy problem.

Saw your mail, thanks :heart:
Can't post to the old IRIS ML since our mail sender addresses have changed and I couldn't figure out how to update it with the two logins now even (old IRIS vs new Earthscope)

**Comment by chad-earthscope** [comment]
Thanks all, we've discussed this internally and will be looking into the issue.

@rcasey-earthscope

**Comment by megies** [comment]
Are you working on this right now @rcasey-earthscope @chad-earthscope? Since some basic dataselect requests are failing now too..

http://service.iris.edu/fdsnws/dataselect/1/query?starttime=2010-02-27T06%3A45%3A00.000000&endtime=2010-02-27T07%3A45%3A00.000000&network=IU&station=ANMO&location=00&channel=LHZ

"Error 500: Error calling internal metadata service, code 404"

**Comment by chad-earthscope** [comment]
I believe this was an unrelated glitch.

**Comment by rcasey-earthscope** [comment]
We had some unexpected spike in traffic.  Unsure of the source.  IT is looking into it.  The services have since been recovered.

	-Rob

**Comment by rcasey-earthscope** [comment]
Requesting a review of this issue.  Have the server-side changes on the FDSN services addressed the malformed responses or is there still an issue that needs to be addressed?

**Comment by megies** [comment]
I'm assuming you are referring to one of the original permanent random fail issues?
 - "chunked" header omitted
 - malformed gzip reply

Did those get worked on server side?

**Comment by rcasey-earthscope** [comment]
Hi Tobias.   Yes, we modified the behavior of the Station service to **not apply compression** to returns.  We have had internal and external testers that have verified this solves their issue.  

I have conducted another load-level test (20 x 1000) applying your test Python script above (just attempting to connect) and I have not encountered a malformed return response, but there was a single case of failing to make a connection to the service endpoint.

If you have time, please perform a validation test that you are not seeing the random fail issues described in this ticket.  It will be good to get confirmation that we can close this.

Thank you for all of your help!

**Comment by megies** [comment]
@rcasey-earthscope seems good to me, ran the client initialization above more than 2000 times in a loop without problems
