### ISSUE TITLE
obspy.clients.fdsn.header.FDSNException: Unknown HTTP code: 404 with iris-federator

### ISSUE THREAD

**Issue by Thomas-Ulrich** [obspy/obspy#3497]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

I'm unable to download some waveforms with the iris-federator, with some very unspecific error.

(with eida-routing, I get

`obspy.clients.fdsn.header.FDSNNoDataException: No data available for request (requested time window might be out of bounds of valid station epochs).`)

### Code to Reproduce

```python
from obspy.clients.fdsn import RoutingClient

client = RoutingClient("iris-federator")
network = "KO"
station = "MLSB"
selected_band = "HH"
t1 = "2020-10-30T11:49:47.000000Z"
t2 = "2020-10-30T11:56:27.000000Z"

st_obs0 = client.get_waveforms(
    network=network,
    station=station,
    location="*",
    channel=f"{selected_band}*",
    starttime=t1,
    endtime=t2,
)
```

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "/export/dump/ulrich/test_automated_workflow/2020-10-30_Mw7_Greece_us7000c7y0_1slipnear_Samos/test.py", line 11, in <module>
    st_obs0 = client.get_waveforms(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 84, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 91, in _assert_attach_response_not_in_kwargs
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 335, in get_waveforms
    return self.get_waveforms_bulk([bulk], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 91, in _assert_attach_response_not_in_kwargs
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 84, in _assert_filename_not_in_kwargs
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/routing/federator_routing_client.py", line 82, in get_waveforms_bulk
    r = self._download(self._url + "/query", data=bulk_str,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/base.py", line 249, in _download
    self._handle_requests_http_error(r)
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 304, in _handle_requests_http_error
    raise_on_error(r.status_code, buf)
  File "/import/exception-dump/ulrich/myLibs/spack-packages/linux-debian12-zen2/gcc-12.2.0/python-venv-1.0-kycg6bwhpnzmabb53q37uzjzq3lytho4/lib/python3.11/site-packages/obspy/clients/fdsn/client.py", line 1881, in raise_on_error
    raise FDSNException("Unknown HTTP code: %i" % code, server_info)
obspy.clients.fdsn.header.FDSNException: Unknown HTTP code: 404
Detailed response of server:

 -- Error 404: No data matched request.
Request:
http://service.iris.edu/irisws/fedcatalog/1/query
Request Submitted:
2024/08/26 13:07:38 UTC
Service version:
Service: irisws-fedcatalog  version: 1.1.17
```

### ObsPy Version?

1.4.1

### Operating System?

Ubuntu

### Python Version?

3.11.2

### Installation Method?

pip

**Comment by megies** [comment]
I'm confused about this one. Did they change something on the server side? In case of no data it's supposed to return a HTTP 204 and not a HTTP 404. In principle, we could just treat 404 in the same way as we do treat a HTTP 204 response, but that is not at all ideal because 404 can happen also in case of a wrong URL.

It also seems that when using the POST option to specify the request, options like `nodata=204` are ignored and always a `404` is used on "no data".

http://service.iris.edu/irisws/fedcatalog/1/query?format=request&nodata=204&network=KO&station=MLSB&channel=HH*&starttime=2020-10-30T11:49:47&endtime=2020-10-30T11:49:55

```
$ cat mlsb.txt
format=request
nodata=204
KO MLSB * HH* 2020-10-30T11:49:47 2020-10-30T11:49:55
$ curl -L --data-binary @mlsb.txt http://service.iris.edu/irisws/fedcatalog/1/query
Error 404: No data matched request.

Request:
http://service.iris.edu/irisws/fedcatalog/1/query

Request Submitted:
2024/08/29 08:40:05 UTC

Service version:
Service: irisws-fedcatalog  version: 1.1.17
```

I'm a bit confused right now. Seems like on server side things were changed somehow

**Comment by megies** [comment]
@rcasey-earthscope, CC @chad-earthscope 

Valid request, with data available:

https://service.iris.edu/irisws/fedcatalog/1/query?net=FR&station=ISO&cha=BHZ&start=2008-09-01&end=2008-09-01T00:00:30

Returns:

```
DATACENTER=RESIF,http://www.resif.fr
DATASELECTSERVICE=http://ws.resif.fr/fdsnws/dataselect/1/
STATIONSERVICE=http://ws.resif.fr/fdsnws/station/1/
FR ISO 00 BHZ 2008-09-01T00:00:00 2008-09-01T00:00:30
```

Valid request with just time window changed so that there is no data:

https://service.iris.edu/irisws/fedcatalog/1/query?net=FR&station=ISO&cha=BHZ&start=1908-09-01&end=1908-09-01T00:00:30

Returns:

```
Error 404: No data matched request.

Request:
http://service.iris.edu/irisws/fedcatalog/1/query?net=FR&station=ISO&cha=BHZ&start=1908-09-01&end=1908-09-01T00:00:30

Request Submitted:
2024/08/29 08:44:57 UTC

Service version:
Service: irisws-fedcatalog  version: 1.1.17
```

The above is supposed to return a HTTP 204 instead as per FDSN WS official specification and also the IRIS FEDCATALOG WS specs. Looks like this was changed on server side at some point inadvertently.

On top of that, it seems that sometimes valid requests that have no data available glitch out and show a "Page not found 404" even, instead of a "No matching data 404", at least when used in the browser (even when specifying that 204 should be used in case of "no data"):

![Screenshot from 2024-08-29 10-50-48](https://github.com/user-attachments/assets/e60f27d4-2c22-43ca-b4db-b32f56e9bacb)

Also it seems that when using the POST option to formulate the request, "nodata=204" is ignored and always a 404 is returned in case of no data.

```
$ cat mlsb.txt
format=request
nodata=204
KO MLSB * HH* 2020-10-30T11:49:47 2020-10-30T11:49:55
$ curl -L --data-binary @mlsb.txt http://service.iris.edu/irisws/fedcatalog/1/query
Error 404: No data matched request.

Request:
http://service.iris.edu/irisws/fedcatalog/1/query

Request Submitted:
2024/08/29 08:40:05 UTC

Service version:
Service: irisws-fedcatalog  version: 1.1.17
```

**Comment by Thomas-Ulrich** [comment]
Thank you for checking out @megies !

**Comment by rcasey-earthscope** [comment]
Thank you for posting this.  I'll bring the 404 default behavior to the attention of the developer, though I can't promise an immediate change can occur.  There are two interesting points to make on this particular issue:

1. The web page documentation indicates that the return can be 204 or 404, with the default as 204.  Clearly the behavior does not follow that documentation.
2. Though we want IRISWS web services to be as close to FDSN-compliant as possible, this is not an official FDSN web service.  It is IRIS-only.  The irony of that for Fed Catalog is not lost on me.

We can either change the code or correct the documentation.  I have to check with the developer on this.

Regards,
-Rob
