### ISSUE TITLE
In FDSN client, it is possible for `server_info` to be a `timeout` object

### ISSUE THREAD

**Issue by mhearne-usgs** [obspy/obspy#3510]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

We have a rather complicated code base (gmprocess) that depends heavily on obspy. One of our processes uses the mass downloader, and today I saw this error: `AttributeError: 'timeout' object has no attribute 'splitlines'`. I have traced it in the current main branch to these lines: https://github.com/obspy/obspy/blob/master/obspy/clients/fdsn/client.py#L1849-L1851

It seems that at least in some cases of a timeout, server_info is not a string but a `timeout` object.

### Error Traceback

```Python traceback
Traceback (most recent call last):
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/gmprocess/apps/gmrecords.py", line 123, in mai
n
    self.args.func().main(self)
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/gmprocess/subcommands/autoshakemap.py", line 1
01, in main
    download.DownloadModule().main(gmrecords)
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/gmprocess/subcommands/download.py", line 64, i
n main
    download_utils.download_event_data(
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/gmprocess/utils/download_utils.py", line 69, i
n download_event_data
    tcollection, _ = fetch_data(
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/gmprocess/io/global_fetcher.py", line 128, in
fetch_data
    tstreams = fetcher.retrieve_data()
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/gmprocess/io/obspy/fdsn_fetcher.py", line 303,
 in retrieve_data
    mdl.download(
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/obspy/clients/fdsn/mass_downloader/mass_downlo
ader.py", line 208, in download
    helper.download_mseed(chunk_size_in_mb=download_chunk_size_in_mb,
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/obspy/clients/fdsn/mass_downloader/download_he
lpers.py", line 866, in download_mseed
    pool.map(
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/obspy/clients/fdsn/mass_downloader/download_he
lpers.py", line 852, in star_download_mseed
    ret_val = utils.download_and_split_mseed_bulk(
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/obspy/clients/fdsn/mass_downloader/utils.py",
line 224, in download_and_split_mseed_bulk
    client.get_waveforms_bulk(bulk, filename=temp_filename)
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/obspy/clients/fdsn/client.py", line 1051, in g
et_waveforms_bulk
    data_stream = self._download(
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/obspy/clients/fdsn/client.py", line 1486, in _
download
    raise_on_error(code, data)
  File "/home/autogmp/miniconda3/envs/autogmp/lib/python3.9/site-packages/obspy/clients/fdsn/client.py", line 1831, in r
aise_on_error
    line for line in server_info.splitlines() if line)
AttributeError: 'timeout' object has no attribute 'splitlines'
```

### ObsPy Version?

1.4.1

### Operating System?

Ubuntu

### Python Version?

3.9.19

### Installation Method?

pip

**Comment by megies** [comment]
seems to be a duplicate of or at least similar case like #3496. good to know we run into multiple types of objects though.

**Comment by megies** [comment]
@mhearne-usgs should be fixed in master
